//! Code specialization for union-split branches.
//!
//! This module provides functionality to generate specialized bytecode for
//! branches where types have been narrowed through union splitting.

use crate::compile::abstract_interp::TypeEnv;
use crate::compile::lattice::types::{ConcreteType, LatticeType};
use crate::inference_core::{CorePrimitive, CoreType};
use crate::ir::core::{BinaryOp, BuiltinOp, Expr, Literal, Stmt};
use crate::vm::instr::Instr;

/// Information about a specialized code path.
#[derive(Debug, Clone)]
pub struct SpecializedPath {
    /// The specialized type for this path
    pub specialized_type: ConcreteType,
    /// The type environment for this path
    pub env: TypeEnv,
    /// Generated bytecode instructions (placeholder for future work)
    pub instructions: Vec<Instr>,
}

/// Specialize a block of statements for a specific type.
///
/// This generates optimized bytecode knowing the exact type of variables,
/// enabling:
/// - Elimination of runtime type checks
/// - Use of specialized operations (e.g., specialized Int addition)
/// - Better optimization opportunities
///
/// # Arguments
///
/// * `block` - The statements to specialize
/// * `env` - The type environment with narrowed types
/// * `specialized_type` - The specific type this branch handles
///
/// # Returns
///
/// A vector of bytecode instructions. Returns empty when this lightweight
/// emitter cannot prove a safe specialized lowering without full `Compiler`
/// context.
///
/// # Implementation Status
///
/// This function has a small context-free emitter for straight-line returns of
/// literals and known primitive arithmetic. Full implementation still requires
/// deep integration with the `Compiler` struct:
///
/// 1. **Compiler State Access**: The main compiler maintains local variable maps,
///    slot allocations, and type tracking that would need to be available here.
///
/// 2. **Method Table Lookups**: Specialized dispatch requires access to compiled
///    method tables to resolve the correct specialized method.
///
/// 3. **Instruction Selection**: Choosing between dynamic and specialized
///    instructions (e.g., `AddI64` vs `DynamicAdd`) requires type context.
///
/// 4. **Control Flow**: Generating correct jump offsets and label resolution
///    requires the full compilation context.
///
/// # Future Work
///
/// Full implementation would involve:
/// - Creating a specialized `Compiler` context with narrowed types
/// - Compiling each statement with type-specialized codegen
/// - Eliminating redundant type checks (isa calls that are always true/false)
/// - Using specialized intrinsics (AddI64 instead of DynamicAdd)
/// - Inlining small type-specific operations
///
/// # See Also
///
/// - `analyze_specialization_opportunities`: Identifies which optimizations apply
/// - `crate::compile::stmt::compile_stmt`: The main statement compilation logic
pub fn specialize_block(
    block: &[Stmt],
    env: &TypeEnv,
    specialized_type: &ConcreteType,
) -> Vec<Instr> {
    // Analyze opportunities for debugging/metrics purposes
    let _opportunities = analyze_specialization_opportunities(block, env, specialized_type);

    let mut local_env = env.clone();
    let mut instructions = Vec::new();
    for stmt in block {
        if !emit_specialized_stmt(stmt, &mut local_env, &mut instructions) {
            return Vec::new();
        }
    }
    instructions
}

fn emit_specialized_stmt(stmt: &Stmt, env: &mut TypeEnv, instructions: &mut Vec<Instr>) -> bool {
    match stmt {
        Stmt::Assign { var, value, .. } => {
            let Some(value_ty) = emit_specialized_expr(value, env, instructions) else {
                return false;
            };
            if !emit_specialized_store(var, &value_ty, instructions) {
                return false;
            }
            env.set(var, LatticeType::Concrete(value_ty));
            true
        }
        Stmt::Return {
            value: Some(expr), ..
        } => match emit_specialized_expr(expr, env, instructions) {
            Some(ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64))) => {
                instructions.push(Instr::ReturnI64);
                true
            }
            Some(ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float64))) => {
                instructions.push(Instr::ReturnF64);
                true
            }
            Some(_) => {
                instructions.push(Instr::ReturnAny);
                true
            }
            None => false,
        },
        Stmt::Return { value: None, .. } => {
            instructions.push(Instr::ReturnNothing);
            true
        }
        Stmt::Expr { expr, .. } => {
            if emit_specialized_expr(expr, env, instructions).is_none() {
                return false;
            }
            instructions.push(Instr::Pop);
            true
        }
        _ => false,
    }
}

fn emit_specialized_store(name: &str, ty: &ConcreteType, instructions: &mut Vec<Instr>) -> bool {
    match ty {
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64)) => {
            instructions.push(Instr::StoreI64(name.to_string()))
        }
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float64)) => {
            instructions.push(Instr::StoreF64(name.to_string()))
        }
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float32)) => {
            instructions.push(Instr::StoreF32(name.to_string()))
        }
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float16)) => {
            instructions.push(Instr::StoreF16(name.to_string()))
        }
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool)) => {
            instructions.push(Instr::StoreBool(name.to_string()))
        }
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::String)) => {
            instructions.push(Instr::StoreStr(name.to_string()))
        }
        _ => return false,
    }
    true
}

fn emit_specialized_expr(
    expr: &Expr,
    env: &TypeEnv,
    instructions: &mut Vec<Instr>,
) -> Option<ConcreteType> {
    match expr {
        Expr::Literal(lit, _) => emit_specialized_literal(lit, instructions),
        Expr::Var(name, _) => emit_specialized_var(name, env, instructions),
        Expr::BinaryOp {
            left, right, op, ..
        } => emit_specialized_binary(op, left, right, env, instructions),
        _ => None,
    }
}

fn emit_specialized_literal(lit: &Literal, instructions: &mut Vec<Instr>) -> Option<ConcreteType> {
    match lit {
        Literal::Int(v) => {
            instructions.push(Instr::PushI64(*v));
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Int64,
            )))
        }
        Literal::Float(v) => {
            instructions.push(Instr::PushF64(*v));
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Float64,
            )))
        }
        Literal::Float32(v) => {
            instructions.push(Instr::PushF32(*v));
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Float32,
            )))
        }
        Literal::Float16(v) => {
            instructions.push(Instr::PushF16(*v));
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Float16,
            )))
        }
        Literal::Bool(v) => {
            instructions.push(Instr::PushBool(*v));
            Some(ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool)))
        }
        Literal::Str(v) => {
            instructions.push(Instr::PushStr(v.clone()));
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::String,
            )))
        }
        Literal::Char(v) => {
            instructions.push(Instr::PushChar(*v));
            Some(ConcreteType::Core(CoreType::Primitive(CorePrimitive::Char)))
        }
        Literal::Nothing => {
            instructions.push(Instr::PushNothing);
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Nothing,
            )))
        }
        _ => None,
    }
}

fn emit_specialized_var(
    name: &str,
    env: &TypeEnv,
    instructions: &mut Vec<Instr>,
) -> Option<ConcreteType> {
    match env.get(name).and_then(get_concrete_type)? {
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64)) => {
            instructions.push(Instr::LoadI64(name.to_string()));
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Int64,
            )))
        }
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float64)) => {
            instructions.push(Instr::LoadF64(name.to_string()));
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Float64,
            )))
        }
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float32)) => {
            instructions.push(Instr::LoadF32(name.to_string()));
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Float32,
            )))
        }
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float16)) => {
            instructions.push(Instr::LoadF16(name.to_string()));
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Float16,
            )))
        }
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool)) => {
            instructions.push(Instr::LoadBool(name.to_string()));
            Some(ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool)))
        }
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::String)) => {
            instructions.push(Instr::LoadStr(name.to_string()));
            Some(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::String,
            )))
        }
        _ => None,
    }
}

fn emit_specialized_binary(
    op: &BinaryOp,
    left: &Expr,
    right: &Expr,
    env: &TypeEnv,
    instructions: &mut Vec<Instr>,
) -> Option<ConcreteType> {
    let mut left_emitted = Vec::new();
    let left_ty = emit_specialized_expr(left, env, &mut left_emitted)?;
    let mut right_emitted = Vec::new();
    let right_ty = emit_specialized_expr(right, env, &mut right_emitted)?;
    let mut emitted = left_emitted;
    let left_instr_count = emitted.len();
    emitted.extend(right_emitted);

    let result_ty = match (left_ty, right_ty) {
        (
            ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64)),
            ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64)),
        ) => {
            if let Some(instr) = int64_comparison_instr(op) {
                emitted.push(instr);
                ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool))
            } else {
                let instr = match op {
                    BinaryOp::Add => Instr::AddI64,
                    BinaryOp::Sub => Instr::SubI64,
                    BinaryOp::Mul => Instr::MulI64,
                    BinaryOp::Mod => Instr::ModI64,
                    _ => return None,
                };
                emitted.push(instr);
                ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64))
            }
        }
        (
            ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float64)),
            ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float64)),
        ) => {
            if let Some(instr) = float64_comparison_instr(op) {
                emitted.push(instr);
                ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool))
            } else {
                let instr = match op {
                    BinaryOp::Add => Instr::AddF64,
                    BinaryOp::Sub => Instr::SubF64,
                    BinaryOp::Mul => Instr::MulF64,
                    BinaryOp::Div => Instr::DivF64,
                    _ => return None,
                };
                emitted.push(instr);
                ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float64))
            }
        }
        (
            ConcreteType::Core(CoreType::Primitive(CorePrimitive::String)),
            ConcreteType::Core(CoreType::Primitive(CorePrimitive::String)),
        ) => {
            let instr = match op {
                BinaryOp::Eq | BinaryOp::Ne => Instr::EqStr,
                BinaryOp::Lt => Instr::LtStr,
                BinaryOp::Le => Instr::LeStr,
                BinaryOp::Gt => Instr::GtStr,
                BinaryOp::Ge => Instr::GeStr,
                _ => return None,
            };
            emitted.push(instr);
            if matches!(op, BinaryOp::Ne) {
                emitted.push(Instr::NotBool);
            }
            ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool))
        }
        (
            ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool)),
            ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool)),
        ) => {
            let instr = match op {
                BinaryOp::Eq => Instr::EqI64,
                BinaryOp::Ne => Instr::NeI64,
                _ => return None,
            };
            emitted.insert(left_instr_count, Instr::BoolToI64);
            emitted.push(Instr::BoolToI64);
            emitted.push(instr);
            ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool))
        }
        _ => return None,
    };
    instructions.extend(emitted);
    Some(result_ty)
}

fn int64_comparison_instr(op: &BinaryOp) -> Option<Instr> {
    match op {
        BinaryOp::Lt => Some(Instr::LtI64),
        BinaryOp::Gt => Some(Instr::GtI64),
        BinaryOp::Le => Some(Instr::LeI64),
        BinaryOp::Ge => Some(Instr::GeI64),
        BinaryOp::Eq => Some(Instr::EqI64),
        BinaryOp::Ne => Some(Instr::NeI64),
        _ => None,
    }
}

fn float64_comparison_instr(op: &BinaryOp) -> Option<Instr> {
    match op {
        BinaryOp::Lt => Some(Instr::LtF64),
        BinaryOp::Gt => Some(Instr::GtF64),
        BinaryOp::Le => Some(Instr::LeF64),
        BinaryOp::Ge => Some(Instr::GeF64),
        BinaryOp::Eq => Some(Instr::EqF64),
        BinaryOp::Ne => Some(Instr::NeF64),
        _ => None,
    }
}

/// Create a specialized path for a given type and environment.
///
/// This is a convenience function that packages the specialized type,
/// environment, and generated instructions together.
pub fn create_specialized_path(
    block: &[Stmt],
    env: TypeEnv,
    specialized_type: ConcreteType,
) -> SpecializedPath {
    let instructions = specialize_block(block, &env, &specialized_type);

    SpecializedPath {
        specialized_type,
        env,
        instructions,
    }
}

/// Optimization opportunities for specialized code.
///
/// This enum describes the types of optimizations that can be applied
/// when generating specialized code for a known type.
#[derive(Debug, Clone, PartialEq)]
pub enum SpecializationOpportunity {
    /// Eliminate a runtime `isa` check (always true/false)
    EliminateTypeCheck,
    /// Use specialized arithmetic (e.g., Int-specific add)
    SpecializedArithmetic,
    /// Use specialized array indexing (e.g., known element type)
    SpecializedArrayAccess,
    /// Inline type-specific operations
    InlineOperation,
    /// Eliminate boxing/unboxing for known types
    EliminateBoxing,
}

/// Analyze optimization opportunities for a specialized block.
///
/// This function identifies which optimizations can be applied when
/// compiling a block with narrowed type information.
///
/// # Arguments
///
/// * `block` - The statements to analyze
/// * `env` - The type environment with narrowed types
/// * `specialized_type` - The specific type this branch handles
///
/// # Returns
///
/// A vector of applicable optimization opportunities.
pub fn analyze_specialization_opportunities(
    block: &[Stmt],
    env: &TypeEnv,
    specialized_type: &ConcreteType,
) -> Vec<SpecializationOpportunity> {
    let mut opportunities = Vec::new();

    for stmt in block {
        analyze_stmt_opportunities(stmt, env, specialized_type, &mut opportunities);
    }

    opportunities
}

/// Analyze optimization opportunities in a single statement.
fn analyze_stmt_opportunities(
    stmt: &Stmt,
    env: &TypeEnv,
    specialized_type: &ConcreteType,
    opportunities: &mut Vec<SpecializationOpportunity>,
) {
    match stmt {
        Stmt::If {
            condition,
            then_branch,
            else_branch,
            ..
        } => {
            // Check if condition contains an `isa` check that's always true/false
            if is_eliminable_type_check(condition, env, specialized_type) {
                opportunities.push(SpecializationOpportunity::EliminateTypeCheck);
            }

            // Recursively analyze branches
            for s in &then_branch.stmts {
                analyze_stmt_opportunities(s, env, specialized_type, opportunities);
            }
            if let Some(else_block) = else_branch {
                for s in &else_block.stmts {
                    analyze_stmt_opportunities(s, env, specialized_type, opportunities);
                }
            }
        }

        Stmt::Assign { value, .. } | Stmt::AddAssign { value, .. } => {
            analyze_expr_opportunities(value, env, specialized_type, opportunities);
        }

        Stmt::For { body, .. }
        | Stmt::ForEach { body, .. }
        | Stmt::While { body, .. }
        | Stmt::TestSet { body, .. } => {
            for s in &body.stmts {
                analyze_stmt_opportunities(s, env, specialized_type, opportunities);
            }
        }

        Stmt::Return {
            value: Some(expr), ..
        } => {
            analyze_expr_opportunities(expr, env, specialized_type, opportunities);
        }

        Stmt::Expr { expr, .. } => {
            analyze_expr_opportunities(expr, env, specialized_type, opportunities);
        }

        Stmt::Block(block) => {
            for s in &block.stmts {
                analyze_stmt_opportunities(s, env, specialized_type, opportunities);
            }
        }

        _ => {}
    }
}

/// Analyze optimization opportunities in an expression.
fn analyze_expr_opportunities(
    expr: &Expr,
    env: &TypeEnv,
    specialized_type: &ConcreteType,
    opportunities: &mut Vec<SpecializationOpportunity>,
) {
    match expr {
        Expr::BinaryOp {
            left, right, op, ..
        } => {
            // Check if this is arithmetic on known numeric types
            if is_specializable_arithmetic(op, left, right, env, specialized_type) {
                opportunities.push(SpecializationOpportunity::SpecializedArithmetic);
            }

            // Recurse
            analyze_expr_opportunities(left, env, specialized_type, opportunities);
            analyze_expr_opportunities(right, env, specialized_type, opportunities);
        }

        Expr::Index { array, indices, .. } => {
            // Check if array indexing can be optimized
            if can_specialize_array_access(array, env, specialized_type) {
                opportunities.push(SpecializationOpportunity::SpecializedArrayAccess);
            }

            analyze_expr_opportunities(array, env, specialized_type, opportunities);
            for idx in indices {
                analyze_expr_opportunities(idx, env, specialized_type, opportunities);
            }
        }

        Expr::Call { args, .. } => {
            // Check if the call can be inlined for known types
            if can_inline_for_type(specialized_type) {
                opportunities.push(SpecializationOpportunity::InlineOperation);
            }

            for arg in args {
                analyze_expr_opportunities(arg, env, specialized_type, opportunities);
            }
        }

        Expr::Builtin { name, args, .. } => {
            // Check for eliminable isa checks
            if matches!(name, BuiltinOp::Isa)
                && args.len() == 2
                && is_eliminable_isa_check(&args[0], &args[1], env, specialized_type)
            {
                opportunities.push(SpecializationOpportunity::EliminateTypeCheck);
            }

            for arg in args {
                analyze_expr_opportunities(arg, env, specialized_type, opportunities);
            }
        }

        _ => {}
    }
}

/// Check if a condition contains a type check that's always true or false.
fn is_eliminable_type_check(
    condition: &Expr,
    env: &TypeEnv,
    specialized_type: &ConcreteType,
) -> bool {
    match condition {
        Expr::Builtin {
            name: BuiltinOp::Isa,
            args,
            ..
        } if args.len() == 2 => is_eliminable_isa_check(&args[0], &args[1], env, specialized_type),
        _ => false,
    }
}

/// Check if an isa check can be eliminated because we know the type.
fn is_eliminable_isa_check(
    var_expr: &Expr,
    _type_expr: &Expr,
    env: &TypeEnv,
    specialized_type: &ConcreteType,
) -> bool {
    if let Expr::Var(var_name, _) = var_expr {
        if let Some(var_type) = env.get(var_name) {
            // If the variable's type in the environment matches the specialized type,
            // the isa check result is statically known
            return get_concrete_type(var_type) == Some(specialized_type.clone());
        }
    }
    false
}

/// Extract a concrete type from a LatticeType if possible.
fn get_concrete_type(ty: &LatticeType) -> Option<ConcreteType> {
    match ty {
        LatticeType::Concrete(ct) => Some(ct.clone()),
        LatticeType::Const(cv) => Some(cv.to_concrete_type()),
        _ => None,
    }
}

/// Check if arithmetic can be specialized for numeric types.
fn is_specializable_arithmetic(
    op: &BinaryOp,
    left: &Expr,
    right: &Expr,
    env: &TypeEnv,
    specialized_type: &ConcreteType,
) -> bool {
    // Check if this is an arithmetic operation
    let is_arithmetic = matches!(
        op,
        BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul | BinaryOp::Div | BinaryOp::Mod
    );

    if !is_arithmetic {
        return false;
    }

    // Check if the operands involve the specialized type
    let left_is_specialized = expr_uses_specialized_type(left, env, specialized_type);
    let right_is_specialized = expr_uses_specialized_type(right, env, specialized_type);

    // At least one operand should be of the specialized type
    (left_is_specialized || right_is_specialized) && is_numeric_type(specialized_type)
}

/// Check if an expression uses the specialized type.
fn expr_uses_specialized_type(expr: &Expr, env: &TypeEnv, specialized_type: &ConcreteType) -> bool {
    match expr {
        Expr::Var(name, _) => {
            if let Some(var_type) = env.get(name) {
                return get_concrete_type(var_type) == Some(specialized_type.clone());
            }
            false
        }
        _ => false,
    }
}

/// Check if array access can be specialized.
fn can_specialize_array_access(
    object: &Expr,
    env: &TypeEnv,
    specialized_type: &ConcreteType,
) -> bool {
    if let Expr::Var(name, _) = object {
        if let Some(var_type) = env.get(name) {
            // Check if the variable has an array type with matching element type
            if let Some(ConcreteType::Array { element, .. }) = get_concrete_type(var_type) {
                return *element == *specialized_type;
            }
        }
    }
    false
}

/// Check if operations can be inlined for the specialized type.
fn can_inline_for_type(specialized_type: &ConcreteType) -> bool {
    // Primitive types have well-known operations that can be inlined
    matches!(
        specialized_type,
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float64))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::String))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::Char))
    )
}

/// Check if a type is numeric.
fn is_numeric_type(ty: &ConcreteType) -> bool {
    matches!(
        ty,
        ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int8))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int16))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int32))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int128))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::UInt8))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::UInt16))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::UInt32))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::UInt64))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::UInt128))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float32))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float64))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::BigInt))
            | ConcreteType::Core(CoreType::Primitive(CorePrimitive::BigFloat))
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compile::lattice::types::LatticeType;
    use crate::ir::core::{Block, Literal};
    use crate::span::Span;

    fn dummy_span() -> Span {
        Span::new(0, 0, 0, 0, 0, 0)
    }

    #[test]
    fn test_create_specialized_path() {
        let env = TypeEnv::new();
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64));

        let block = vec![Stmt::Return {
            value: Some(Expr::Literal(Literal::Int(42), dummy_span())),
            span: dummy_span(),
        }];

        let path = create_specialized_path(&block, env.clone(), specialized_type.clone());

        assert_eq!(path.specialized_type, specialized_type);
        assert!(matches!(
            path.instructions.as_slice(),
            [Instr::PushI64(42), Instr::ReturnI64]
        ));
    }

    #[test]
    fn test_specialize_block_emits_literal_return_issue_5077() {
        let env = TypeEnv::new();
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::String));

        let block = vec![Stmt::Return {
            value: Some(Expr::Literal(
                Literal::Str("hello".to_string()),
                dummy_span(),
            )),
            span: dummy_span(),
        }];

        let instructions = specialize_block(&block, &env, &specialized_type);

        assert!(matches!(instructions.as_slice(), [
            Instr::PushStr(value),
            Instr::ReturnAny
        ] if value == "hello"));
    }

    #[test]
    fn test_specialize_block_emits_known_i64_arithmetic_issue_5077() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Int64,
            ))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64));

        let block = vec![Stmt::Return {
            value: Some(Expr::BinaryOp {
                op: BinaryOp::Mul,
                left: Box::new(Expr::Var("x".to_string(), dummy_span())),
                right: Box::new(Expr::Literal(Literal::Int(2), dummy_span())),
                span: dummy_span(),
            }),
            span: dummy_span(),
        }];

        let instructions = specialize_block(&block, &env, &specialized_type);

        assert!(matches!(instructions.as_slice(), [
            Instr::LoadI64(name),
            Instr::PushI64(2),
            Instr::MulI64,
            Instr::ReturnI64
        ] if name == "x"));
    }

    #[test]
    fn test_specialize_block_emits_known_i64_comparison_issue_5077() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Int64,
            ))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64));

        let block = vec![Stmt::Return {
            value: Some(Expr::BinaryOp {
                op: BinaryOp::Le,
                left: Box::new(Expr::Var("x".to_string(), dummy_span())),
                right: Box::new(Expr::Literal(Literal::Int(10), dummy_span())),
                span: dummy_span(),
            }),
            span: dummy_span(),
        }];

        let instructions = specialize_block(&block, &env, &specialized_type);

        assert!(matches!(instructions.as_slice(), [
            Instr::LoadI64(name),
            Instr::PushI64(10),
            Instr::LeI64,
            Instr::ReturnAny
        ] if name == "x"));
    }

    #[test]
    fn test_specialize_block_emits_known_f64_comparison_issue_5077() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Float64,
            ))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float64));

        let block = vec![Stmt::Return {
            value: Some(Expr::BinaryOp {
                op: BinaryOp::Gt,
                left: Box::new(Expr::Var("x".to_string(), dummy_span())),
                right: Box::new(Expr::Literal(Literal::Float(2.5), dummy_span())),
                span: dummy_span(),
            }),
            span: dummy_span(),
        }];

        let instructions = specialize_block(&block, &env, &specialized_type);

        assert!(matches!(instructions.as_slice(), [
            Instr::LoadF64(name),
            Instr::PushF64(value),
            Instr::GtF64,
            Instr::ReturnAny
        ] if name == "x" && *value == 2.5));
    }

    #[test]
    fn test_specialize_block_emits_known_string_comparison_issue_5077() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::String,
            ))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::String));

        let block = vec![Stmt::Return {
            value: Some(Expr::BinaryOp {
                op: BinaryOp::Ne,
                left: Box::new(Expr::Var("x".to_string(), dummy_span())),
                right: Box::new(Expr::Literal(
                    Literal::Str("done".to_string()),
                    dummy_span(),
                )),
                span: dummy_span(),
            }),
            span: dummy_span(),
        }];

        let instructions = specialize_block(&block, &env, &specialized_type);

        assert!(matches!(instructions.as_slice(), [
            Instr::LoadStr(name),
            Instr::PushStr(value),
            Instr::EqStr,
            Instr::NotBool,
            Instr::ReturnAny
        ] if name == "x" && value == "done"));
    }

    #[test]
    fn test_specialize_block_emits_known_bool_comparison_issue_5077() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Bool));

        let block = vec![Stmt::Return {
            value: Some(Expr::BinaryOp {
                op: BinaryOp::Ne,
                left: Box::new(Expr::Var("x".to_string(), dummy_span())),
                right: Box::new(Expr::Literal(Literal::Bool(false), dummy_span())),
                span: dummy_span(),
            }),
            span: dummy_span(),
        }];

        let instructions = specialize_block(&block, &env, &specialized_type);

        assert!(matches!(instructions.as_slice(), [
            Instr::LoadBool(name),
            Instr::BoolToI64,
            Instr::PushBool(false),
            Instr::BoolToI64,
            Instr::NeI64,
            Instr::ReturnAny
        ] if name == "x"));
    }

    #[test]
    fn test_specialize_block_emits_assignment_and_reuses_narrowed_local_issue_5077() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Int64,
            ))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64));

        let block = vec![
            Stmt::Assign {
                var: "y".to_string(),
                value: Expr::BinaryOp {
                    op: BinaryOp::Add,
                    left: Box::new(Expr::Var("x".to_string(), dummy_span())),
                    right: Box::new(Expr::Literal(Literal::Int(1), dummy_span())),
                    span: dummy_span(),
                },
                span: dummy_span(),
            },
            Stmt::Return {
                value: Some(Expr::Var("y".to_string(), dummy_span())),
                span: dummy_span(),
            },
        ];

        let instructions = specialize_block(&block, &env, &specialized_type);

        assert!(matches!(instructions.as_slice(), [
            Instr::LoadI64(x_name),
            Instr::PushI64(1),
            Instr::AddI64,
            Instr::StoreI64(y_store),
            Instr::LoadI64(y_load),
            Instr::ReturnI64
        ] if x_name == "x" && y_store == "y" && y_load == "y"));
    }

    #[test]
    fn test_specialize_block_emits_expression_statement_pop_issue_5077() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Int64,
            ))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64));

        let block = vec![
            Stmt::Expr {
                expr: Expr::BinaryOp {
                    op: BinaryOp::Mul,
                    left: Box::new(Expr::Var("x".to_string(), dummy_span())),
                    right: Box::new(Expr::Literal(Literal::Int(2), dummy_span())),
                    span: dummy_span(),
                },
                span: dummy_span(),
            },
            Stmt::Return {
                value: Some(Expr::Var("x".to_string(), dummy_span())),
                span: dummy_span(),
            },
        ];

        let instructions = specialize_block(&block, &env, &specialized_type);

        assert!(matches!(instructions.as_slice(), [
            Instr::LoadI64(expr_name),
            Instr::PushI64(2),
            Instr::MulI64,
            Instr::Pop,
            Instr::LoadI64(return_name),
            Instr::ReturnI64
        ] if expr_name == "x" && return_name == "x"));
    }

    #[test]
    fn test_analyze_arithmetic_opportunities() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Int64,
            ))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64));

        // x + 1
        let block = vec![Stmt::Expr {
            expr: Expr::BinaryOp {
                op: BinaryOp::Add,
                left: Box::new(Expr::Var("x".to_string(), dummy_span())),
                right: Box::new(Expr::Literal(Literal::Int(1), dummy_span())),
                span: dummy_span(),
            },
            span: dummy_span(),
        }];

        let opportunities = analyze_specialization_opportunities(&block, &env, &specialized_type);

        // Should identify specialized arithmetic opportunity
        assert!(opportunities.contains(&SpecializationOpportunity::SpecializedArithmetic));
    }

    #[test]
    fn test_analyze_type_check_elimination() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Int64,
            ))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64));

        // if isa(x, Int64) ... end
        let block = vec![Stmt::If {
            condition: Expr::Builtin {
                name: BuiltinOp::Isa,
                args: vec![
                    Expr::Var("x".to_string(), dummy_span()),
                    Expr::Var("Int64".to_string(), dummy_span()),
                ],
                span: dummy_span(),
            },
            then_branch: Block {
                stmts: vec![],
                span: dummy_span(),
            },
            else_branch: None,
            span: dummy_span(),
        }];

        let opportunities = analyze_specialization_opportunities(&block, &env, &specialized_type);

        // Should identify eliminable type check
        assert!(opportunities.contains(&SpecializationOpportunity::EliminateTypeCheck));
    }

    #[test]
    fn test_analyze_inlining_opportunity() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Int64,
            ))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Int64));

        // f(x) where x is known to be Int64
        let block = vec![Stmt::Expr {
            expr: Expr::Call {
                function: "f".to_string(),
                args: vec![Expr::Var("x".to_string(), dummy_span())],
                kwargs: vec![],
                splat_mask: vec![],
                kwargs_splat_mask: vec![],
                span: dummy_span(),
            },
            span: dummy_span(),
        }];

        let opportunities = analyze_specialization_opportunities(&block, &env, &specialized_type);

        // Should identify inlining opportunity for primitive type
        assert!(opportunities.contains(&SpecializationOpportunity::InlineOperation));
    }

    #[test]
    fn test_analyze_nested_blocks() {
        let mut env = TypeEnv::new();
        env.set(
            "x",
            LatticeType::Concrete(ConcreteType::Core(CoreType::Primitive(
                CorePrimitive::Float64,
            ))),
        );
        let specialized_type = ConcreteType::Core(CoreType::Primitive(CorePrimitive::Float64));

        // for i in 1:10
        //     x * 2.0
        // end
        let block = vec![Stmt::For {
            var: "i".to_string(),
            start: Expr::Literal(Literal::Int(1), dummy_span()),
            end: Expr::Literal(Literal::Int(10), dummy_span()),
            step: None,
            body: Block {
                stmts: vec![Stmt::Expr {
                    expr: Expr::BinaryOp {
                        op: BinaryOp::Mul,
                        left: Box::new(Expr::Var("x".to_string(), dummy_span())),
                        right: Box::new(Expr::Literal(Literal::Float(2.0), dummy_span())),
                        span: dummy_span(),
                    },
                    span: dummy_span(),
                }],
                span: dummy_span(),
            },
            span: dummy_span(),
        }];

        let opportunities = analyze_specialization_opportunities(&block, &env, &specialized_type);

        // Should find specialized arithmetic in nested loop body
        assert!(opportunities.contains(&SpecializationOpportunity::SpecializedArithmetic));
    }

    #[test]
    fn test_is_numeric_type() {
        assert!(is_numeric_type(&ConcreteType::Core(CoreType::Primitive(
            CorePrimitive::Int64
        ))));
        assert!(is_numeric_type(&ConcreteType::Core(CoreType::Primitive(
            CorePrimitive::Float64
        ))));
        assert!(is_numeric_type(&ConcreteType::Core(CoreType::Primitive(
            CorePrimitive::Int32
        ))));
        assert!(is_numeric_type(&ConcreteType::Core(CoreType::Primitive(
            CorePrimitive::BigInt
        ))));

        assert!(!is_numeric_type(&ConcreteType::Core(CoreType::Primitive(
            CorePrimitive::String
        ))));
        assert!(!is_numeric_type(&ConcreteType::Core(CoreType::Primitive(
            CorePrimitive::Bool
        ))));
        assert!(!is_numeric_type(&ConcreteType::Core(CoreType::Primitive(
            CorePrimitive::Nothing
        ))));
    }
}
