# Generated by scripts/gen_generator_trait_matrix_fixture.jl for Issue #9566.
# Differential generator/iterator trait matrix. Each assertion records
# upstream julia's result for one {transform, base, consumer} cell.
#
# Divergent cells are excluded here and tracked in
# docs/vm/GENERATOR_TRAIT_MATRIX_SKIPLIST.tsv. Re-run the generator after
# removing a fixed row from that skiplist to promote it into this fixture.

using Test

matrix_dispatch_9566(x::Int64) = x
matrix_dispatch_9566(x::Float64) = 2
matrix_dispatch_9566(x::String) = 3
matrix_dispatch_9566(x) = 4

matrix_typed_base_9566() = [1, 2, 3]
matrix_any_base_9566() = Any[1, 2.0, "s"]

function matrix_iteratorsize_label_9566(iter)
    trait = Base.IteratorSize(iter)
    if trait isa Base.HasShape{1}
        return "HasShape{1}"
    elseif trait isa Base.HasShape{2}
        return "HasShape{2}"
    elseif trait isa Base.HasShape{3}
        return "HasShape{3}"
    elseif trait isa Base.HasLength
        return "HasLength"
    elseif trait isa Base.SizeUnknown
        return "SizeUnknown"
    elseif trait isa Base.IsInfinite
        return "IsInfinite"
    end
    return string(typeof(trait))
end

function matrix_iteratoreltype_label_9566(iter)
    trait = Base.IteratorEltype(iter)
    if trait isa Base.HasEltype
        return "HasEltype"
    elseif trait isa Base.EltypeUnknown
        return "EltypeUnknown"
    end
    return string(typeof(trait))
end

matrix_collect_summary_9566(value) = (string(typeof(value)), repr(value))

function matrix_for_sum_9566(iter)
    acc = 0
    for value in iter
        acc += value
    end
    return acc
end

struct MatrixIterOnly9566
    n::Int64
end

Base.iterate(iter::MatrixIterOnly9566, state=1) =
    state > iter.n ? nothing : (state, state + 1)

matrix_iteronly_9566() = MatrixIterOnly9566(5)

function matrix_dynamic_loopsum_9566(xs)
    acc = 0
    for x in xs
        acc += x
    end
    return acc
end

# Workaround: evaluate generated generator cells through function-scope
# helpers because @testset block scope loses lifted generator body
# bindings for trait queries (Issue #10137).
function matrix_cell_M_MAP_TYPED_ARRAY_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) for x in matrix_typed_base_9566()))
end

function matrix_cell_M_MAP_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) for x in matrix_typed_base_9566()))
end

function matrix_cell_M_MAP_TYPED_ARRAY_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) for x in matrix_typed_base_9566())))
end

function matrix_cell_M_MAP_TYPED_ARRAY_SUM_9566()
    return sum((matrix_dispatch_9566(x) for x in matrix_typed_base_9566()))
end

function matrix_cell_M_MAP_TYPED_ARRAY_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) for x in matrix_typed_base_9566()); init=0)
end

function matrix_cell_M_MAP_TYPED_ARRAY_FIRST_9566()
    return first((matrix_dispatch_9566(x) for x in matrix_typed_base_9566()))
end

function matrix_cell_M_MAP_TYPED_ARRAY_LENGTH_9566()
    return length((matrix_dispatch_9566(x) for x in matrix_typed_base_9566()))
end

function matrix_cell_M_MAP_TYPED_ARRAY_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) for x in matrix_typed_base_9566()))
end

function matrix_cell_M_FILTER_TYPED_ARRAY_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) for x in matrix_typed_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) for x in matrix_typed_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_TYPED_ARRAY_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) for x in matrix_typed_base_9566() if matrix_dispatch_9566(x) >= 2)))
end

function matrix_cell_M_FILTER_TYPED_ARRAY_SUM_9566()
    return sum((matrix_dispatch_9566(x) for x in matrix_typed_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_TYPED_ARRAY_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) for x in matrix_typed_base_9566() if matrix_dispatch_9566(x) >= 2); init=0)
end

function matrix_cell_M_FILTER_TYPED_ARRAY_FIRST_9566()
    return first((matrix_dispatch_9566(x) for x in matrix_typed_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_TYPED_ARRAY_LENGTH_9566()
    return length((matrix_dispatch_9566(x) for x in matrix_typed_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_TYPED_ARRAY_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) for x in matrix_typed_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FLATTEN_TYPED_ARRAY_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566() for y in 1:2))
end

function matrix_cell_M_FLATTEN_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566() for y in 1:2))
end

function matrix_cell_M_FLATTEN_TYPED_ARRAY_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566() for y in 1:2)))
end

function matrix_cell_M_FLATTEN_TYPED_ARRAY_SUM_9566()
    return sum((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566() for y in 1:2))
end

function matrix_cell_M_FLATTEN_TYPED_ARRAY_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566() for y in 1:2); init=0)
end

function matrix_cell_M_FLATTEN_TYPED_ARRAY_FIRST_9566()
    return first((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566() for y in 1:2))
end

function matrix_cell_M_FLATTEN_TYPED_ARRAY_LENGTH_9566()
    return length((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566() for y in 1:2))
end

function matrix_cell_M_FLATTEN_TYPED_ARRAY_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566() for y in 1:2))
end

function matrix_cell_M_PRODUCT_TYPED_ARRAY_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566(), y in 1:2))
end

function matrix_cell_M_PRODUCT_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566(), y in 1:2))
end

function matrix_cell_M_PRODUCT_TYPED_ARRAY_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566(), y in 1:2)))
end

function matrix_cell_M_PRODUCT_TYPED_ARRAY_SUM_9566()
    return sum((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566(), y in 1:2))
end

function matrix_cell_M_PRODUCT_TYPED_ARRAY_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566(), y in 1:2); init=0)
end

function matrix_cell_M_PRODUCT_TYPED_ARRAY_FIRST_9566()
    return first((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566(), y in 1:2))
end

function matrix_cell_M_PRODUCT_TYPED_ARRAY_LENGTH_9566()
    return length((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566(), y in 1:2))
end

function matrix_cell_M_PRODUCT_TYPED_ARRAY_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) + y for x in matrix_typed_base_9566(), y in 1:2))
end

function matrix_cell_M_ZIP_TYPED_ARRAY_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_typed_base_9566(), 10:12)))
end

function matrix_cell_M_ZIP_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_typed_base_9566(), 10:12)))
end

function matrix_cell_M_ZIP_TYPED_ARRAY_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_typed_base_9566(), 10:12))))
end

function matrix_cell_M_ZIP_TYPED_ARRAY_SUM_9566()
    return sum((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_typed_base_9566(), 10:12)))
end

function matrix_cell_M_ZIP_TYPED_ARRAY_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_typed_base_9566(), 10:12)); init=0)
end

function matrix_cell_M_ZIP_TYPED_ARRAY_FIRST_9566()
    return first((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_typed_base_9566(), 10:12)))
end

function matrix_cell_M_ZIP_TYPED_ARRAY_LENGTH_9566()
    return length((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_typed_base_9566(), 10:12)))
end

function matrix_cell_M_ZIP_TYPED_ARRAY_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_typed_base_9566(), 10:12)))
end

function matrix_cell_M_ENUMERATE_TYPED_ARRAY_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_typed_base_9566())))
end

function matrix_cell_M_ENUMERATE_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_typed_base_9566())))
end

function matrix_cell_M_ENUMERATE_TYPED_ARRAY_COLLECT_9566()
    return matrix_collect_summary_9566(collect((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_typed_base_9566()))))
end

function matrix_cell_M_ENUMERATE_TYPED_ARRAY_SUM_9566()
    return sum((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_typed_base_9566())))
end

function matrix_cell_M_ENUMERATE_TYPED_ARRAY_FOLDL_9566()
    return foldl(+, (i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_typed_base_9566())); init=0)
end

function matrix_cell_M_ENUMERATE_TYPED_ARRAY_FIRST_9566()
    return first((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_typed_base_9566())))
end

function matrix_cell_M_ENUMERATE_TYPED_ARRAY_LENGTH_9566()
    return length((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_typed_base_9566())))
end

function matrix_cell_M_ENUMERATE_TYPED_ARRAY_FORLOOP_9566()
    return matrix_for_sum_9566((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_typed_base_9566())))
end

function matrix_cell_M_MAP_RANGE_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) for x in 1:3))
end

function matrix_cell_M_MAP_RANGE_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) for x in 1:3))
end

function matrix_cell_M_MAP_RANGE_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) for x in 1:3)))
end

function matrix_cell_M_MAP_RANGE_SUM_9566()
    return sum((matrix_dispatch_9566(x) for x in 1:3))
end

function matrix_cell_M_MAP_RANGE_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) for x in 1:3); init=0)
end

function matrix_cell_M_MAP_RANGE_FIRST_9566()
    return first((matrix_dispatch_9566(x) for x in 1:3))
end

function matrix_cell_M_MAP_RANGE_LENGTH_9566()
    return length((matrix_dispatch_9566(x) for x in 1:3))
end

function matrix_cell_M_MAP_RANGE_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) for x in 1:3))
end

function matrix_cell_M_FILTER_RANGE_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) for x in 1:3 if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_RANGE_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) for x in 1:3 if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_RANGE_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) for x in 1:3 if matrix_dispatch_9566(x) >= 2)))
end

function matrix_cell_M_FILTER_RANGE_SUM_9566()
    return sum((matrix_dispatch_9566(x) for x in 1:3 if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_RANGE_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) for x in 1:3 if matrix_dispatch_9566(x) >= 2); init=0)
end

function matrix_cell_M_FILTER_RANGE_FIRST_9566()
    return first((matrix_dispatch_9566(x) for x in 1:3 if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_RANGE_LENGTH_9566()
    return length((matrix_dispatch_9566(x) for x in 1:3 if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_RANGE_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) for x in 1:3 if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FLATTEN_RANGE_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) + y for x in 1:3 for y in 1:2))
end

function matrix_cell_M_FLATTEN_RANGE_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) + y for x in 1:3 for y in 1:2))
end

function matrix_cell_M_FLATTEN_RANGE_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) + y for x in 1:3 for y in 1:2)))
end

function matrix_cell_M_FLATTEN_RANGE_SUM_9566()
    return sum((matrix_dispatch_9566(x) + y for x in 1:3 for y in 1:2))
end

function matrix_cell_M_FLATTEN_RANGE_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) + y for x in 1:3 for y in 1:2); init=0)
end

function matrix_cell_M_FLATTEN_RANGE_FIRST_9566()
    return first((matrix_dispatch_9566(x) + y for x in 1:3 for y in 1:2))
end

function matrix_cell_M_FLATTEN_RANGE_LENGTH_9566()
    return length((matrix_dispatch_9566(x) + y for x in 1:3 for y in 1:2))
end

function matrix_cell_M_FLATTEN_RANGE_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) + y for x in 1:3 for y in 1:2))
end

function matrix_cell_M_PRODUCT_RANGE_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) + y for x in 1:3, y in 1:2))
end

function matrix_cell_M_PRODUCT_RANGE_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) + y for x in 1:3, y in 1:2))
end

function matrix_cell_M_PRODUCT_RANGE_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) + y for x in 1:3, y in 1:2)))
end

function matrix_cell_M_PRODUCT_RANGE_SUM_9566()
    return sum((matrix_dispatch_9566(x) + y for x in 1:3, y in 1:2))
end

function matrix_cell_M_PRODUCT_RANGE_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) + y for x in 1:3, y in 1:2); init=0)
end

function matrix_cell_M_PRODUCT_RANGE_FIRST_9566()
    return first((matrix_dispatch_9566(x) + y for x in 1:3, y in 1:2))
end

function matrix_cell_M_PRODUCT_RANGE_LENGTH_9566()
    return length((matrix_dispatch_9566(x) + y for x in 1:3, y in 1:2))
end

function matrix_cell_M_PRODUCT_RANGE_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) + y for x in 1:3, y in 1:2))
end

function matrix_cell_M_ZIP_RANGE_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) + y for (x, y) in zip(1:3, 10:12)))
end

function matrix_cell_M_ZIP_RANGE_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) + y for (x, y) in zip(1:3, 10:12)))
end

function matrix_cell_M_ZIP_RANGE_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) + y for (x, y) in zip(1:3, 10:12))))
end

function matrix_cell_M_ZIP_RANGE_SUM_9566()
    return sum((matrix_dispatch_9566(x) + y for (x, y) in zip(1:3, 10:12)))
end

function matrix_cell_M_ZIP_RANGE_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) + y for (x, y) in zip(1:3, 10:12)); init=0)
end

function matrix_cell_M_ZIP_RANGE_FIRST_9566()
    return first((matrix_dispatch_9566(x) + y for (x, y) in zip(1:3, 10:12)))
end

function matrix_cell_M_ZIP_RANGE_LENGTH_9566()
    return length((matrix_dispatch_9566(x) + y for (x, y) in zip(1:3, 10:12)))
end

function matrix_cell_M_ZIP_RANGE_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) + y for (x, y) in zip(1:3, 10:12)))
end

function matrix_cell_M_ENUMERATE_RANGE_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((i + matrix_dispatch_9566(x) for (i, x) in enumerate(1:3)))
end

function matrix_cell_M_ENUMERATE_RANGE_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((i + matrix_dispatch_9566(x) for (i, x) in enumerate(1:3)))
end

function matrix_cell_M_ENUMERATE_RANGE_COLLECT_9566()
    return matrix_collect_summary_9566(collect((i + matrix_dispatch_9566(x) for (i, x) in enumerate(1:3))))
end

function matrix_cell_M_ENUMERATE_RANGE_SUM_9566()
    return sum((i + matrix_dispatch_9566(x) for (i, x) in enumerate(1:3)))
end

function matrix_cell_M_ENUMERATE_RANGE_FOLDL_9566()
    return foldl(+, (i + matrix_dispatch_9566(x) for (i, x) in enumerate(1:3)); init=0)
end

function matrix_cell_M_ENUMERATE_RANGE_FIRST_9566()
    return first((i + matrix_dispatch_9566(x) for (i, x) in enumerate(1:3)))
end

function matrix_cell_M_ENUMERATE_RANGE_LENGTH_9566()
    return length((i + matrix_dispatch_9566(x) for (i, x) in enumerate(1:3)))
end

function matrix_cell_M_ENUMERATE_RANGE_FORLOOP_9566()
    return matrix_for_sum_9566((i + matrix_dispatch_9566(x) for (i, x) in enumerate(1:3)))
end

function matrix_cell_M_MAP_ANY_MIXED_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) for x in matrix_any_base_9566()))
end

function matrix_cell_M_MAP_ANY_MIXED_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) for x in matrix_any_base_9566()))
end

function matrix_cell_M_MAP_ANY_MIXED_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) for x in matrix_any_base_9566())))
end

function matrix_cell_M_MAP_ANY_MIXED_SUM_9566()
    return sum((matrix_dispatch_9566(x) for x in matrix_any_base_9566()))
end

function matrix_cell_M_MAP_ANY_MIXED_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) for x in matrix_any_base_9566()); init=0)
end

function matrix_cell_M_MAP_ANY_MIXED_FIRST_9566()
    return first((matrix_dispatch_9566(x) for x in matrix_any_base_9566()))
end

function matrix_cell_M_MAP_ANY_MIXED_LENGTH_9566()
    return length((matrix_dispatch_9566(x) for x in matrix_any_base_9566()))
end

function matrix_cell_M_MAP_ANY_MIXED_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) for x in matrix_any_base_9566()))
end

function matrix_cell_M_FILTER_ANY_MIXED_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) for x in matrix_any_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_ANY_MIXED_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) for x in matrix_any_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_ANY_MIXED_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) for x in matrix_any_base_9566() if matrix_dispatch_9566(x) >= 2)))
end

function matrix_cell_M_FILTER_ANY_MIXED_SUM_9566()
    return sum((matrix_dispatch_9566(x) for x in matrix_any_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_ANY_MIXED_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) for x in matrix_any_base_9566() if matrix_dispatch_9566(x) >= 2); init=0)
end

function matrix_cell_M_FILTER_ANY_MIXED_FIRST_9566()
    return first((matrix_dispatch_9566(x) for x in matrix_any_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_ANY_MIXED_LENGTH_9566()
    return length((matrix_dispatch_9566(x) for x in matrix_any_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FILTER_ANY_MIXED_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) for x in matrix_any_base_9566() if matrix_dispatch_9566(x) >= 2))
end

function matrix_cell_M_FLATTEN_ANY_MIXED_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566() for y in 1:2))
end

function matrix_cell_M_FLATTEN_ANY_MIXED_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566() for y in 1:2))
end

function matrix_cell_M_FLATTEN_ANY_MIXED_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566() for y in 1:2)))
end

function matrix_cell_M_FLATTEN_ANY_MIXED_SUM_9566()
    return sum((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566() for y in 1:2))
end

function matrix_cell_M_FLATTEN_ANY_MIXED_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) + y for x in matrix_any_base_9566() for y in 1:2); init=0)
end

function matrix_cell_M_FLATTEN_ANY_MIXED_FIRST_9566()
    return first((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566() for y in 1:2))
end

function matrix_cell_M_FLATTEN_ANY_MIXED_LENGTH_9566()
    return length((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566() for y in 1:2))
end

function matrix_cell_M_FLATTEN_ANY_MIXED_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566() for y in 1:2))
end

function matrix_cell_M_PRODUCT_ANY_MIXED_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566(), y in 1:2))
end

function matrix_cell_M_PRODUCT_ANY_MIXED_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566(), y in 1:2))
end

function matrix_cell_M_PRODUCT_ANY_MIXED_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566(), y in 1:2)))
end

function matrix_cell_M_PRODUCT_ANY_MIXED_SUM_9566()
    return sum((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566(), y in 1:2))
end

function matrix_cell_M_PRODUCT_ANY_MIXED_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) + y for x in matrix_any_base_9566(), y in 1:2); init=0)
end

function matrix_cell_M_PRODUCT_ANY_MIXED_FIRST_9566()
    return first((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566(), y in 1:2))
end

function matrix_cell_M_PRODUCT_ANY_MIXED_LENGTH_9566()
    return length((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566(), y in 1:2))
end

function matrix_cell_M_PRODUCT_ANY_MIXED_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) + y for x in matrix_any_base_9566(), y in 1:2))
end

function matrix_cell_M_ZIP_ANY_MIXED_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_any_base_9566(), 10:12)))
end

function matrix_cell_M_ZIP_ANY_MIXED_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_any_base_9566(), 10:12)))
end

function matrix_cell_M_ZIP_ANY_MIXED_COLLECT_9566()
    return matrix_collect_summary_9566(collect((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_any_base_9566(), 10:12))))
end

function matrix_cell_M_ZIP_ANY_MIXED_SUM_9566()
    return sum((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_any_base_9566(), 10:12)))
end

function matrix_cell_M_ZIP_ANY_MIXED_FOLDL_9566()
    return foldl(+, (matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_any_base_9566(), 10:12)); init=0)
end

function matrix_cell_M_ZIP_ANY_MIXED_FIRST_9566()
    return first((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_any_base_9566(), 10:12)))
end

function matrix_cell_M_ZIP_ANY_MIXED_LENGTH_9566()
    return length((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_any_base_9566(), 10:12)))
end

function matrix_cell_M_ZIP_ANY_MIXED_FORLOOP_9566()
    return matrix_for_sum_9566((matrix_dispatch_9566(x) + y for (x, y) in zip(matrix_any_base_9566(), 10:12)))
end

function matrix_cell_M_ENUMERATE_ANY_MIXED_ITERATOR_SIZE_9566()
    return matrix_iteratorsize_label_9566((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_any_base_9566())))
end

function matrix_cell_M_ENUMERATE_ANY_MIXED_ITERATOR_ELTYPE_9566()
    return matrix_iteratoreltype_label_9566((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_any_base_9566())))
end

function matrix_cell_M_ENUMERATE_ANY_MIXED_COLLECT_9566()
    return matrix_collect_summary_9566(collect((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_any_base_9566()))))
end

function matrix_cell_M_ENUMERATE_ANY_MIXED_SUM_9566()
    return sum((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_any_base_9566())))
end

function matrix_cell_M_ENUMERATE_ANY_MIXED_FOLDL_9566()
    return foldl(+, (i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_any_base_9566())); init=0)
end

function matrix_cell_M_ENUMERATE_ANY_MIXED_FIRST_9566()
    return first((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_any_base_9566())))
end

function matrix_cell_M_ENUMERATE_ANY_MIXED_LENGTH_9566()
    return length((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_any_base_9566())))
end

function matrix_cell_M_ENUMERATE_ANY_MIXED_FORLOOP_9566()
    return matrix_for_sum_9566((i + matrix_dispatch_9566(x) for (i, x) in enumerate(matrix_any_base_9566())))
end

function matrix_cell_BUG_9403_DYNAMIC_FORLOOP_9566()
    return matrix_dynamic_loopsum_9566(matrix_iteronly_9566())
end

function matrix_cell_BUG_9405_NESTED_FILTERED_COLLECT_9566()
    return matrix_collect_summary_9566(collect(v for v in (x for x in 1:5 if x > 2)))
end

function matrix_cell_BUG_9405_NESTED_FILTERED_MAP_9566()
    return matrix_collect_summary_9566(map(x -> x + 1, (v for v in (x for x in 1:5 if x > 2))))
end

function matrix_cell_BUG_9405_NESTED_FILTERED_SUM_9566()
    return sum(v for v in (x^2 for x in 1:5 if isodd(x)))
end

function matrix_cell_BUG_9385_COMPREHENSION_ANY_NARROW_9566()
    return matrix_collect_summary_9566([matrix_dispatch_9566(x) for x in matrix_any_base_9566()])
end

function matrix_cell_BUG_9457_GENERATOR_GETINDEX_METHODERROR_9566()
    return ((x for x in 1:3)[1])
end

function matrix_cell_BUG_9533_TUPLE_BROADCAST_ABS_9566()
    return matrix_collect_summary_9566(abs.((-1, -2, -3)))
end

function matrix_cell_BUG_9547_TUPLE_BROADCAST_COMPARE_9566()
    return matrix_collect_summary_9566((1, 2, 3) .< (2, 2, 2))
end

@testset "generator trait matrix - closed_bug (Issue #9566)" begin
    let result = matrix_cell_BUG_9385_COMPREHENSION_ANY_NARROW_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # BUG_9385_COMPREHENSION_ANY_NARROW comprehension/any_mixed/collect #9385,#9566
        @test repr(result) == "(\"Vector{Int64}\", \"[1, 2, 3]\")"  # BUG_9385_COMPREHENSION_ANY_NARROW comprehension/any_mixed/collect #9385,#9566
    end
    @test_throws MethodError matrix_cell_BUG_9457_GENERATOR_GETINDEX_METHODERROR_9566()  # BUG_9457_GENERATOR_GETINDEX_METHODERROR indexing/range/getindex #9457,#9566
    let result = matrix_cell_BUG_9533_TUPLE_BROADCAST_ABS_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # BUG_9533_TUPLE_BROADCAST_ABS tuple_broadcast/tuple/broadcast #9533,#9566
        @test repr(result) == "(\"Tuple{Int64, Int64, Int64}\", \"(1, 2, 3)\")"  # BUG_9533_TUPLE_BROADCAST_ABS tuple_broadcast/tuple/broadcast #9533,#9566
    end
    let result = matrix_cell_BUG_9547_TUPLE_BROADCAST_COMPARE_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # BUG_9547_TUPLE_BROADCAST_COMPARE tuple_broadcast/tuple/broadcast #9547,#9566
        @test repr(result) == "(\"Tuple{Bool, Bool, Bool}\", \"(true, false, false)\")"  # BUG_9547_TUPLE_BROADCAST_COMPARE tuple_broadcast/tuple/broadcast #9547,#9566
    end
end

@testset "generator trait matrix - matrix (Issue #9566)" begin
    let result = matrix_cell_M_MAP_TYPED_ARRAY_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_MAP_TYPED_ARRAY_ITERATOR_SIZE map/typed_array/iterator_size #9566,#9393
        @test repr(result) == "\"HasShape{1}\""  # M_MAP_TYPED_ARRAY_ITERATOR_SIZE map/typed_array/iterator_size #9566,#9393
    end
    let result = matrix_cell_M_MAP_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_MAP_TYPED_ARRAY_ITERATOR_ELTYPE map/typed_array/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_MAP_TYPED_ARRAY_ITERATOR_ELTYPE map/typed_array/iterator_eltype #9566
    end
    let result = matrix_cell_M_MAP_TYPED_ARRAY_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_MAP_TYPED_ARRAY_COLLECT map/typed_array/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[1, 2, 3]\")"  # M_MAP_TYPED_ARRAY_COLLECT map/typed_array/collect #9566
    end
    let result = matrix_cell_M_MAP_TYPED_ARRAY_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_TYPED_ARRAY_SUM map/typed_array/sum #9566
        @test repr(result) == "6"  # M_MAP_TYPED_ARRAY_SUM map/typed_array/sum #9566
    end
    let result = matrix_cell_M_MAP_TYPED_ARRAY_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_TYPED_ARRAY_FOLDL map/typed_array/foldl #9566
        @test repr(result) == "6"  # M_MAP_TYPED_ARRAY_FOLDL map/typed_array/foldl #9566
    end
    let result = matrix_cell_M_MAP_TYPED_ARRAY_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_TYPED_ARRAY_FIRST map/typed_array/first #9566
        @test repr(result) == "1"  # M_MAP_TYPED_ARRAY_FIRST map/typed_array/first #9566
    end
    let result = matrix_cell_M_MAP_TYPED_ARRAY_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_TYPED_ARRAY_LENGTH map/typed_array/length #9566
        @test repr(result) == "3"  # M_MAP_TYPED_ARRAY_LENGTH map/typed_array/length #9566
    end
    let result = matrix_cell_M_MAP_TYPED_ARRAY_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_TYPED_ARRAY_FORLOOP map/typed_array/forloop #9566
        @test repr(result) == "6"  # M_MAP_TYPED_ARRAY_FORLOOP map/typed_array/forloop #9566
    end
    let result = matrix_cell_M_FILTER_TYPED_ARRAY_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_FILTER_TYPED_ARRAY_ITERATOR_SIZE filter/typed_array/iterator_size #9566
        @test repr(result) == "\"SizeUnknown\""  # M_FILTER_TYPED_ARRAY_ITERATOR_SIZE filter/typed_array/iterator_size #9566
    end
    let result = matrix_cell_M_FILTER_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_FILTER_TYPED_ARRAY_ITERATOR_ELTYPE filter/typed_array/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_FILTER_TYPED_ARRAY_ITERATOR_ELTYPE filter/typed_array/iterator_eltype #9566
    end
    let result = matrix_cell_M_FILTER_TYPED_ARRAY_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_FILTER_TYPED_ARRAY_COLLECT filter/typed_array/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[2, 3]\")"  # M_FILTER_TYPED_ARRAY_COLLECT filter/typed_array/collect #9566
    end
    let result = matrix_cell_M_FILTER_TYPED_ARRAY_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_TYPED_ARRAY_SUM filter/typed_array/sum #9566
        @test repr(result) == "5"  # M_FILTER_TYPED_ARRAY_SUM filter/typed_array/sum #9566
    end
    let result = matrix_cell_M_FILTER_TYPED_ARRAY_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_TYPED_ARRAY_FOLDL filter/typed_array/foldl #9566
        @test repr(result) == "5"  # M_FILTER_TYPED_ARRAY_FOLDL filter/typed_array/foldl #9566
    end
    let result = matrix_cell_M_FILTER_TYPED_ARRAY_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_TYPED_ARRAY_FIRST filter/typed_array/first #9566
        @test repr(result) == "2"  # M_FILTER_TYPED_ARRAY_FIRST filter/typed_array/first #9566
    end
    @test_throws MethodError matrix_cell_M_FILTER_TYPED_ARRAY_LENGTH_9566()  # M_FILTER_TYPED_ARRAY_LENGTH filter/typed_array/length #9566
    let result = matrix_cell_M_FILTER_TYPED_ARRAY_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_TYPED_ARRAY_FORLOOP filter/typed_array/forloop #9566
        @test repr(result) == "5"  # M_FILTER_TYPED_ARRAY_FORLOOP filter/typed_array/forloop #9566
    end
    let result = matrix_cell_M_FLATTEN_TYPED_ARRAY_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_FLATTEN_TYPED_ARRAY_ITERATOR_SIZE flatten/typed_array/iterator_size #9566
        @test repr(result) == "\"SizeUnknown\""  # M_FLATTEN_TYPED_ARRAY_ITERATOR_SIZE flatten/typed_array/iterator_size #9566
    end
    let result = matrix_cell_M_FLATTEN_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_FLATTEN_TYPED_ARRAY_ITERATOR_ELTYPE flatten/typed_array/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_FLATTEN_TYPED_ARRAY_ITERATOR_ELTYPE flatten/typed_array/iterator_eltype #9566
    end
    let result = matrix_cell_M_FLATTEN_TYPED_ARRAY_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_FLATTEN_TYPED_ARRAY_COLLECT flatten/typed_array/collect #9566,#9438
        @test repr(result) == "(\"Vector{Int64}\", \"[2, 3, 3, 4, 4, 5]\")"  # M_FLATTEN_TYPED_ARRAY_COLLECT flatten/typed_array/collect #9566,#9438
    end
    let result = matrix_cell_M_FLATTEN_TYPED_ARRAY_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_TYPED_ARRAY_SUM flatten/typed_array/sum #9566
        @test repr(result) == "21"  # M_FLATTEN_TYPED_ARRAY_SUM flatten/typed_array/sum #9566
    end
    let result = matrix_cell_M_FLATTEN_TYPED_ARRAY_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_TYPED_ARRAY_FOLDL flatten/typed_array/foldl #9566
        @test repr(result) == "21"  # M_FLATTEN_TYPED_ARRAY_FOLDL flatten/typed_array/foldl #9566
    end
    let result = matrix_cell_M_FLATTEN_TYPED_ARRAY_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_TYPED_ARRAY_FIRST flatten/typed_array/first #9566
        @test repr(result) == "2"  # M_FLATTEN_TYPED_ARRAY_FIRST flatten/typed_array/first #9566
    end
    @test_throws ArgumentError matrix_cell_M_FLATTEN_TYPED_ARRAY_LENGTH_9566()  # M_FLATTEN_TYPED_ARRAY_LENGTH flatten/typed_array/length #9566
    let result = matrix_cell_M_FLATTEN_TYPED_ARRAY_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_TYPED_ARRAY_FORLOOP flatten/typed_array/forloop #9566
        @test repr(result) == "21"  # M_FLATTEN_TYPED_ARRAY_FORLOOP flatten/typed_array/forloop #9566
    end
    let result = matrix_cell_M_PRODUCT_TYPED_ARRAY_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_PRODUCT_TYPED_ARRAY_ITERATOR_SIZE product/typed_array/iterator_size #9566
        @test repr(result) == "\"HasShape{2}\""  # M_PRODUCT_TYPED_ARRAY_ITERATOR_SIZE product/typed_array/iterator_size #9566
    end
    let result = matrix_cell_M_PRODUCT_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_PRODUCT_TYPED_ARRAY_ITERATOR_ELTYPE product/typed_array/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_PRODUCT_TYPED_ARRAY_ITERATOR_ELTYPE product/typed_array/iterator_eltype #9566
    end
    let result = matrix_cell_M_PRODUCT_TYPED_ARRAY_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_PRODUCT_TYPED_ARRAY_COLLECT product/typed_array/collect #9566
        @test repr(result) == "(\"Matrix{Int64}\", \"[2 3; 3 4; 4 5]\")"  # M_PRODUCT_TYPED_ARRAY_COLLECT product/typed_array/collect #9566
    end
    let result = matrix_cell_M_PRODUCT_TYPED_ARRAY_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_TYPED_ARRAY_SUM product/typed_array/sum #9566
        @test repr(result) == "21"  # M_PRODUCT_TYPED_ARRAY_SUM product/typed_array/sum #9566
    end
    let result = matrix_cell_M_PRODUCT_TYPED_ARRAY_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_TYPED_ARRAY_FOLDL product/typed_array/foldl #9566
        @test repr(result) == "21"  # M_PRODUCT_TYPED_ARRAY_FOLDL product/typed_array/foldl #9566
    end
    let result = matrix_cell_M_PRODUCT_TYPED_ARRAY_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_TYPED_ARRAY_FIRST product/typed_array/first #9566
        @test repr(result) == "2"  # M_PRODUCT_TYPED_ARRAY_FIRST product/typed_array/first #9566
    end
    let result = matrix_cell_M_PRODUCT_TYPED_ARRAY_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_TYPED_ARRAY_LENGTH product/typed_array/length #9566
        @test repr(result) == "6"  # M_PRODUCT_TYPED_ARRAY_LENGTH product/typed_array/length #9566
    end
    let result = matrix_cell_M_PRODUCT_TYPED_ARRAY_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_TYPED_ARRAY_FORLOOP product/typed_array/forloop #9566
        @test repr(result) == "21"  # M_PRODUCT_TYPED_ARRAY_FORLOOP product/typed_array/forloop #9566
    end
    let result = matrix_cell_M_ZIP_TYPED_ARRAY_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_ZIP_TYPED_ARRAY_ITERATOR_SIZE zip/typed_array/iterator_size #9566
        @test repr(result) == "\"HasShape{1}\""  # M_ZIP_TYPED_ARRAY_ITERATOR_SIZE zip/typed_array/iterator_size #9566
    end
    let result = matrix_cell_M_ZIP_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_ZIP_TYPED_ARRAY_ITERATOR_ELTYPE zip/typed_array/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_ZIP_TYPED_ARRAY_ITERATOR_ELTYPE zip/typed_array/iterator_eltype #9566
    end
    let result = matrix_cell_M_ZIP_TYPED_ARRAY_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_ZIP_TYPED_ARRAY_COLLECT zip/typed_array/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[11, 13, 15]\")"  # M_ZIP_TYPED_ARRAY_COLLECT zip/typed_array/collect #9566
    end
    let result = matrix_cell_M_ZIP_TYPED_ARRAY_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_TYPED_ARRAY_SUM zip/typed_array/sum #9566
        @test repr(result) == "39"  # M_ZIP_TYPED_ARRAY_SUM zip/typed_array/sum #9566
    end
    let result = matrix_cell_M_ZIP_TYPED_ARRAY_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_TYPED_ARRAY_FOLDL zip/typed_array/foldl #9566
        @test repr(result) == "39"  # M_ZIP_TYPED_ARRAY_FOLDL zip/typed_array/foldl #9566
    end
    let result = matrix_cell_M_ZIP_TYPED_ARRAY_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_TYPED_ARRAY_FIRST zip/typed_array/first #9566
        @test repr(result) == "11"  # M_ZIP_TYPED_ARRAY_FIRST zip/typed_array/first #9566
    end
    let result = matrix_cell_M_ZIP_TYPED_ARRAY_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_TYPED_ARRAY_LENGTH zip/typed_array/length #9566
        @test repr(result) == "3"  # M_ZIP_TYPED_ARRAY_LENGTH zip/typed_array/length #9566
    end
    let result = matrix_cell_M_ZIP_TYPED_ARRAY_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_TYPED_ARRAY_FORLOOP zip/typed_array/forloop #9566
        @test repr(result) == "39"  # M_ZIP_TYPED_ARRAY_FORLOOP zip/typed_array/forloop #9566
    end
    let result = matrix_cell_M_ENUMERATE_TYPED_ARRAY_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_ENUMERATE_TYPED_ARRAY_ITERATOR_SIZE enumerate/typed_array/iterator_size #9566
        @test repr(result) == "\"HasShape{1}\""  # M_ENUMERATE_TYPED_ARRAY_ITERATOR_SIZE enumerate/typed_array/iterator_size #9566
    end
    let result = matrix_cell_M_ENUMERATE_TYPED_ARRAY_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_ENUMERATE_TYPED_ARRAY_ITERATOR_ELTYPE enumerate/typed_array/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_ENUMERATE_TYPED_ARRAY_ITERATOR_ELTYPE enumerate/typed_array/iterator_eltype #9566
    end
    let result = matrix_cell_M_ENUMERATE_TYPED_ARRAY_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_ENUMERATE_TYPED_ARRAY_COLLECT enumerate/typed_array/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[2, 4, 6]\")"  # M_ENUMERATE_TYPED_ARRAY_COLLECT enumerate/typed_array/collect #9566
    end
    let result = matrix_cell_M_ENUMERATE_TYPED_ARRAY_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_TYPED_ARRAY_SUM enumerate/typed_array/sum #9566
        @test repr(result) == "12"  # M_ENUMERATE_TYPED_ARRAY_SUM enumerate/typed_array/sum #9566
    end
    let result = matrix_cell_M_ENUMERATE_TYPED_ARRAY_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_TYPED_ARRAY_FOLDL enumerate/typed_array/foldl #9566
        @test repr(result) == "12"  # M_ENUMERATE_TYPED_ARRAY_FOLDL enumerate/typed_array/foldl #9566
    end
    let result = matrix_cell_M_ENUMERATE_TYPED_ARRAY_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_TYPED_ARRAY_FIRST enumerate/typed_array/first #9566
        @test repr(result) == "2"  # M_ENUMERATE_TYPED_ARRAY_FIRST enumerate/typed_array/first #9566
    end
    let result = matrix_cell_M_ENUMERATE_TYPED_ARRAY_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_TYPED_ARRAY_LENGTH enumerate/typed_array/length #9566
        @test repr(result) == "3"  # M_ENUMERATE_TYPED_ARRAY_LENGTH enumerate/typed_array/length #9566
    end
    let result = matrix_cell_M_ENUMERATE_TYPED_ARRAY_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_TYPED_ARRAY_FORLOOP enumerate/typed_array/forloop #9566
        @test repr(result) == "12"  # M_ENUMERATE_TYPED_ARRAY_FORLOOP enumerate/typed_array/forloop #9566
    end
    let result = matrix_cell_M_MAP_RANGE_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_MAP_RANGE_ITERATOR_SIZE map/range/iterator_size #9566
        @test repr(result) == "\"HasShape{1}\""  # M_MAP_RANGE_ITERATOR_SIZE map/range/iterator_size #9566
    end
    let result = matrix_cell_M_MAP_RANGE_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_MAP_RANGE_ITERATOR_ELTYPE map/range/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_MAP_RANGE_ITERATOR_ELTYPE map/range/iterator_eltype #9566
    end
    let result = matrix_cell_M_MAP_RANGE_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_MAP_RANGE_COLLECT map/range/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[1, 2, 3]\")"  # M_MAP_RANGE_COLLECT map/range/collect #9566
    end
    let result = matrix_cell_M_MAP_RANGE_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_RANGE_SUM map/range/sum #9566
        @test repr(result) == "6"  # M_MAP_RANGE_SUM map/range/sum #9566
    end
    let result = matrix_cell_M_MAP_RANGE_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_RANGE_FOLDL map/range/foldl #9566
        @test repr(result) == "6"  # M_MAP_RANGE_FOLDL map/range/foldl #9566
    end
    let result = matrix_cell_M_MAP_RANGE_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_RANGE_FIRST map/range/first #9566
        @test repr(result) == "1"  # M_MAP_RANGE_FIRST map/range/first #9566
    end
    let result = matrix_cell_M_MAP_RANGE_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_RANGE_LENGTH map/range/length #9566
        @test repr(result) == "3"  # M_MAP_RANGE_LENGTH map/range/length #9566
    end
    let result = matrix_cell_M_MAP_RANGE_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_RANGE_FORLOOP map/range/forloop #9566
        @test repr(result) == "6"  # M_MAP_RANGE_FORLOOP map/range/forloop #9566
    end
    let result = matrix_cell_M_FILTER_RANGE_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_FILTER_RANGE_ITERATOR_SIZE filter/range/iterator_size #9566
        @test repr(result) == "\"SizeUnknown\""  # M_FILTER_RANGE_ITERATOR_SIZE filter/range/iterator_size #9566
    end
    let result = matrix_cell_M_FILTER_RANGE_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_FILTER_RANGE_ITERATOR_ELTYPE filter/range/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_FILTER_RANGE_ITERATOR_ELTYPE filter/range/iterator_eltype #9566
    end
    let result = matrix_cell_M_FILTER_RANGE_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_FILTER_RANGE_COLLECT filter/range/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[2, 3]\")"  # M_FILTER_RANGE_COLLECT filter/range/collect #9566
    end
    let result = matrix_cell_M_FILTER_RANGE_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_RANGE_SUM filter/range/sum #9566
        @test repr(result) == "5"  # M_FILTER_RANGE_SUM filter/range/sum #9566
    end
    let result = matrix_cell_M_FILTER_RANGE_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_RANGE_FOLDL filter/range/foldl #9566
        @test repr(result) == "5"  # M_FILTER_RANGE_FOLDL filter/range/foldl #9566
    end
    let result = matrix_cell_M_FILTER_RANGE_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_RANGE_FIRST filter/range/first #9566
        @test repr(result) == "2"  # M_FILTER_RANGE_FIRST filter/range/first #9566
    end
    @test_throws MethodError matrix_cell_M_FILTER_RANGE_LENGTH_9566()  # M_FILTER_RANGE_LENGTH filter/range/length #9566
    let result = matrix_cell_M_FILTER_RANGE_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_RANGE_FORLOOP filter/range/forloop #9566
        @test repr(result) == "5"  # M_FILTER_RANGE_FORLOOP filter/range/forloop #9566
    end
    let result = matrix_cell_M_FLATTEN_RANGE_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_FLATTEN_RANGE_ITERATOR_SIZE flatten/range/iterator_size #9566
        @test repr(result) == "\"SizeUnknown\""  # M_FLATTEN_RANGE_ITERATOR_SIZE flatten/range/iterator_size #9566
    end
    let result = matrix_cell_M_FLATTEN_RANGE_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_FLATTEN_RANGE_ITERATOR_ELTYPE flatten/range/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_FLATTEN_RANGE_ITERATOR_ELTYPE flatten/range/iterator_eltype #9566
    end
    let result = matrix_cell_M_FLATTEN_RANGE_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_FLATTEN_RANGE_COLLECT flatten/range/collect #9566,#9438
        @test repr(result) == "(\"Vector{Int64}\", \"[2, 3, 3, 4, 4, 5]\")"  # M_FLATTEN_RANGE_COLLECT flatten/range/collect #9566,#9438
    end
    let result = matrix_cell_M_FLATTEN_RANGE_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_RANGE_SUM flatten/range/sum #9566
        @test repr(result) == "21"  # M_FLATTEN_RANGE_SUM flatten/range/sum #9566
    end
    let result = matrix_cell_M_FLATTEN_RANGE_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_RANGE_FOLDL flatten/range/foldl #9566
        @test repr(result) == "21"  # M_FLATTEN_RANGE_FOLDL flatten/range/foldl #9566
    end
    let result = matrix_cell_M_FLATTEN_RANGE_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_RANGE_FIRST flatten/range/first #9566
        @test repr(result) == "2"  # M_FLATTEN_RANGE_FIRST flatten/range/first #9566
    end
    @test_throws ArgumentError matrix_cell_M_FLATTEN_RANGE_LENGTH_9566()  # M_FLATTEN_RANGE_LENGTH flatten/range/length #9566
    let result = matrix_cell_M_FLATTEN_RANGE_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_RANGE_FORLOOP flatten/range/forloop #9566
        @test repr(result) == "21"  # M_FLATTEN_RANGE_FORLOOP flatten/range/forloop #9566
    end
    let result = matrix_cell_M_PRODUCT_RANGE_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_PRODUCT_RANGE_ITERATOR_SIZE product/range/iterator_size #9566
        @test repr(result) == "\"HasShape{2}\""  # M_PRODUCT_RANGE_ITERATOR_SIZE product/range/iterator_size #9566
    end
    let result = matrix_cell_M_PRODUCT_RANGE_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_PRODUCT_RANGE_ITERATOR_ELTYPE product/range/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_PRODUCT_RANGE_ITERATOR_ELTYPE product/range/iterator_eltype #9566
    end
    let result = matrix_cell_M_PRODUCT_RANGE_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_PRODUCT_RANGE_COLLECT product/range/collect #9566
        @test repr(result) == "(\"Matrix{Int64}\", \"[2 3; 3 4; 4 5]\")"  # M_PRODUCT_RANGE_COLLECT product/range/collect #9566
    end
    let result = matrix_cell_M_PRODUCT_RANGE_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_RANGE_SUM product/range/sum #9566
        @test repr(result) == "21"  # M_PRODUCT_RANGE_SUM product/range/sum #9566
    end
    let result = matrix_cell_M_PRODUCT_RANGE_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_RANGE_FOLDL product/range/foldl #9566
        @test repr(result) == "21"  # M_PRODUCT_RANGE_FOLDL product/range/foldl #9566
    end
    let result = matrix_cell_M_PRODUCT_RANGE_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_RANGE_FIRST product/range/first #9566
        @test repr(result) == "2"  # M_PRODUCT_RANGE_FIRST product/range/first #9566
    end
    let result = matrix_cell_M_PRODUCT_RANGE_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_RANGE_LENGTH product/range/length #9566
        @test repr(result) == "6"  # M_PRODUCT_RANGE_LENGTH product/range/length #9566
    end
    let result = matrix_cell_M_PRODUCT_RANGE_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_RANGE_FORLOOP product/range/forloop #9566
        @test repr(result) == "21"  # M_PRODUCT_RANGE_FORLOOP product/range/forloop #9566
    end
    let result = matrix_cell_M_ZIP_RANGE_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_ZIP_RANGE_ITERATOR_SIZE zip/range/iterator_size #9566
        @test repr(result) == "\"HasShape{1}\""  # M_ZIP_RANGE_ITERATOR_SIZE zip/range/iterator_size #9566
    end
    let result = matrix_cell_M_ZIP_RANGE_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_ZIP_RANGE_ITERATOR_ELTYPE zip/range/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_ZIP_RANGE_ITERATOR_ELTYPE zip/range/iterator_eltype #9566
    end
    let result = matrix_cell_M_ZIP_RANGE_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_ZIP_RANGE_COLLECT zip/range/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[11, 13, 15]\")"  # M_ZIP_RANGE_COLLECT zip/range/collect #9566
    end
    let result = matrix_cell_M_ZIP_RANGE_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_RANGE_SUM zip/range/sum #9566
        @test repr(result) == "39"  # M_ZIP_RANGE_SUM zip/range/sum #9566
    end
    let result = matrix_cell_M_ZIP_RANGE_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_RANGE_FOLDL zip/range/foldl #9566
        @test repr(result) == "39"  # M_ZIP_RANGE_FOLDL zip/range/foldl #9566
    end
    let result = matrix_cell_M_ZIP_RANGE_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_RANGE_FIRST zip/range/first #9566
        @test repr(result) == "11"  # M_ZIP_RANGE_FIRST zip/range/first #9566
    end
    let result = matrix_cell_M_ZIP_RANGE_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_RANGE_LENGTH zip/range/length #9566
        @test repr(result) == "3"  # M_ZIP_RANGE_LENGTH zip/range/length #9566
    end
    let result = matrix_cell_M_ZIP_RANGE_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_RANGE_FORLOOP zip/range/forloop #9566
        @test repr(result) == "39"  # M_ZIP_RANGE_FORLOOP zip/range/forloop #9566
    end
    let result = matrix_cell_M_ENUMERATE_RANGE_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_ENUMERATE_RANGE_ITERATOR_SIZE enumerate/range/iterator_size #9566
        @test repr(result) == "\"HasShape{1}\""  # M_ENUMERATE_RANGE_ITERATOR_SIZE enumerate/range/iterator_size #9566
    end
    let result = matrix_cell_M_ENUMERATE_RANGE_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_ENUMERATE_RANGE_ITERATOR_ELTYPE enumerate/range/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_ENUMERATE_RANGE_ITERATOR_ELTYPE enumerate/range/iterator_eltype #9566
    end
    let result = matrix_cell_M_ENUMERATE_RANGE_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_ENUMERATE_RANGE_COLLECT enumerate/range/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[2, 4, 6]\")"  # M_ENUMERATE_RANGE_COLLECT enumerate/range/collect #9566
    end
    let result = matrix_cell_M_ENUMERATE_RANGE_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_RANGE_SUM enumerate/range/sum #9566
        @test repr(result) == "12"  # M_ENUMERATE_RANGE_SUM enumerate/range/sum #9566
    end
    let result = matrix_cell_M_ENUMERATE_RANGE_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_RANGE_FOLDL enumerate/range/foldl #9566
        @test repr(result) == "12"  # M_ENUMERATE_RANGE_FOLDL enumerate/range/foldl #9566
    end
    let result = matrix_cell_M_ENUMERATE_RANGE_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_RANGE_FIRST enumerate/range/first #9566
        @test repr(result) == "2"  # M_ENUMERATE_RANGE_FIRST enumerate/range/first #9566
    end
    let result = matrix_cell_M_ENUMERATE_RANGE_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_RANGE_LENGTH enumerate/range/length #9566
        @test repr(result) == "3"  # M_ENUMERATE_RANGE_LENGTH enumerate/range/length #9566
    end
    let result = matrix_cell_M_ENUMERATE_RANGE_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_RANGE_FORLOOP enumerate/range/forloop #9566
        @test repr(result) == "12"  # M_ENUMERATE_RANGE_FORLOOP enumerate/range/forloop #9566
    end
    let result = matrix_cell_M_MAP_ANY_MIXED_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_MAP_ANY_MIXED_ITERATOR_SIZE map/any_mixed/iterator_size #9566
        @test repr(result) == "\"HasShape{1}\""  # M_MAP_ANY_MIXED_ITERATOR_SIZE map/any_mixed/iterator_size #9566
    end
    let result = matrix_cell_M_MAP_ANY_MIXED_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_MAP_ANY_MIXED_ITERATOR_ELTYPE map/any_mixed/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_MAP_ANY_MIXED_ITERATOR_ELTYPE map/any_mixed/iterator_eltype #9566
    end
    let result = matrix_cell_M_MAP_ANY_MIXED_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_MAP_ANY_MIXED_COLLECT map/any_mixed/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[1, 2, 3]\")"  # M_MAP_ANY_MIXED_COLLECT map/any_mixed/collect #9566
    end
    let result = matrix_cell_M_MAP_ANY_MIXED_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_ANY_MIXED_SUM map/any_mixed/sum #9566,#9399
        @test repr(result) == "6"  # M_MAP_ANY_MIXED_SUM map/any_mixed/sum #9566,#9399
    end
    let result = matrix_cell_M_MAP_ANY_MIXED_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_ANY_MIXED_FOLDL map/any_mixed/foldl #9566,#9399
        @test repr(result) == "6"  # M_MAP_ANY_MIXED_FOLDL map/any_mixed/foldl #9566,#9399
    end
    let result = matrix_cell_M_MAP_ANY_MIXED_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_ANY_MIXED_FIRST map/any_mixed/first #9566
        @test repr(result) == "1"  # M_MAP_ANY_MIXED_FIRST map/any_mixed/first #9566
    end
    let result = matrix_cell_M_MAP_ANY_MIXED_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_ANY_MIXED_LENGTH map/any_mixed/length #9566
        @test repr(result) == "3"  # M_MAP_ANY_MIXED_LENGTH map/any_mixed/length #9566
    end
    let result = matrix_cell_M_MAP_ANY_MIXED_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_MAP_ANY_MIXED_FORLOOP map/any_mixed/forloop #9566
        @test repr(result) == "6"  # M_MAP_ANY_MIXED_FORLOOP map/any_mixed/forloop #9566
    end
    let result = matrix_cell_M_FILTER_ANY_MIXED_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_FILTER_ANY_MIXED_ITERATOR_SIZE filter/any_mixed/iterator_size #9566
        @test repr(result) == "\"SizeUnknown\""  # M_FILTER_ANY_MIXED_ITERATOR_SIZE filter/any_mixed/iterator_size #9566
    end
    let result = matrix_cell_M_FILTER_ANY_MIXED_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_FILTER_ANY_MIXED_ITERATOR_ELTYPE filter/any_mixed/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_FILTER_ANY_MIXED_ITERATOR_ELTYPE filter/any_mixed/iterator_eltype #9566
    end
    let result = matrix_cell_M_FILTER_ANY_MIXED_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_FILTER_ANY_MIXED_COLLECT filter/any_mixed/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[2, 3]\")"  # M_FILTER_ANY_MIXED_COLLECT filter/any_mixed/collect #9566
    end
    let result = matrix_cell_M_FILTER_ANY_MIXED_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_ANY_MIXED_SUM filter/any_mixed/sum #9566
        @test repr(result) == "5"  # M_FILTER_ANY_MIXED_SUM filter/any_mixed/sum #9566
    end
    let result = matrix_cell_M_FILTER_ANY_MIXED_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_ANY_MIXED_FOLDL filter/any_mixed/foldl #9566
        @test repr(result) == "5"  # M_FILTER_ANY_MIXED_FOLDL filter/any_mixed/foldl #9566
    end
    let result = matrix_cell_M_FILTER_ANY_MIXED_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_ANY_MIXED_FIRST filter/any_mixed/first #9566
        @test repr(result) == "2"  # M_FILTER_ANY_MIXED_FIRST filter/any_mixed/first #9566
    end
    @test_throws MethodError matrix_cell_M_FILTER_ANY_MIXED_LENGTH_9566()  # M_FILTER_ANY_MIXED_LENGTH filter/any_mixed/length #9566
    let result = matrix_cell_M_FILTER_ANY_MIXED_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_FILTER_ANY_MIXED_FORLOOP filter/any_mixed/forloop #9566
        @test repr(result) == "5"  # M_FILTER_ANY_MIXED_FORLOOP filter/any_mixed/forloop #9566
    end
    let result = matrix_cell_M_FLATTEN_ANY_MIXED_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_FLATTEN_ANY_MIXED_ITERATOR_SIZE flatten/any_mixed/iterator_size #9566
        @test repr(result) == "\"SizeUnknown\""  # M_FLATTEN_ANY_MIXED_ITERATOR_SIZE flatten/any_mixed/iterator_size #9566
    end
    let result = matrix_cell_M_FLATTEN_ANY_MIXED_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_FLATTEN_ANY_MIXED_ITERATOR_ELTYPE flatten/any_mixed/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_FLATTEN_ANY_MIXED_ITERATOR_ELTYPE flatten/any_mixed/iterator_eltype #9566
    end
    let result = matrix_cell_M_FLATTEN_ANY_MIXED_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_FLATTEN_ANY_MIXED_COLLECT flatten/any_mixed/collect #9566,#9438
        @test repr(result) == "(\"Vector{Int64}\", \"[2, 3, 3, 4, 4, 5]\")"  # M_FLATTEN_ANY_MIXED_COLLECT flatten/any_mixed/collect #9566,#9438
    end
    let result = matrix_cell_M_FLATTEN_ANY_MIXED_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_ANY_MIXED_SUM flatten/any_mixed/sum #9566
        @test repr(result) == "21"  # M_FLATTEN_ANY_MIXED_SUM flatten/any_mixed/sum #9566
    end
    let result = matrix_cell_M_FLATTEN_ANY_MIXED_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_ANY_MIXED_FOLDL flatten/any_mixed/foldl #9566
        @test repr(result) == "21"  # M_FLATTEN_ANY_MIXED_FOLDL flatten/any_mixed/foldl #9566
    end
    let result = matrix_cell_M_FLATTEN_ANY_MIXED_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_ANY_MIXED_FIRST flatten/any_mixed/first #9566
        @test repr(result) == "2"  # M_FLATTEN_ANY_MIXED_FIRST flatten/any_mixed/first #9566
    end
    @test_throws ArgumentError matrix_cell_M_FLATTEN_ANY_MIXED_LENGTH_9566()  # M_FLATTEN_ANY_MIXED_LENGTH flatten/any_mixed/length #9566
    let result = matrix_cell_M_FLATTEN_ANY_MIXED_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_FLATTEN_ANY_MIXED_FORLOOP flatten/any_mixed/forloop #9566
        @test repr(result) == "21"  # M_FLATTEN_ANY_MIXED_FORLOOP flatten/any_mixed/forloop #9566
    end
    let result = matrix_cell_M_PRODUCT_ANY_MIXED_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_PRODUCT_ANY_MIXED_ITERATOR_SIZE product/any_mixed/iterator_size #9566
        @test repr(result) == "\"HasShape{2}\""  # M_PRODUCT_ANY_MIXED_ITERATOR_SIZE product/any_mixed/iterator_size #9566
    end
    let result = matrix_cell_M_PRODUCT_ANY_MIXED_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_PRODUCT_ANY_MIXED_ITERATOR_ELTYPE product/any_mixed/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_PRODUCT_ANY_MIXED_ITERATOR_ELTYPE product/any_mixed/iterator_eltype #9566
    end
    let result = matrix_cell_M_PRODUCT_ANY_MIXED_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_PRODUCT_ANY_MIXED_COLLECT product/any_mixed/collect #9566
        @test repr(result) == "(\"Matrix{Int64}\", \"[2 3; 3 4; 4 5]\")"  # M_PRODUCT_ANY_MIXED_COLLECT product/any_mixed/collect #9566
    end
    let result = matrix_cell_M_PRODUCT_ANY_MIXED_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_ANY_MIXED_SUM product/any_mixed/sum #9566
        @test repr(result) == "21"  # M_PRODUCT_ANY_MIXED_SUM product/any_mixed/sum #9566
    end
    let result = matrix_cell_M_PRODUCT_ANY_MIXED_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_ANY_MIXED_FOLDL product/any_mixed/foldl #9566
        @test repr(result) == "21"  # M_PRODUCT_ANY_MIXED_FOLDL product/any_mixed/foldl #9566
    end
    let result = matrix_cell_M_PRODUCT_ANY_MIXED_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_ANY_MIXED_FIRST product/any_mixed/first #9566
        @test repr(result) == "2"  # M_PRODUCT_ANY_MIXED_FIRST product/any_mixed/first #9566
    end
    let result = matrix_cell_M_PRODUCT_ANY_MIXED_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_ANY_MIXED_LENGTH product/any_mixed/length #9566
        @test repr(result) == "6"  # M_PRODUCT_ANY_MIXED_LENGTH product/any_mixed/length #9566
    end
    let result = matrix_cell_M_PRODUCT_ANY_MIXED_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_PRODUCT_ANY_MIXED_FORLOOP product/any_mixed/forloop #9566
        @test repr(result) == "21"  # M_PRODUCT_ANY_MIXED_FORLOOP product/any_mixed/forloop #9566
    end
    let result = matrix_cell_M_ZIP_ANY_MIXED_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_ZIP_ANY_MIXED_ITERATOR_SIZE zip/any_mixed/iterator_size #9566
        @test repr(result) == "\"HasShape{1}\""  # M_ZIP_ANY_MIXED_ITERATOR_SIZE zip/any_mixed/iterator_size #9566
    end
    let result = matrix_cell_M_ZIP_ANY_MIXED_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_ZIP_ANY_MIXED_ITERATOR_ELTYPE zip/any_mixed/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_ZIP_ANY_MIXED_ITERATOR_ELTYPE zip/any_mixed/iterator_eltype #9566
    end
    let result = matrix_cell_M_ZIP_ANY_MIXED_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_ZIP_ANY_MIXED_COLLECT zip/any_mixed/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[11, 13, 15]\")"  # M_ZIP_ANY_MIXED_COLLECT zip/any_mixed/collect #9566
    end
    let result = matrix_cell_M_ZIP_ANY_MIXED_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_ANY_MIXED_SUM zip/any_mixed/sum #9566
        @test repr(result) == "39"  # M_ZIP_ANY_MIXED_SUM zip/any_mixed/sum #9566
    end
    let result = matrix_cell_M_ZIP_ANY_MIXED_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_ANY_MIXED_FOLDL zip/any_mixed/foldl #9566
        @test repr(result) == "39"  # M_ZIP_ANY_MIXED_FOLDL zip/any_mixed/foldl #9566
    end
    let result = matrix_cell_M_ZIP_ANY_MIXED_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_ANY_MIXED_FIRST zip/any_mixed/first #9566
        @test repr(result) == "11"  # M_ZIP_ANY_MIXED_FIRST zip/any_mixed/first #9566
    end
    let result = matrix_cell_M_ZIP_ANY_MIXED_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_ANY_MIXED_LENGTH zip/any_mixed/length #9566
        @test repr(result) == "3"  # M_ZIP_ANY_MIXED_LENGTH zip/any_mixed/length #9566
    end
    let result = matrix_cell_M_ZIP_ANY_MIXED_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_ZIP_ANY_MIXED_FORLOOP zip/any_mixed/forloop #9566
        @test repr(result) == "39"  # M_ZIP_ANY_MIXED_FORLOOP zip/any_mixed/forloop #9566
    end
    let result = matrix_cell_M_ENUMERATE_ANY_MIXED_ITERATOR_SIZE_9566()
        @test string(typeof(result)) == "String"  # M_ENUMERATE_ANY_MIXED_ITERATOR_SIZE enumerate/any_mixed/iterator_size #9566
        @test repr(result) == "\"HasShape{1}\""  # M_ENUMERATE_ANY_MIXED_ITERATOR_SIZE enumerate/any_mixed/iterator_size #9566
    end
    let result = matrix_cell_M_ENUMERATE_ANY_MIXED_ITERATOR_ELTYPE_9566()
        @test string(typeof(result)) == "String"  # M_ENUMERATE_ANY_MIXED_ITERATOR_ELTYPE enumerate/any_mixed/iterator_eltype #9566
        @test repr(result) == "\"EltypeUnknown\""  # M_ENUMERATE_ANY_MIXED_ITERATOR_ELTYPE enumerate/any_mixed/iterator_eltype #9566
    end
    let result = matrix_cell_M_ENUMERATE_ANY_MIXED_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # M_ENUMERATE_ANY_MIXED_COLLECT enumerate/any_mixed/collect #9566
        @test repr(result) == "(\"Vector{Int64}\", \"[2, 4, 6]\")"  # M_ENUMERATE_ANY_MIXED_COLLECT enumerate/any_mixed/collect #9566
    end
    let result = matrix_cell_M_ENUMERATE_ANY_MIXED_SUM_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_ANY_MIXED_SUM enumerate/any_mixed/sum #9566
        @test repr(result) == "12"  # M_ENUMERATE_ANY_MIXED_SUM enumerate/any_mixed/sum #9566
    end
    let result = matrix_cell_M_ENUMERATE_ANY_MIXED_FOLDL_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_ANY_MIXED_FOLDL enumerate/any_mixed/foldl #9566
        @test repr(result) == "12"  # M_ENUMERATE_ANY_MIXED_FOLDL enumerate/any_mixed/foldl #9566
    end
    let result = matrix_cell_M_ENUMERATE_ANY_MIXED_FIRST_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_ANY_MIXED_FIRST enumerate/any_mixed/first #9566
        @test repr(result) == "2"  # M_ENUMERATE_ANY_MIXED_FIRST enumerate/any_mixed/first #9566
    end
    let result = matrix_cell_M_ENUMERATE_ANY_MIXED_LENGTH_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_ANY_MIXED_LENGTH enumerate/any_mixed/length #9566
        @test repr(result) == "3"  # M_ENUMERATE_ANY_MIXED_LENGTH enumerate/any_mixed/length #9566
    end
    let result = matrix_cell_M_ENUMERATE_ANY_MIXED_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # M_ENUMERATE_ANY_MIXED_FORLOOP enumerate/any_mixed/forloop #9566
        @test repr(result) == "12"  # M_ENUMERATE_ANY_MIXED_FORLOOP enumerate/any_mixed/forloop #9566
    end
end

@testset "generator trait matrix - open_bug (Issue #9566)" begin
    let result = matrix_cell_BUG_9403_DYNAMIC_FORLOOP_9566()
        @test string(typeof(result)) == "Int64"  # BUG_9403_DYNAMIC_FORLOOP iterate_only/custom_iterate_only/forloop #9403,#9566
        @test repr(result) == "15"  # BUG_9403_DYNAMIC_FORLOOP iterate_only/custom_iterate_only/forloop #9403,#9566
    end
    let result = matrix_cell_BUG_9405_NESTED_FILTERED_COLLECT_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # BUG_9405_NESTED_FILTERED_COLLECT nested_filtered/range/collect #9405,#9566
        @test repr(result) == "(\"Vector{Int64}\", \"[3, 4, 5]\")"  # BUG_9405_NESTED_FILTERED_COLLECT nested_filtered/range/collect #9405,#9566
    end
    let result = matrix_cell_BUG_9405_NESTED_FILTERED_MAP_9566()
        @test string(typeof(result)) == "Tuple{String, String}"  # BUG_9405_NESTED_FILTERED_MAP nested_filtered/range/map #9405,#9566
        @test repr(result) == "(\"Vector{Int64}\", \"[4, 5, 6]\")"  # BUG_9405_NESTED_FILTERED_MAP nested_filtered/range/map #9405,#9566
    end
    let result = matrix_cell_BUG_9405_NESTED_FILTERED_SUM_9566()
        @test string(typeof(result)) == "Int64"  # BUG_9405_NESTED_FILTERED_SUM nested_filtered/range/sum #9405,#9566
        @test repr(result) == "35"  # BUG_9405_NESTED_FILTERED_SUM nested_filtered/range/sum #9405,#9566
    end
end

true
