# Generated by scripts/gen_numeric_matrix_fixture.jl for Issue #8696.
# The full upstream oracle matrix lives in numeric_matrix_reduced_8696.tsv.

using Test

const NUMERIC_MATRIX_REDUCED_8696_ROWS = 5202
const NUMERIC_MATRIX_REDUCED_8696_SHA256 = "4f2829982202acd40c16cb6133aaf6bf71704ae23f2d0ba19147345baf439b95"

@testset "numeric matrix reduced oracle metadata (Issue #8696)" begin
    @test NUMERIC_MATRIX_REDUCED_8696_ROWS == 5202
    @test NUMERIC_MATRIX_REDUCED_8696_SHA256 == "4f2829982202acd40c16cb6133aaf6bf71704ae23f2d0ba19147345baf439b95"
end

true
