//! Validate the committed lezer-julia oracle snapshots (Issue #11049, M0/M1).
//!
//! The snapshots in `tests/oracle_snapshots/` are generated by
//! `scripts/gen_lezer_oracle_snapshots.sh` from the lezer-julia test corpus
//! and committed so these checks run without Node.js. They pin the Canonical
//! CST JSON contract (`subset_julia_vm_parser_common/schemas/
//! canonical-cst.schema.json`; spec archived in Issue #11225): every snapshot must deserialize into
//! `OracleCase`, and every tree must satisfy the span invariants of spec
//! §10.4 (byte spans in bounds, on char boundaries, children ordered and
//! contained, leaf value text matching the source slice).

use std::fs;
use std::path::PathBuf;

use subset_julia_vm_parser_common::{NodeKind, OracleCase, CANONICAL_CST_VERSION};

fn snapshot_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/oracle_snapshots")
}

fn load_all() -> Vec<(String, Vec<OracleCase>)> {
    let mut out = Vec::new();
    let mut entries: Vec<_> = fs::read_dir(snapshot_dir())
        .expect("tests/oracle_snapshots/ missing — run scripts/gen_lezer_oracle_snapshots.sh")
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().is_some_and(|e| e == "json"))
        .collect();
    entries.sort();
    for path in entries {
        let json = fs::read_to_string(&path).unwrap();
        let cases: Vec<OracleCase> = serde_json::from_str(&json)
            .unwrap_or_else(|e| panic!("{}: failed to deserialize: {e}", path.display()));
        out.push((
            path.file_name().unwrap().to_string_lossy().into_owned(),
            cases,
        ));
    }
    out
}

#[test]
fn oracle_snapshots_present_and_nonempty() {
    let all = load_all();
    assert!(
        all.len() >= 8,
        "expected snapshots for the 8 lezer-julia corpus files, found {}",
        all.len()
    );
    let total: usize = all.iter().map(|(_, cases)| cases.len()).sum();
    assert!(total >= 100, "expected >= 100 oracle cases, found {total}");
    for (file, cases) in &all {
        assert!(!cases.is_empty(), "{file}: empty snapshot");
    }
}

#[test]
fn oracle_snapshot_documents_are_well_formed() {
    for (file, cases) in load_all() {
        for case in cases {
            let ctx = format!("{file} :: {}", case.name);
            let doc = &case.document;
            assert_eq!(doc.version, CANONICAL_CST_VERSION, "{ctx}: version");
            assert_eq!(doc.root.kind, NodeKind::SourceFile, "{ctx}: root kind");
            assert_eq!(doc.root.span.start, 0, "{ctx}: root span start");
            assert_eq!(
                doc.root.span.end as usize,
                case.source.len(),
                "{ctx}: root span must cover the full source; end {} vs byte length {}",
                doc.root.span.end,
                case.source.len()
            );
            if let Err(d) = doc.root.validate_spans(&case.source) {
                panic!(
                    "{ctx}: at {}: {}\n{}",
                    d.path,
                    d.detail,
                    doc.root.to_pretty()
                );
            }
            for (i, diag) in doc.diagnostics.iter().enumerate() {
                assert!(
                    diag.span.start <= diag.span.end && diag.span.end as usize <= case.source.len(),
                    "{ctx}: diagnostic[{i}] span {:?} out of bounds",
                    diag.span
                );
            }
        }
    }
}

/// The oracle corpus must exercise the canonical NodeKind catalog broadly —
/// a canary against the normalizer silently emitting unmapped lezer names
/// for kinds the spec canonicalizes (e.g. `Program` instead of `SourceFile`).
#[test]
fn oracle_snapshots_use_canonical_kinds() {
    // lezer names that the normalizer must never let through.
    const FORBIDDEN: &[&str] = &[
        "Program",
        "⚠",
        "BoolLiteral",
        "CharLiteral",
        "StringLiteral",
        "InterpExpression",
        "ArrowFunctionExpression",
        "MacrocallExpression",
        "BeginStatement",
        "LetStatement",
        "Generator",
        "GenFor",
        "GenFilter",
        "AssignmentOp",
        "PlusOp",
        "TimesOp",
        "ComparisonOp",
        "UpdateOp",
    ];
    fn walk(node: &subset_julia_vm_parser_common::CstNode, ctx: &str) {
        let name = node.kind.as_str();
        assert!(
            !FORBIDDEN.contains(&name),
            "{ctx}: unmapped lezer node kind `{name}` leaked into a snapshot"
        );
        for child in &node.children {
            walk(child, ctx);
        }
    }
    let mut seen_canonical = std::collections::BTreeSet::new();
    for (file, cases) in load_all() {
        for case in cases {
            let ctx = format!("{file} :: {}", case.name);
            walk(&case.document.root, &ctx);
            fn collect(
                node: &subset_julia_vm_parser_common::CstNode,
                seen: &mut std::collections::BTreeSet<String>,
            ) {
                if !matches!(node.kind, NodeKind::Other(_)) {
                    seen.insert(node.kind.as_str().to_string());
                }
                for child in &node.children {
                    collect(child, seen);
                }
            }
            collect(&case.document.root, &mut seen_canonical);
        }
    }
    // The lezer corpus covers a broad slice of the catalog; keep a floor so
    // a normalizer regression (everything becoming Other) is caught.
    assert!(
        seen_canonical.len() >= 25,
        "expected >= 25 distinct canonical kinds across the corpus, found {}: {:?}",
        seen_canonical.len(),
        seen_canonical
    );
}
