# Single-axis 3-D rotations RotX / RotY / RotZ (adapted from
# extern/Rotations.jl/src/euler_types.jl, lines 45-198).
#
# Only the structs + constructors live here; per-type behaviour (`getindex`,
# `Tuple`, `*`, `inv`, ...) is handled by the single `::Rotation` methods in
# core_types.jl (one method per generic function, branching on the concrete type
# with `isa`) to avoid the sibling-method mis-dispatch of #7960.
#
# The upstream multi-axis Euler variants (RotXY ... RotZYX, generated by `@eval`
# loops) are out of MVP scope; see docs/vm/ROTATIONS.md.

"""
    RotX{T} <: Rotation{3,T}

A 3×3 rotation by `theta` about the X axis.
"""
struct RotX{T} <: Rotation{3,T}
    theta::T
    RotX{T}(theta::Number) where {T} = new{T}(T(theta))
end
@inline RotX(theta::Number) = RotX{rot_eltype(typeof(theta))}(theta)

"""
    RotY{T} <: Rotation{3,T}

A 3×3 rotation by `theta` about the Y axis.
"""
struct RotY{T} <: Rotation{3,T}
    theta::T
    RotY{T}(theta::Number) where {T} = new{T}(T(theta))
end
@inline RotY(theta::Number) = RotY{rot_eltype(typeof(theta))}(theta)

"""
    RotZ{T} <: Rotation{3,T}

A 3×3 rotation by `theta` about the Z axis.
"""
struct RotZ{T} <: Rotation{3,T}
    theta::T
    RotZ{T}(theta::Number) where {T} = new{T}(T(theta))
end
@inline RotZ(theta::Number) = RotZ{rot_eltype(typeof(theta))}(theta)
