//! Peephole optimizer for bytecode
//!
//! This module performs peephole optimizations on generated bytecode by replacing
//! common instruction sequences with fused instructions for better performance.

use crate::builtins::BuiltinId;
use crate::compile::effects::instr::instruction_effects;
use crate::vm::instr::{CallDirectSlots, CallSpecializeSlots};
use crate::vm::Instr;
use std::collections::HashSet;

/// Optimize bytecode by fusing common instruction patterns
/// Returns (optimized_code, old_to_new_index_mapping)
/// The mapping allows updating function boundaries and entry points after optimization
/// The mapping vector has length code.len() + 1 to handle end-of-code boundaries
pub fn optimize(code: Vec<Instr>) -> (Vec<Instr>, Vec<usize>) {
    let jump_targets = collect_jump_targets(&code);
    // Build old->new instruction index mapping
    // Add one extra entry for the "end" position (one past last instruction)
    let mut old_to_new: Vec<usize> = vec![0; code.len() + 1];
    let mut new_index = 0;
    let mut i = 0;

    while i < code.len() {
        old_to_new[i] = new_index;
        let fused = try_fuse_at_guarded(&code, i, &jump_targets);
        match fused {
            Some((_, consumed)) => {
                // Mark all consumed instructions as mapping to the same new index
                for j in 0..consumed {
                    if i + j < code.len() {
                        old_to_new[i + j] = new_index;
                    }
                }
                new_index += 1;
                i += consumed;
            }
            None => {
                old_to_new[i] = new_index;
                new_index += 1;
                i += 1;
            }
        }
    }

    // Map the "end" position (one past last instruction)
    old_to_new[code.len()] = new_index;

    // Now optimize with the mapping
    let mut optimized = Vec::with_capacity(code.len());
    i = 0;

    while i < code.len() {
        let fused = try_fuse_at_guarded(&code, i, &jump_targets);
        match fused {
            Some((fused_instr, consumed)) => {
                // Update jump target if this is a jump instruction
                let updated_instr = update_jump_target(fused_instr, &old_to_new);
                optimized.push(updated_instr);
                i += consumed;
            }
            None => {
                // Update jump target if this is a jump instruction
                let updated_instr = update_jump_target(code[i].clone(), &old_to_new);
                optimized.push(updated_instr);
                i += 1;
            }
        }
    }

    rewrite_adjacent_duplicate_loads(&mut optimized, &HashSet::new());

    (optimized, old_to_new)
}

/// Optimize only unprotected ranges of bytecode, leaving protected ranges untouched.
/// Returns (optimized_code, old_to_new_index_mapping)
/// `protected_ranges` are ranges that should NOT be optimized (e.g., cached code).
/// Each range is (start, end) where end is exclusive.
#[cfg(test)]
pub fn optimize_with_protected_ranges(
    code: Vec<Instr>,
    protected_ranges: &[(usize, usize)],
) -> (Vec<Instr>, Vec<usize>) {
    // If no protected ranges, use standard optimization
    if protected_ranges.is_empty() {
        return optimize(code);
    }
    if let Some(prefix_len) = protected_prefix_only_len(protected_ranges) {
        return optimize_with_protected_prefix(code, prefix_len);
    }

    let jump_targets = collect_jump_targets(&code);

    // Check if index is in a protected range
    let is_protected = |idx: usize| -> bool {
        protected_ranges
            .iter()
            .any(|(start, end)| idx >= *start && idx < *end)
    };

    // Build old->new instruction index mapping
    let mut old_to_new: Vec<usize> = vec![0; code.len() + 1];
    let mut optimized = Vec::with_capacity(code.len());
    let mut new_index = 0;
    let mut i = 0;

    while i < code.len() {
        old_to_new[i] = new_index;

        if is_protected(i) {
            // Protected range: copy instruction as-is
            optimized.push(code[i].clone());
            new_index += 1;
            i += 1;
        } else {
            // Unprotected range: try to fuse
            let fused = try_fuse_at_guarded(&code, i, &jump_targets);
            match fused {
                Some((fused_instr, consumed)) => {
                    // Only fuse if all consumed instructions are also unprotected
                    let all_unprotected = (0..consumed).all(|j| !is_protected(i + j));
                    if all_unprotected {
                        for j in 0..consumed {
                            old_to_new[i + j] = new_index;
                        }
                        optimized.push(fused_instr);
                        new_index += 1;
                        i += consumed;
                    } else {
                        // Some instructions in fusion range are protected, copy as-is
                        optimized.push(code[i].clone());
                        new_index += 1;
                        i += 1;
                    }
                }
                None => {
                    optimized.push(code[i].clone());
                    new_index += 1;
                    i += 1;
                }
            }
        }
    }

    // Map the "end" position
    old_to_new[code.len()] = new_index;

    // Update all jump targets using the mapping
    for instr in &mut optimized {
        *instr = update_jump_target(instr.clone(), &old_to_new);
    }
    let protected_new_indices = collect_protected_new_indices(protected_ranges, &old_to_new);
    rewrite_adjacent_duplicate_loads(&mut optimized, &protected_new_indices);

    (optimized, old_to_new)
}

#[cfg(test)]
fn protected_prefix_only_len(protected_ranges: &[(usize, usize)]) -> Option<usize> {
    let mut ranges = protected_ranges
        .iter()
        .copied()
        .filter(|(start, end)| start < end)
        .collect::<Vec<_>>();
    ranges.sort_unstable();

    let mut prefix_end = 0;
    for (start, end) in &ranges {
        if *start > prefix_end {
            break;
        }
        prefix_end = prefix_end.max(*end);
    }
    if prefix_end == 0 {
        return None;
    }
    ranges
        .iter()
        .all(|(start, end)| *start < prefix_end && *end <= prefix_end)
        .then_some(prefix_end)
}

#[cfg(test)]
fn optimize_with_protected_prefix(
    code: Vec<Instr>,
    protected_prefix_len: usize,
) -> (Vec<Instr>, Vec<usize>) {
    let protected_prefix_len = protected_prefix_len.min(code.len());
    let jump_targets = collect_jump_targets(&code[protected_prefix_len..]);

    let mut old_to_new: Vec<usize> = vec![0; code.len() + 1];
    for (idx, slot) in old_to_new.iter_mut().enumerate().take(protected_prefix_len) {
        *slot = idx;
    }

    let mut new_index = protected_prefix_len;
    let mut i = protected_prefix_len;
    while i < code.len() {
        old_to_new[i] = new_index;
        let fused = try_fuse_at_guarded(&code, i, &jump_targets);
        match fused {
            Some((_, consumed)) => {
                for j in 0..consumed {
                    if i + j < code.len() {
                        old_to_new[i + j] = new_index;
                    }
                }
                new_index += 1;
                i += consumed;
            }
            None => {
                new_index += 1;
                i += 1;
            }
        }
    }
    old_to_new[code.len()] = new_index;

    let mut optimized = Vec::with_capacity(code.len());
    optimized.extend_from_slice(&code[..protected_prefix_len]);

    i = protected_prefix_len;
    while i < code.len() {
        let fused = try_fuse_at_guarded(&code, i, &jump_targets);
        match fused {
            Some((fused_instr, consumed)) => {
                optimized.push(update_jump_target(fused_instr, &old_to_new));
                i += consumed;
            }
            None => {
                optimized.push(update_jump_target(code[i].clone(), &old_to_new));
                i += 1;
            }
        }
    }

    rewrite_adjacent_duplicate_loads(&mut optimized[protected_prefix_len..], &HashSet::new());

    (optimized, old_to_new)
}

#[cfg(test)]
fn collect_protected_new_indices(
    protected_ranges: &[(usize, usize)],
    old_to_new: &[usize],
) -> HashSet<usize> {
    let mut protected = HashSet::new();
    for (start, end) in protected_ranges {
        for old_index in *start..*end {
            if let Some(new_index) = old_to_new.get(old_index) {
                protected.insert(*new_index);
            }
        }
    }
    protected
}

fn rewrite_adjacent_duplicate_loads(code: &mut [Instr], protected_indices: &HashSet<usize>) {
    for i in 1..code.len() {
        if protected_indices.contains(&(i - 1)) || protected_indices.contains(&i) {
            continue;
        }
        if let Some(dup) = duplicate_for_redundant_load_pair(&code[i - 1], &code[i]) {
            code[i] = dup;
        }
    }
}

fn duplicate_for_redundant_load_pair(first: &Instr, second: &Instr) -> Option<Instr> {
    if !instruction_effects(first).effect_free.is_always_true() {
        return None;
    }

    match (first, second) {
        (Instr::LoadI64(a), Instr::LoadI64(b)) if a == b => Some(Instr::DupI64),
        (Instr::LoadSlotI64(a), Instr::LoadSlotI64(b)) if a == b => Some(Instr::DupI64),
        (Instr::LoadF64(a), Instr::LoadF64(b)) if a == b => Some(Instr::DupF64),
        (Instr::LoadSlotF64(a), Instr::LoadSlotF64(b)) if a == b => Some(Instr::DupF64),
        _ => None,
    }
}

fn collect_jump_targets(code: &[Instr]) -> HashSet<usize> {
    code.iter()
        .filter_map(|instr| match instr {
            Instr::Jump(target)
            | Instr::JumpIfZero(target)
            | Instr::JumpIfNeI64(target)
            | Instr::JumpIfEqI64(target)
            | Instr::JumpIfLtI64(target)
            | Instr::JumpIfGtI64(target)
            | Instr::JumpIfGtI64Slots(_, _, target)
            | Instr::AddConstI64SlotAndJumpIfLe(_, _, _, target)
            | Instr::JumpIfLeI64(target)
            | Instr::JumpIfGeI64(target)
            | Instr::JumpIfEqF64(target)
            | Instr::JumpIfNeF64(target)
            | Instr::JumpIfNotLtF64(target)
            | Instr::JumpIfNotGtF64(target)
            | Instr::JumpIfNotLeF64(target)
            | Instr::JumpIfNotGeF64(target) => Some(*target),
            _ => None,
        })
        .collect()
}

fn try_fuse_at_guarded(
    code: &[Instr],
    i: usize,
    jump_targets: &HashSet<usize>,
) -> Option<(Instr, usize)> {
    let fused = try_fuse_at(code, i)?;
    let (_, consumed) = fused;
    if (1..consumed).any(|offset| jump_targets.contains(&(i + offset))) {
        return None;
    }
    Some(fused)
}

/// Update jump target in an instruction based on the old->new mapping
fn update_jump_target(instr: Instr, old_to_new: &[usize]) -> Instr {
    match instr {
        Instr::Jump(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr // Keep original if out of bounds (shouldn't happen)
            };
            Instr::Jump(new_addr)
        }
        Instr::JumpIfZero(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfZero(new_addr)
        }
        Instr::JumpIfNeI64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfNeI64(new_addr)
        }
        Instr::JumpIfEqI64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfEqI64(new_addr)
        }
        Instr::JumpIfLtI64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfLtI64(new_addr)
        }
        Instr::JumpIfGtI64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfGtI64(new_addr)
        }
        Instr::JumpIfGtI64Slots(lhs_slot, rhs_slot, old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfGtI64Slots(lhs_slot, rhs_slot, new_addr)
        }
        Instr::AddConstI64SlotAndJumpIfLe(slot, delta, stop_slot, old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::AddConstI64SlotAndJumpIfLe(slot, delta, stop_slot, new_addr)
        }
        Instr::JumpIfLeI64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfLeI64(new_addr)
        }
        Instr::JumpIfGeI64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfGeI64(new_addr)
        }
        Instr::JumpIfEqF64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfEqF64(new_addr)
        }
        Instr::JumpIfNeF64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfNeF64(new_addr)
        }
        Instr::JumpIfNotLtF64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfNotLtF64(new_addr)
        }
        Instr::JumpIfNotGtF64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfNotGtF64(new_addr)
        }
        Instr::JumpIfNotLeF64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfNotLeF64(new_addr)
        }
        Instr::JumpIfNotGeF64(old_addr) => {
            let new_addr = if old_addr < old_to_new.len() {
                old_to_new[old_addr]
            } else {
                old_addr
            };
            Instr::JumpIfNotGeF64(new_addr)
        }
        Instr::PushHandler(catch_ip, finally_ip) => {
            let map_ip = |ip: Option<usize>| {
                ip.map(|old_addr| {
                    if old_addr < old_to_new.len() {
                        old_to_new[old_addr]
                    } else {
                        old_addr
                    }
                })
            };
            Instr::PushHandler(map_ip(catch_ip), map_ip(finally_ip))
        }
        // Add other jump instructions as needed
        _ => instr, // No change for non-jump instructions
    }
}

/// Try to fuse instructions starting at index i
/// Returns Some((fused_instruction, num_instructions_consumed)) if successful
fn try_fuse_at(code: &[Instr], i: usize) -> Option<(Instr, usize)> {
    // Need at least 2 instructions for any fusion
    if i + 1 >= code.len() {
        return None;
    }

    if let Some(fused) = try_fuse_slot_arg_call(code, i) {
        return Some(fused);
    }

    let instr1 = &code[i];
    let instr2 = &code[i + 1];

    if let (Instr::LoadSlotI64(slot), Instr::CallBuiltin(BuiltinId::Float64, 1)) = (instr1, instr2)
    {
        return Some((Instr::LoadSlotI64ToF64(*slot), 2));
    }

    if i + 2 < code.len() {
        if let (
            Instr::LoadSlotI64(lhs_slot),
            Instr::LoadSlotI64(rhs_slot),
            Instr::JumpIfGtI64(target),
        ) = (instr1, instr2, &code[i + 2])
        {
            if gt_slot_branch_fusion_is_profitable(code, i + 3, *target, *lhs_slot) {
                return Some((Instr::JumpIfGtI64Slots(*lhs_slot, *rhs_slot, *target), 3));
            }
        }
    }

    if let Some(fused) = try_fuse_counted_loop_backedge(code, i) {
        return Some(fused);
    }

    // Pattern 0a: constant slot increment/decrement produced by const-step loops.
    if let Instr::PushI64(delta) = instr1 {
        match instr2 {
            Instr::IncVarI64Slot(slot) => {
                return Some((Instr::AddConstI64Slot(*slot, *delta), 2));
            }
            Instr::DecVarI64Slot(slot) => {
                return Some((Instr::AddConstI64Slot(*slot, delta.wrapping_neg()), 2));
            }
            _ => {}
        }
    }

    // Pattern 0 (3-instruction): Constant folding (Issue #3367)
    // PushI64(a) + PushI64(b) + ArithOp → PushI64(result)
    if let Instr::PushI64(a) = instr1 {
        if let Instr::PushI64(b) = instr2 {
            if i + 2 < code.len() {
                let instr3 = &code[i + 2];
                match instr3 {
                    Instr::AddI64 => return Some((Instr::PushI64(a.wrapping_add(*b)), 3)),
                    Instr::SubI64 => return Some((Instr::PushI64(a.wrapping_sub(*b)), 3)),
                    Instr::MulI64 => return Some((Instr::PushI64(a.wrapping_mul(*b)), 3)),
                    Instr::ModI64 if *b != 0 => {
                        return Some((Instr::PushI64(a.wrapping_rem(*b)), 3))
                    }
                    _ => {}
                }
            }
        }
    }

    // PushF64(a) + PushF64(b) + ArithOp → PushF64(result)
    if let Instr::PushF64(a) = instr1 {
        if let Instr::PushF64(b) = instr2 {
            if i + 2 < code.len() {
                let instr3 = &code[i + 2];
                match instr3 {
                    Instr::AddF64 => return Some((Instr::PushF64(a + b), 3)),
                    Instr::SubF64 => return Some((Instr::PushF64(a - b), 3)),
                    Instr::MulF64 => return Some((Instr::PushF64(a * b), 3)),
                    Instr::DivF64 => return Some((Instr::PushF64(a / b), 3)),
                    _ => {}
                }
            }
        }
    }

    // Pattern 1 (3-instruction): LoadI64(x) + AddI64 + StoreI64(x) → IncVarI64(x)
    // Check this FIRST before the 2-instruction pattern, since it's more specific
    if let Instr::LoadI64(name) = instr1 {
        if i + 2 < code.len() {
            let instr3 = &code[i + 2];
            if matches!(instr2, Instr::AddI64) {
                if let Instr::StoreI64(store_name) = instr3 {
                    if store_name == name {
                        // cnt = cnt + 1  →  IncVarI64(cnt)
                        return Some((Instr::IncVarI64(name.clone()), 3));
                    }
                }
            }
            if matches!(instr2, Instr::SubI64) {
                if let Instr::StoreI64(store_name) = instr3 {
                    if store_name == name {
                        // cnt = cnt - 1  →  DecVarI64(cnt)
                        return Some((Instr::DecVarI64(name.clone()), 3));
                    }
                }
            }
        }

        // Pattern 2 (2-instruction): LoadI64(x) + {Add,Sub,Mul,Mod}I64 → Load{Op}I64(x)
        // Only if Pattern 1 didn't match
        match instr2 {
            Instr::AddI64 => {
                return Some((Instr::LoadAddI64(name.clone()), 2));
            }
            Instr::SubI64 => {
                return Some((Instr::LoadSubI64(name.clone()), 2));
            }
            Instr::MulI64 => {
                return Some((Instr::LoadMulI64(name.clone()), 2));
            }
            Instr::ModI64 => {
                return Some((Instr::LoadModI64(name.clone()), 2));
            }
            _ => {}
        }
    }

    // Pattern 2b: slotized Int64 load-op/store and load-op fusion (Issue #5091)
    // Slot assignment removes string-keyed local lookup from hot loops; once slots
    // are available, keep the same superinstruction coverage for slot operands.
    if let Instr::LoadSlotI64(slot) = instr1 {
        if i + 3 < code.len() {
            let instr3 = &code[i + 2];
            let instr4 = &code[i + 3];
            if let Instr::PushI64(delta) = instr2 {
                if matches!(instr3, Instr::AddI64) {
                    if let Instr::StoreSlotI64(store_slot) = instr4 {
                        if store_slot == slot {
                            return Some((Instr::AddConstI64Slot(*slot, *delta), 4));
                        }
                    }
                }
                if matches!(instr3, Instr::SubI64) {
                    if let Instr::StoreSlotI64(store_slot) = instr4 {
                        if store_slot == slot {
                            return Some((Instr::AddConstI64Slot(*slot, delta.wrapping_neg()), 4));
                        }
                    }
                }
            }
        }

        if i + 2 < code.len() {
            let instr3 = &code[i + 2];
            if matches!(instr2, Instr::AddI64) {
                if let Instr::StoreSlotI64(store_slot) = instr3 {
                    if store_slot == slot {
                        return Some((Instr::IncVarI64Slot(*slot), 3));
                    }
                }
            }
            if matches!(instr2, Instr::SubI64) {
                if let Instr::StoreSlotI64(store_slot) = instr3 {
                    if store_slot == slot {
                        return Some((Instr::DecVarI64Slot(*slot), 3));
                    }
                }
            }
        }

        match instr2 {
            Instr::AddI64 => return Some((Instr::LoadAddI64Slot(*slot), 2)),
            Instr::SubI64 => return Some((Instr::LoadSubI64Slot(*slot), 2)),
            Instr::MulI64 => return Some((Instr::LoadMulI64Slot(*slot), 2)),
            Instr::ModI64 => return Some((Instr::LoadModI64Slot(*slot), 2)),
            _ => {}
        }
    }

    // Pattern 2c: slotized Float64 load-op and square fusion.
    if let Instr::LoadSlotF64(slot) = instr1 {
        if i + 2 < code.len() {
            let instr3 = &code[i + 2];
            if matches!(instr2, Instr::DupF64) && matches!(instr3, Instr::MulF64) {
                return Some((Instr::LoadSquareF64Slot(*slot), 3));
            }
            if matches!(instr3, Instr::MulF64) {
                if let Instr::LoadSlotF64(rhs_slot) = instr2 {
                    if rhs_slot == slot {
                        return Some((Instr::LoadSquareF64Slot(*slot), 3));
                    }
                }
            }
        }

        match instr2 {
            Instr::AddF64 => return Some((Instr::LoadAddF64Slot(*slot), 2)),
            Instr::SubF64 => return Some((Instr::LoadSubF64Slot(*slot), 2)),
            Instr::MulF64 => return Some((Instr::LoadMulF64Slot(*slot), 2)),
            Instr::DivF64 => return Some((Instr::LoadDivF64Slot(*slot), 2)),
            _ => {}
        }
    }

    // Pattern 3: NeI64 + JumpIfZero(addr) → JumpIfNeI64(addr)
    // Note: NeI64 pushes 1 if !=, 0 if ==
    // JumpIfZero jumps if value is 0
    // So: if (a != b) == 0 → if a == b → JumpIfEq
    // We want: if a != b → JumpIfNe
    // Actually, the logic is:
    //   NeI64: push (a != b ? 1 : 0)
    //   JumpIfZero: jump if top == 0
    // Combined: jump if (a != b) == 0 → jump if a == b
    // So NeI64 + JumpIfZero → JumpIfEqI64
    match (instr1, instr2) {
        (Instr::NeI64, Instr::JumpIfZero(addr)) => {
            // Jump if equal (because NeI64 returns 0 when equal)
            return Some((Instr::JumpIfEqI64(*addr), 2));
        }
        (Instr::EqI64, Instr::JumpIfZero(addr)) => {
            // Jump if not equal (because EqI64 returns 0 when not equal)
            return Some((Instr::JumpIfNeI64(*addr), 2));
        }
        (Instr::LtI64, Instr::JumpIfZero(addr)) => {
            // Jump if NOT less than (>= )
            return Some((Instr::JumpIfGeI64(*addr), 2));
        }
        (Instr::GtI64, Instr::JumpIfZero(addr)) => {
            // Jump if NOT greater than (<=)
            return Some((Instr::JumpIfLeI64(*addr), 2));
        }
        (Instr::LeI64, Instr::JumpIfZero(addr)) => {
            // Jump if NOT less or equal (>)
            return Some((Instr::JumpIfGtI64(*addr), 2));
        }
        (Instr::GeI64, Instr::JumpIfZero(addr)) => {
            // Jump if NOT greater or equal (<)
            return Some((Instr::JumpIfLtI64(*addr), 2));
        }
        (Instr::NeF64, Instr::JumpIfZero(addr)) => {
            return Some((Instr::JumpIfEqF64(*addr), 2));
        }
        (Instr::EqF64, Instr::JumpIfZero(addr)) => {
            return Some((Instr::JumpIfNeF64(*addr), 2));
        }
        (Instr::LtF64, Instr::JumpIfZero(addr)) => {
            return Some((Instr::JumpIfNotLtF64(*addr), 2));
        }
        (Instr::GtF64, Instr::JumpIfZero(addr)) => {
            return Some((Instr::JumpIfNotGtF64(*addr), 2));
        }
        (Instr::LeF64, Instr::JumpIfZero(addr)) => {
            return Some((Instr::JumpIfNotLeF64(*addr), 2));
        }
        (Instr::GeF64, Instr::JumpIfZero(addr)) => {
            return Some((Instr::JumpIfNotGeF64(*addr), 2));
        }
        _ => {}
    }

    None
}

fn try_fuse_counted_loop_backedge(code: &[Instr], i: usize) -> Option<(Instr, usize)> {
    let (slot, delta, header, consumed) = counted_loop_tail(code, i)?;
    if header >= i {
        return None;
    }
    let fallthrough_exit = i.checked_add(consumed)?;
    let body_target = header.checked_add(1)?;
    if body_target >= code.len() {
        return None;
    }
    match code.get(header)? {
        Instr::JumpIfGtI64Slots(lhs_slot, stop_slot, exit)
            if *lhs_slot == slot && *exit == fallthrough_exit =>
        {
            Some((
                Instr::AddConstI64SlotAndJumpIfLe(slot, delta, *stop_slot, body_target),
                consumed,
            ))
        }
        Instr::LoadSlotI64(lhs_slot)
            if *lhs_slot == slot
                && matches!(
                    (code.get(header + 1), code.get(header + 2)),
                    (
                        Some(Instr::LoadSlotI64(_)),
                        Some(Instr::JumpIfGtI64(header_exit))
                    ) if *header_exit == fallthrough_exit
                ) =>
        {
            let Some(Instr::LoadSlotI64(stop_slot)) = code.get(header + 1) else {
                return None;
            };
            Some((
                Instr::AddConstI64SlotAndJumpIfLe(slot, delta, *stop_slot, header + 3),
                consumed,
            ))
        }
        _ => None,
    }
}

fn counted_loop_tail(code: &[Instr], i: usize) -> Option<(usize, i64, usize, usize)> {
    match (code.get(i)?, code.get(i + 1)?) {
        (Instr::AddConstI64Slot(slot, delta), Instr::Jump(header)) if *delta > 0 => {
            Some((*slot, *delta, *header, 2))
        }
        (Instr::PushI64(delta), Instr::IncVarI64Slot(slot)) if *delta > 0 => {
            match code.get(i + 2)? {
                Instr::Jump(header) => Some((*slot, *delta, *header, 3)),
                _ => None,
            }
        }
        (Instr::LoadSlotI64(slot), Instr::PushI64(delta)) if *delta > 0 => {
            match (code.get(i + 2)?, code.get(i + 3)?, code.get(i + 4)?) {
                (Instr::AddI64, Instr::StoreSlotI64(store_slot), Instr::Jump(header))
                    if store_slot == slot =>
                {
                    Some((*slot, *delta, *header, 5))
                }
                _ => None,
            }
        }
        _ => None,
    }
}

fn try_fuse_slot_arg_call(code: &[Instr], i: usize) -> Option<(Instr, usize)> {
    let mut slots = Vec::new();
    let mut cursor = i;
    while let Some(Instr::LoadSlotI64(slot)) = code.get(cursor) {
        slots.push(*slot);
        cursor += 1;
    }
    if slots.is_empty() {
        return None;
    }

    let specialize_payload = |spec_func_index| {
        Box::new(CallSpecializeSlots {
            spec_func_index,
            slots: slots.clone(),
        })
    };
    let direct_payload = |func_index| {
        Box::new(CallDirectSlots {
            func_index,
            slots: slots.clone(),
        })
    };

    match code.get(cursor) {
        Some(Instr::CallSpecialize(spec_func_index, arg_count)) if *arg_count == slots.len() => {
            Some((
                Instr::CallSpecializeI64Slots(specialize_payload(*spec_func_index)),
                slots.len() + 1,
            ))
        }
        Some(Instr::CallSpecializeInbounds(spec_func_index, arg_count))
            if *arg_count == slots.len() =>
        {
            Some((
                Instr::CallSpecializeInboundsI64Slots(specialize_payload(*spec_func_index)),
                slots.len() + 1,
            ))
        }
        Some(Instr::CallResolved(func_index, arg_count)) if *arg_count == slots.len() => Some((
            Instr::CallResolvedI64Slots(direct_payload(*func_index)),
            slots.len() + 1,
        )),
        Some(Instr::CallInbounds(func_index, arg_count)) if *arg_count == slots.len() => Some((
            Instr::CallInboundsI64Slots(direct_payload(*func_index)),
            slots.len() + 1,
        )),
        _ => None,
    }
}

fn gt_slot_branch_fusion_is_profitable(
    code: &[Instr],
    body_start: usize,
    target: usize,
    lhs_slot: usize,
) -> bool {
    target > body_start
        && target <= code.len()
        && body_updates_i64_slot(&code[body_start..target], lhs_slot)
}

fn body_updates_i64_slot(body: &[Instr], slot: usize) -> bool {
    body.iter().any(|instr| {
        matches!(
            instr,
            Instr::AddConstI64Slot(updated, _)
                | Instr::IncVarI64Slot(updated)
                | Instr::DecVarI64Slot(updated)
                | Instr::AddConstI64SlotAndJumpIfLe(updated, _, _, _)
                if *updated == slot
        )
    }) || body.windows(2).any(|window| {
        matches!(
            window,
            [Instr::PushI64(_), Instr::IncVarI64Slot(updated) | Instr::DecVarI64Slot(updated)]
                if *updated == slot
        )
    }) || body.windows(3).any(|window| {
        matches!(
            window,
            [
                Instr::LoadSlotI64(load_slot),
                Instr::AddI64 | Instr::SubI64,
                Instr::StoreSlotI64(store_slot)
            ] if *load_slot == slot && *store_slot == slot
        )
    }) || body.windows(4).any(|window| {
        matches!(
            window,
            [
                Instr::LoadSlotI64(load_slot),
                Instr::PushI64(_),
                Instr::AddI64 | Instr::SubI64,
                Instr::StoreSlotI64(store_slot)
            ] if *load_slot == slot && *store_slot == slot
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_load_add_fusion() {
        let code = vec![Instr::LoadI64("a".to_string()), Instr::AddI64];

        let (optimized, mapping) = optimize(code);

        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::LoadAddI64(_)));
        assert_eq!(mapping.len(), 3); // 2 instructions + 1 end position
        assert_eq!(mapping[0], 0); // First instruction maps to 0
        assert_eq!(mapping[1], 0); // Second instruction also maps to 0 (fused)
        assert_eq!(mapping[2], 1); // End position maps to new length
    }

    #[test]
    fn test_inc_var_fusion() {
        let code = vec![
            Instr::LoadI64("cnt".to_string()),
            Instr::AddI64,
            Instr::StoreI64("cnt".to_string()),
        ];

        let (optimized, mapping) = optimize(code);

        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::IncVarI64(_)));
        assert_eq!(mapping.len(), 4); // 3 instructions + 1 end position
        assert_eq!(mapping[0], 0);
        assert_eq!(mapping[1], 0);
        assert_eq!(mapping[2], 0); // All three fused to index 0
        assert_eq!(mapping[3], 1); // End position
    }

    #[test]
    fn test_slot_load_op_fusion_issue_5091() {
        let add = vec![Instr::LoadSlotI64(2), Instr::AddI64];
        let (optimized, mapping) = optimize(add);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::LoadAddI64Slot(2)));
        assert_eq!(mapping, vec![0, 0, 1]);

        let sub = vec![Instr::LoadSlotI64(2), Instr::SubI64];
        let (optimized, _) = optimize(sub);
        assert!(matches!(optimized[0], Instr::LoadSubI64Slot(2)));

        let mul = vec![Instr::LoadSlotI64(2), Instr::MulI64];
        let (optimized, _) = optimize(mul);
        assert!(matches!(optimized[0], Instr::LoadMulI64Slot(2)));

        let modu = vec![Instr::LoadSlotI64(2), Instr::ModI64];
        let (optimized, _) = optimize(modu);
        assert!(matches!(optimized[0], Instr::LoadModI64Slot(2)));
    }

    #[test]
    fn test_slot_inc_dec_fusion_issue_5091() {
        let inc = vec![Instr::LoadSlotI64(3), Instr::AddI64, Instr::StoreSlotI64(3)];
        let (optimized, mapping) = optimize(inc);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::IncVarI64Slot(3)));
        assert_eq!(mapping, vec![0, 0, 0, 1]);

        let dec = vec![Instr::LoadSlotI64(4), Instr::SubI64, Instr::StoreSlotI64(4)];
        let (optimized, _) = optimize(dec);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::DecVarI64Slot(4)));
    }

    #[test]
    fn test_slot_const_increment_fusion() {
        let inc = vec![
            Instr::LoadSlotI64(3),
            Instr::PushI64(1),
            Instr::AddI64,
            Instr::StoreSlotI64(3),
        ];
        let (optimized, mapping) = optimize(inc);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::AddConstI64Slot(3, 1)));
        assert_eq!(mapping, vec![0, 0, 0, 0, 1]);

        let dec = vec![
            Instr::LoadSlotI64(4),
            Instr::PushI64(1),
            Instr::SubI64,
            Instr::StoreSlotI64(4),
        ];
        let (optimized, mapping) = optimize(dec);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::AddConstI64Slot(4, -1)));
        assert_eq!(mapping, vec![0, 0, 0, 0, 1]);
    }

    #[test]
    fn test_slot_const_incvar_fusion_issue_6167() {
        let inc = vec![Instr::PushI64(1), Instr::IncVarI64Slot(3)];
        let (optimized, mapping) = optimize(inc);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::AddConstI64Slot(3, 1)));
        assert_eq!(mapping, vec![0, 0, 1]);

        let dec = vec![Instr::PushI64(2), Instr::DecVarI64Slot(4)];
        let (optimized, mapping) = optimize(dec);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::AddConstI64Slot(4, -2)));
        assert_eq!(mapping, vec![0, 0, 1]);
    }

    #[test]
    fn test_slot_gt_branch_fusion_issue_6167() {
        let code = vec![
            Instr::LoadSlotI64(3),
            Instr::LoadSlotI64(2),
            Instr::JumpIfGtI64(7),
            Instr::CallSpecialize(0, 0),
            Instr::PushI64(0),
            Instr::AddConstI64Slot(3, 1),
            Instr::Jump(0),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);
        assert!(matches!(optimized[0], Instr::JumpIfGtI64Slots(3, 2, 4)));
        assert!(matches!(
            optimized[3],
            Instr::AddConstI64SlotAndJumpIfLe(3, 1, 2, 1)
        ));
        assert_eq!(mapping, vec![0, 0, 0, 1, 2, 3, 3, 4, 5]);
    }

    #[test]
    fn test_slot_gt_branch_fusion_uses_loop_slot_update_guard_issue_6167() {
        let code = vec![
            Instr::LoadSlotI64(3),
            Instr::LoadSlotI64(2),
            Instr::JumpIfGtI64(5),
            Instr::AddConstI64Slot(3, 1),
            Instr::Jump(0),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);
        assert!(matches!(optimized[0], Instr::JumpIfGtI64Slots(3, 2, 2)));
        assert!(matches!(
            optimized[1],
            Instr::AddConstI64SlotAndJumpIfLe(3, 1, 2, 1)
        ));
        assert_eq!(mapping, vec![0, 0, 0, 1, 1, 2, 3]);
    }

    #[test]
    fn test_slot_gt_branch_fusion_detects_unfused_slot_update_issue_6167() {
        let code = vec![
            Instr::LoadSlotI64(3),
            Instr::LoadSlotI64(2),
            Instr::JumpIfGtI64(8),
            Instr::LoadSlotI64(3),
            Instr::PushI64(1),
            Instr::AddI64,
            Instr::StoreSlotI64(3),
            Instr::Jump(0),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);
        assert!(matches!(optimized[0], Instr::JumpIfGtI64Slots(3, 2, 2)));
        assert!(matches!(
            optimized[1],
            Instr::AddConstI64SlotAndJumpIfLe(3, 1, 2, 1)
        ));
        assert_eq!(mapping, vec![0, 0, 0, 1, 1, 1, 1, 1, 2, 3]);
    }

    #[test]
    fn test_slot_gt_branch_fusion_stays_scoped_without_loop_update_issue_6167() {
        let code = vec![
            Instr::LoadSlotI64(3),
            Instr::LoadSlotI64(2),
            Instr::JumpIfGtI64(5),
            Instr::PushI64(0),
            Instr::Jump(0),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);
        assert!(matches!(optimized[0], Instr::LoadSlotI64(3)));
        assert!(matches!(optimized[1], Instr::LoadSlotI64(2)));
        assert!(matches!(optimized[2], Instr::JumpIfGtI64(5)));
        assert_eq!(mapping, vec![0, 1, 2, 3, 4, 5, 6]);
    }

    #[test]
    fn test_counted_loop_backedge_fusion_issue_6305() {
        let code = vec![
            Instr::JumpIfGtI64Slots(3, 2, 5),
            Instr::PushI64(9),
            Instr::Pop,
            Instr::AddConstI64Slot(3, 1),
            Instr::Jump(0),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);

        assert!(matches!(optimized[0], Instr::JumpIfGtI64Slots(3, 2, 4)));
        assert!(matches!(
            optimized[3],
            Instr::AddConstI64SlotAndJumpIfLe(3, 1, 2, 1)
        ));
        assert_eq!(mapping, vec![0, 1, 2, 3, 3, 4, 5]);
    }

    #[test]
    fn test_counted_loop_backedge_fusion_sees_unfused_header_issue_6305() {
        let code = vec![
            Instr::LoadSlotI64(3),
            Instr::LoadSlotI64(2),
            Instr::JumpIfGtI64(7),
            Instr::PushI64(9),
            Instr::Pop,
            Instr::AddConstI64Slot(3, 1),
            Instr::Jump(0),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);

        assert!(matches!(optimized[0], Instr::JumpIfGtI64Slots(3, 2, 4)));
        assert!(matches!(
            optimized[3],
            Instr::AddConstI64SlotAndJumpIfLe(3, 1, 2, 1)
        ));
        assert_eq!(mapping, vec![0, 0, 0, 1, 2, 3, 3, 4, 5]);
    }

    #[test]
    fn test_counted_loop_backedge_fusion_requires_fallthrough_exit_issue_6305() {
        let code = vec![
            Instr::JumpIfGtI64Slots(3, 2, 6),
            Instr::PushI64(9),
            Instr::Pop,
            Instr::AddConstI64Slot(3, 1),
            Instr::Jump(0),
            Instr::ReturnAny,
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);

        assert!(matches!(optimized[3], Instr::AddConstI64Slot(3, 1)));
        assert!(matches!(optimized[4], Instr::Jump(0)));
        assert_eq!(mapping, vec![0, 1, 2, 3, 4, 5, 6, 7]);
    }

    #[test]
    fn test_counted_loop_backedge_fusion_supports_positive_const_step_issue_6305() {
        let code = vec![
            Instr::JumpIfGtI64Slots(3, 2, 5),
            Instr::PushI64(9),
            Instr::Pop,
            Instr::AddConstI64Slot(3, 2),
            Instr::Jump(0),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);

        assert!(matches!(
            optimized[3],
            Instr::AddConstI64SlotAndJumpIfLe(3, 2, 2, 1)
        ));
        assert_eq!(mapping, vec![0, 1, 2, 3, 3, 4, 5]);
    }

    #[test]
    fn test_counted_loop_backedge_fusion_requires_positive_step_issue_6305() {
        let code = vec![
            Instr::JumpIfGtI64Slots(3, 2, 5),
            Instr::PushI64(9),
            Instr::Pop,
            Instr::AddConstI64Slot(3, -2),
            Instr::Jump(0),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);

        assert!(matches!(optimized[3], Instr::AddConstI64Slot(3, -2)));
        assert!(matches!(optimized[4], Instr::Jump(0)));
        assert_eq!(mapping, vec![0, 1, 2, 3, 4, 5, 6]);
    }

    #[test]
    fn test_slot_arg_call_specialize_fusion_issue_6167() {
        let code = vec![
            Instr::LoadSlotI64(3),
            Instr::LoadSlotI64(5),
            Instr::CallSpecialize(7, 2),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);
        match &optimized[0] {
            Instr::CallSpecializeI64Slots(operands) => {
                assert_eq!(operands.spec_func_index, 7);
                assert_eq!(operands.slots, vec![3, 5]);
            }
            other => panic!("expected CallSpecializeI64Slots, got {other:?}"),
        }
        assert_eq!(mapping, vec![0, 0, 0, 1, 2]);
    }

    #[test]
    fn test_slot_arg_call_specialize_inbounds_fusion_issue_6167() {
        let code = vec![
            Instr::LoadSlotI64(1),
            Instr::CallSpecializeInbounds(9, 1),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);
        match &optimized[0] {
            Instr::CallSpecializeInboundsI64Slots(operands) => {
                assert_eq!(operands.spec_func_index, 9);
                assert_eq!(operands.slots, vec![1]);
            }
            other => panic!("expected CallSpecializeInboundsI64Slots, got {other:?}"),
        }
        assert_eq!(mapping, vec![0, 0, 1, 2]);
    }

    #[test]
    fn test_slot_arg_call_specialize_requires_matching_arg_count_issue_6167() {
        let code = vec![
            Instr::LoadSlotI64(1),
            Instr::LoadSlotI64(2),
            Instr::CallSpecialize(3, 1),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);
        assert!(matches!(optimized[0], Instr::LoadSlotI64(1)));
        match &optimized[1] {
            Instr::CallSpecializeI64Slots(operands) => {
                assert_eq!(operands.spec_func_index, 3);
                assert_eq!(operands.slots, vec![2]);
            }
            other => panic!("expected trailing single slot call fusion, got {other:?}"),
        }
        assert_eq!(mapping, vec![0, 1, 1, 2, 3]);
    }

    #[test]
    fn test_slot_arg_call_resolved_fusion_issue_6315() {
        let code = vec![
            Instr::LoadSlotI64(3),
            Instr::LoadSlotI64(5),
            Instr::CallResolved(7, 2),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);
        match &optimized[0] {
            Instr::CallResolvedI64Slots(operands) => {
                assert_eq!(operands.func_index, 7);
                assert_eq!(operands.slots, vec![3, 5]);
            }
            other => panic!("expected CallResolvedI64Slots, got {other:?}"),
        }
        assert_eq!(mapping, vec![0, 0, 0, 1, 2]);
    }

    #[test]
    fn test_slot_arg_call_inbounds_fusion_issue_6315() {
        let code = vec![
            Instr::LoadSlotI64(1),
            Instr::CallInbounds(9, 1),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);
        match &optimized[0] {
            Instr::CallInboundsI64Slots(operands) => {
                assert_eq!(operands.func_index, 9);
                assert_eq!(operands.slots, vec![1]);
            }
            other => panic!("expected CallInboundsI64Slots, got {other:?}"),
        }
        assert_eq!(mapping, vec![0, 0, 1, 2]);
    }

    #[test]
    fn test_slot_arg_call_resolved_requires_matching_arg_count_issue_6315() {
        let code = vec![
            Instr::LoadSlotI64(1),
            Instr::LoadSlotI64(2),
            Instr::CallResolved(3, 1),
            Instr::ReturnAny,
        ];
        let (optimized, mapping) = optimize(code);
        assert!(matches!(optimized[0], Instr::LoadSlotI64(1)));
        match &optimized[1] {
            Instr::CallResolvedI64Slots(operands) => {
                assert_eq!(operands.func_index, 3);
                assert_eq!(operands.slots, vec![2]);
            }
            other => panic!("expected trailing single slot direct call fusion, got {other:?}"),
        }
        assert_eq!(mapping, vec![0, 1, 1, 2, 3]);
    }

    #[test]
    fn test_slot_i64_to_f64_builtin_fusion_issue_6167() {
        let code = vec![
            Instr::LoadSlotI64(3),
            Instr::CallBuiltin(BuiltinId::Float64, 1),
            Instr::ReturnF64,
        ];
        let (optimized, mapping) = optimize(code);
        assert!(matches!(optimized[0], Instr::LoadSlotI64ToF64(3)));
        assert_eq!(mapping, vec![0, 0, 1, 2]);
    }

    #[test]
    fn test_slot_f64_square_and_load_op_fusion() {
        let square = vec![Instr::LoadSlotF64(2), Instr::DupF64, Instr::MulF64];
        let (optimized, mapping) = optimize(square);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::LoadSquareF64Slot(2)));
        assert_eq!(mapping, vec![0, 0, 0, 1]);

        let repeated_load_square =
            vec![Instr::LoadSlotF64(2), Instr::LoadSlotF64(2), Instr::MulF64];
        let (optimized, mapping) = optimize(repeated_load_square);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::LoadSquareF64Slot(2)));
        assert_eq!(mapping, vec![0, 0, 0, 1]);

        let add = vec![Instr::LoadSlotF64(2), Instr::AddF64];
        let (optimized, mapping) = optimize(add);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::LoadAddF64Slot(2)));
        assert_eq!(mapping, vec![0, 0, 1]);

        let sub = vec![Instr::LoadSlotF64(2), Instr::SubF64];
        let (optimized, _) = optimize(sub);
        assert!(matches!(optimized[0], Instr::LoadSubF64Slot(2)));

        let mul = vec![Instr::LoadSlotF64(2), Instr::MulF64];
        let (optimized, _) = optimize(mul);
        assert!(matches!(optimized[0], Instr::LoadMulF64Slot(2)));

        let div = vec![Instr::LoadSlotF64(2), Instr::DivF64];
        let (optimized, _) = optimize(div);
        assert!(matches!(optimized[0], Instr::LoadDivF64Slot(2)));
    }

    #[test]
    fn test_slot_store_op_requires_same_slot_issue_5091() {
        let code = vec![Instr::LoadSlotI64(1), Instr::AddI64, Instr::StoreSlotI64(2)];

        let (optimized, _) = optimize(code);

        assert_eq!(optimized.len(), 2);
        assert!(matches!(optimized[0], Instr::LoadAddI64Slot(1)));
        assert!(matches!(optimized[1], Instr::StoreSlotI64(2)));
    }

    #[test]
    fn test_compare_jump_fusion() {
        let code = vec![Instr::NeI64, Instr::JumpIfZero(100)];

        let (optimized, _mapping) = optimize(code);

        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::JumpIfEqI64(_)));
    }

    #[test]
    fn test_f64_compare_jump_false_branch_fusion() {
        let code = vec![
            Instr::LeF64,
            Instr::JumpIfZero(4),
            Instr::PushI64(1),
            Instr::Jump(5),
            Instr::PushI64(2),
        ];

        let (optimized, mapping) = optimize(code);

        assert_eq!(optimized.len(), 4);
        assert_eq!(mapping, vec![0, 0, 1, 2, 3, 4]);
        assert!(matches!(optimized[0], Instr::JumpIfNotLeF64(3)));
        assert!(matches!(optimized[2], Instr::Jump(4)));

        let fusions = vec![
            (vec![Instr::NeF64, Instr::JumpIfZero(10)], "eq"),
            (vec![Instr::EqF64, Instr::JumpIfZero(10)], "ne"),
            (vec![Instr::LtF64, Instr::JumpIfZero(10)], "not_lt"),
            (vec![Instr::GtF64, Instr::JumpIfZero(10)], "not_gt"),
            (vec![Instr::LeF64, Instr::JumpIfZero(10)], "not_le"),
            (vec![Instr::GeF64, Instr::JumpIfZero(10)], "not_ge"),
        ];

        for (code, expected) in fusions {
            let (optimized, _) = optimize(code);
            assert_eq!(optimized.len(), 1);
            match (expected, &optimized[0]) {
                ("eq", Instr::JumpIfEqF64(10))
                | ("ne", Instr::JumpIfNeF64(10))
                | ("not_lt", Instr::JumpIfNotLtF64(10))
                | ("not_gt", Instr::JumpIfNotGtF64(10))
                | ("not_le", Instr::JumpIfNotLeF64(10))
                | ("not_ge", Instr::JumpIfNotGeF64(10)) => {}
                _ => panic!("unexpected F64 compare jump fusion: {:?}", optimized[0]),
            }
        }
    }

    #[test]
    fn test_compare_jump_fusion_skips_jump_target_boundary() {
        // Issue #4351: do not fuse across a basic-block entry.
        let code = vec![
            Instr::Jump(2),
            Instr::GtI64,
            Instr::JumpIfZero(4),
            Instr::PushBool(true),
        ];

        let (optimized, mapping) = optimize(code);

        assert_eq!(optimized.len(), 4);
        assert!(matches!(optimized[0], Instr::Jump(2)));
        assert!(matches!(optimized[1], Instr::GtI64));
        assert!(matches!(optimized[2], Instr::JumpIfZero(4)));
        assert_eq!(mapping, vec![0, 1, 2, 3, 4]);
    }

    #[test]
    fn test_no_fusion() {
        let code = vec![Instr::LoadI64("a".to_string()), Instr::PushI64(42)];

        let (optimized, mapping) = optimize(code);

        assert_eq!(optimized.len(), 2);
        assert_eq!(mapping.len(), 3); // 2 instructions + 1 end position
        assert_eq!(mapping[0], 0);
        assert_eq!(mapping[1], 1); // No fusion, sequential mapping
        assert_eq!(mapping[2], 2); // End position
    }

    #[test]
    fn test_optimize_with_protected_ranges() {
        // Code with some instructions that should be protected
        let code = vec![
            // Protected range [0, 2)
            Instr::LoadI64("a".to_string()), // 0 - protected
            Instr::AddI64,                   // 1 - protected
            // Unprotected range [2, 4)
            Instr::LoadI64("b".to_string()), // 2 - should fuse with 3
            Instr::SubI64,                   // 3
        ];

        let protected = vec![(0, 2)];
        let (optimized, mapping) = optimize_with_protected_ranges(code, &protected);

        // Protected instructions should remain as-is
        assert!(matches!(optimized[0], Instr::LoadI64(_)));
        assert!(matches!(optimized[1], Instr::AddI64));

        // Unprotected should be fused
        assert!(matches!(optimized[2], Instr::LoadSubI64(_)));

        assert_eq!(optimized.len(), 3);
        assert_eq!(mapping[0], 0);
        assert_eq!(mapping[1], 1);
        assert_eq!(mapping[2], 2);
        assert_eq!(mapping[3], 2); // Fused into same index
        assert_eq!(mapping[4], 3); // End position
    }

    #[test]
    fn test_protected_range_prevents_cross_boundary_fusion() {
        // Fusion pattern straddles protected boundary
        let code = vec![
            Instr::LoadI64("a".to_string()),  // 0 - unprotected, fusion start
            Instr::AddI64,                    // 1 - protected, fusion would continue here
            Instr::StoreI64("a".to_string()), // 2 - protected, fusion would end here
        ];

        let protected = vec![(1, 3)];
        let (optimized, _mapping) = optimize_with_protected_ranges(code, &protected);

        // Should NOT fuse because fusion crosses into protected range
        assert_eq!(optimized.len(), 3);
        assert!(matches!(optimized[0], Instr::LoadI64(_)));
        assert!(matches!(optimized[1], Instr::AddI64));
        assert!(matches!(optimized[2], Instr::StoreI64(_)));
    }

    #[test]
    fn test_empty_protected_ranges_uses_standard_optimize() {
        let code = vec![Instr::LoadI64("x".to_string()), Instr::AddI64];

        let (optimized, _) = optimize_with_protected_ranges(code, &[]);

        // Should fuse normally
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::LoadAddI64(_)));
    }

    #[test]
    fn test_duplicate_i64_load_cse_uses_dup_issue_5185() {
        let code = vec![
            Instr::LoadI64("x".to_string()),
            Instr::LoadI64("x".to_string()),
            Instr::EqI64,
        ];

        let (optimized, mapping) = optimize(code);

        assert_eq!(optimized.len(), 3);
        assert!(matches!(&optimized[0], Instr::LoadI64(name) if name == "x"));
        assert!(matches!(optimized[1], Instr::DupI64));
        assert!(matches!(optimized[2], Instr::EqI64));
        assert_eq!(mapping, vec![0, 1, 2, 3]);
    }

    #[test]
    fn test_duplicate_slot_f64_load_cse_uses_dup_issue_5185() {
        let code = vec![Instr::LoadSlotF64(2), Instr::LoadSlotF64(2), Instr::EqF64];

        let (optimized, _) = optimize(code);

        assert_eq!(optimized.len(), 3);
        assert!(matches!(optimized[0], Instr::LoadSlotF64(2)));
        assert!(matches!(optimized[1], Instr::DupF64));
        assert!(matches!(optimized[2], Instr::EqF64));
    }

    #[test]
    fn test_duplicate_load_cse_respects_protected_ranges_issue_5185() {
        let code = vec![
            Instr::LoadI64("x".to_string()),
            Instr::LoadI64("x".to_string()),
            Instr::AddI64,
        ];

        let (optimized, _) = optimize_with_protected_ranges(code, &[(1, 2)]);

        assert_eq!(optimized.len(), 3);
        assert!(matches!(&optimized[0], Instr::LoadI64(name) if name == "x"));
        assert!(matches!(&optimized[1], Instr::LoadI64(name) if name == "x"));
        assert!(matches!(optimized[2], Instr::AddI64));
    }

    // === Constant folding tests (Issue #3367) ===

    #[test]
    fn test_const_fold_i64_add() {
        let code = vec![Instr::PushI64(3), Instr::PushI64(4), Instr::AddI64];
        let (optimized, _) = optimize(code);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::PushI64(7)));
    }

    #[test]
    fn test_const_fold_i64_sub() {
        let code = vec![Instr::PushI64(10), Instr::PushI64(3), Instr::SubI64];
        let (optimized, _) = optimize(code);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::PushI64(7)));
    }

    #[test]
    fn test_const_fold_i64_mul() {
        let code = vec![Instr::PushI64(5), Instr::PushI64(6), Instr::MulI64];
        let (optimized, _) = optimize(code);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::PushI64(30)));
    }

    #[test]
    fn test_const_fold_i64_mod() {
        let code = vec![Instr::PushI64(10), Instr::PushI64(3), Instr::ModI64];
        let (optimized, _) = optimize(code);
        assert_eq!(optimized.len(), 1);
        assert!(matches!(optimized[0], Instr::PushI64(1)));
    }

    #[test]
    fn test_const_fold_i64_mod_zero_no_fold() {
        // Division by zero should not be folded
        let code = vec![Instr::PushI64(10), Instr::PushI64(0), Instr::ModI64];
        let (optimized, _) = optimize(code);
        assert_eq!(optimized.len(), 3); // Not folded
    }

    #[test]
    fn test_const_fold_f64_add() {
        let code = vec![Instr::PushF64(1.5), Instr::PushF64(2.5), Instr::AddF64];
        let (optimized, _) = optimize(code);
        assert_eq!(optimized.len(), 1);
        match &optimized[0] {
            Instr::PushF64(v) => assert!((*v - 4.0).abs() < 1e-10),
            _ => panic!("Expected PushF64"),
        }
    }

    #[test]
    fn test_const_fold_f64_mul() {
        let code = vec![Instr::PushF64(3.0), Instr::PushF64(4.0), Instr::MulF64];
        let (optimized, _) = optimize(code);
        assert_eq!(optimized.len(), 1);
        match &optimized[0] {
            Instr::PushF64(v) => assert!((*v - 12.0).abs() < 1e-10),
            _ => panic!("Expected PushF64"),
        }
    }

    #[test]
    fn test_const_fold_f64_div() {
        let code = vec![Instr::PushF64(10.0), Instr::PushF64(4.0), Instr::DivF64];
        let (optimized, _) = optimize(code);
        assert_eq!(optimized.len(), 1);
        match &optimized[0] {
            Instr::PushF64(v) => assert!((*v - 2.5).abs() < 1e-10),
            _ => panic!("Expected PushF64"),
        }
    }
}
