#!/usr/bin/env bash
# check_numeric_matrix_reduced.sh — sjulia reduced numeric matrix comparator
# (Issue #8697, parent #8683).

set -euo pipefail
cd "$(dirname "$0")/.."

ORACLE="${ORACLE:-subset_julia_vm/tests/fixtures/numeric/numeric_matrix_reduced_8696.tsv}"
ALLOWLIST="${ALLOWLIST:-docs/vm/NUMERIC_MATRIX_REDUCED_ALLOWLIST.tsv}"
SKIPLIST="${SKIPLIST:-}"
SJULIA_BIN="${SJULIA_BIN:-./target/release/sjulia}"
OUT_DIR="${OUT_DIR:-target/numeric-matrix-reduced}"
TIMEOUT_SECONDS="${TIMEOUT_SECONDS:-300}"

mkdir -p "$OUT_DIR"
PROBE="$OUT_DIR/probe.jl"
ACTUAL="$OUT_DIR/sjulia.tsv"
DIFF="$OUT_DIR/diff.tsv"

if [[ ! -f "$ORACLE" ]]; then
  echo "ERROR: oracle TSV not found: $ORACLE" >&2
  exit 1
fi
if [[ ! -f "$ALLOWLIST" ]]; then
  echo "ERROR: allowlist not found: $ALLOWLIST" >&2
  exit 1
fi
if [[ ! -x "$SJULIA_BIN" ]]; then
  echo "ERROR: sjulia binary not executable: $SJULIA_BIN" >&2
  echo "Build it with: cargo build --release -p subset_julia_vm --bin sjulia --features repl" >&2
  exit 1
fi

julia --startup-file=no - "$ORACLE" "$PROBE" "$SKIPLIST" <<'JL'
const ORACLE = ARGS[1]
const PROBE = ARGS[2]
const SKIPLIST = ARGS[3]

const TYPE_EXPR = Dict(
    "Bool" => "true",
    "Int8" => "Int8(3)",
    "Int16" => "Int16(3)",
    "Int32" => "Int32(3)",
    "Int64" => "Int64(3)",
    "Int128" => "Int128(3)",
    "UInt8" => "UInt8(5)",
    "UInt16" => "UInt16(5)",
    "UInt32" => "UInt32(5)",
    "UInt64" => "UInt64(5)",
    "UInt128" => "UInt128(5)",
    "Float16" => "Float16(2.5)",
    "Float32" => "Float32(2.5)",
    "Float64" => "Float64(2.5)",
    "BigInt" => "big(7)",
    "BigFloat" => "BigFloat(\"2.5\")",
)

function key_for(fields)
    if length(fields) >= 13
        return join((fields[1], fields[2], fields[3], fields[10], fields[11]), "|")
    end
    return join((fields[1], fields[2], fields[3]), "|")
end

function read_skip_rules(path)
    rules = Tuple{String,String,String,String,String}[]
    isfile(path) || return rules
    for line in eachline(path)
        startswith(line, "left_type\t") && continue
        startswith(line, "operator\t") && continue
        isempty(strip(line)) && continue
        f = split(line, '\t')
        if length(f) >= 5
            push!(rules, (f[1], f[2], f[3], f[4], f[5]))
        elseif length(f) >= 3
            push!(rules, ("ANY", "ANY", f[1], f[2], f[3]))
        else
            error("malformed skiplist row: $line")
        end
    end
    return rules
end

function skipped(fields, rules)
    length(fields) >= 13 || return false
    left_type = fields[1]
    left_label = fields[10]
    op = fields[3]
    right_type = fields[2]
    right_label = fields[11]
    return any(rules) do rule
        lty, llab, rop, rty, rlab = rule
        (lty == "ANY" || lty == left_type) &&
            (llab == "ANY" || llab == left_label) &&
            (rop == "ANY" || rop == op) &&
            (rty == "ANY" || rty == right_type) &&
            (rlab == "ANY" || rlab == right_label)
    end
end

function expr_for(fields)
    op = fields[3]
    a = length(fields) >= 13 ? fields[12] : TYPE_EXPR[fields[1]]
    b = length(fields) >= 13 ? fields[13] : TYPE_EXPR[fields[2]]
    if op in ("+", "-", "*", "/", "==", "!=", "<", "<=", ">", ">=")
        return "($a) $op ($b)"
    end
    return "$op($a, $b)"
end

open(PROBE, "w") do io
    println(io, "# Generated by scripts/check_numeric_matrix_reduced.sh.")
    skip_rules = read_skip_rules(SKIPLIST)
    for line in eachline(ORACLE)
        startswith(line, "left_type\t") && continue
        fields = split(line, '\t')
        skipped(fields, skip_rules) && continue
        key = key_for(fields)
        expr = expr_for(fields)
        println(io, "try")
        println(io, "    r = ", expr)
        println(io, "    println(\"", escape_string(key), "\\t\", \"ok\\t\", string(typeof(r)), \"\\t\", repr(r), \"\\tnone\")")
        println(io, "catch e")
        println(io, "    println(\"", escape_string(key), "\\t\", \"error\\tnone\\tnone\\t\", string(typeof(e)))")
        println(io, "end")
    end
end
JL

timeout "$TIMEOUT_SECONDS" "$SJULIA_BIN" "$PROBE" > "$ACTUAL"

julia --startup-file=no - "$ORACLE" "$ACTUAL" "$ALLOWLIST" "$DIFF" "$SKIPLIST" <<'JL'
const ORACLE = ARGS[1]
const ACTUAL = ARGS[2]
const ALLOWLIST = ARGS[3]
const DIFF = ARGS[4]
const SKIPLIST = ARGS[5]

struct ExpectedRow
    left::String
    right::String
    op::String
    left_label::String
    right_label::String
    status::String
    result_type::String
    result_value::String
    exception_type::String
end

struct ActualRow
    status::String
    result_type::String
    result_value::String
    exception_type::String
end

function read_expected(path)
    rows = Dict{String,ExpectedRow}()
    for line in eachline(path)
        startswith(line, "left_type\t") && continue
        f = split(line, '\t')
        if length(f) >= 13
            key = join((f[1], f[2], f[3], f[10], f[11]), "|")
            rows[key] = ExpectedRow(f[1], f[2], f[3], f[10], f[11], f[6], f[7], f[8], f[9])
        else
            key = join((f[1], f[2], f[3]), "|")
            rows[key] = ExpectedRow(f[1], f[2], f[3], "normal", "normal", f[6], f[7], f[8], f[9])
        end
    end
    rows
end

function read_actual(path)
    rows = Dict{String,ActualRow}()
    for line in eachline(path)
        f = split(line, '\t')
        length(f) == 5 || error("malformed actual row: $line")
        rows[f[1]] = ActualRow(f[2], f[3], f[4], f[5])
    end
    rows
end

function read_allowlist(path)
    rows = Dict{String,Tuple{String,String,Int,String}}()
    for line in eachline(path)
        startswith(line, "family\t") && continue
        f = split(line, '\t')
        length(f) >= 5 || error("malformed allowlist row: $line")
        rows[f[1]] = (f[2], f[3], parse(Int, f[4]), f[5])
    end
    rows
end

function read_skip_rules(path)
    rules = Vector{Tuple{Tuple{String,String,String,String,String},Tuple{String,Int,String}}}()
    isfile(path) || return rules
    for line in eachline(path)
        startswith(line, "left_type\t") && continue
        startswith(line, "operator\t") && continue
        isempty(strip(line)) && continue
        f = split(line, '\t')
        if length(f) >= 8
            push!(rules, ((f[1], f[2], f[3], f[4], f[5]), (f[6], parse(Int, f[7]), f[8])))
        elseif length(f) >= 6
            push!(rules, (("ANY", "ANY", f[1], f[2], f[3]), (f[4], parse(Int, f[5]), f[6])))
        else
            error("malformed skiplist row: $line")
        end
    end
    return rules
end

function skip_key(row::ExpectedRow, skip_rules)
    for (key, _data) in skip_rules
        lty, llab, op, rty, rlab = key
        if (lty == "ANY" || lty == row.left) &&
            (llab == "ANY" || llab == row.left_label) &&
            (op == "ANY" || op == row.op) &&
            (rty == "ANY" || rty == row.right) &&
            (rlab == "ANY" || rlab == row.right_label)
            return key
        end
    end
    return nothing
end

function family(expected::ExpectedRow, actual::ActualRow)
    if expected.status != actual.status
        return "status"
    elseif expected.result_type != actual.result_type
        return "result-type"
    elseif expected.result_value != actual.result_value
        if expected.result_type == "BigFloat"
            return "bigfloat-precision"
        end
        return "value-repr"
    elseif expected.exception_type != actual.exception_type
        return "exception-type"
    end
    return "match"
end

function main()
    expected = read_expected(ORACLE)
    actual = read_actual(ACTUAL)
    allowlist = read_allowlist(ALLOWLIST)
    skip_rules = read_skip_rules(SKIPLIST)
    skipped_counts = Dict{Tuple{String,String,String,String,String},Int}()
    expected = filter(expected) do pair
        row = pair.second
        key = skip_key(row, skip_rules)
        if key !== nothing
            skipped_counts[key] = get(skipped_counts, key, 0) + 1
            return false
        end
        return true
    end
    missing = sort(collect(setdiff(keys(expected), keys(actual))))
    extra = sort(collect(setdiff(keys(actual), keys(expected))))
    isempty(missing) || error("missing actual rows: $(join(missing[1:min(end, 5)], ", "))")
    isempty(extra) || error("extra actual rows: $(join(extra[1:min(end, 5)], ", "))")

    counts = Dict{String,Int}()
    examples = Dict{String,String}()
    diff_rows = String[]
    for key in sort(collect(keys(expected)))
        exp = expected[key]
        act = actual[key]
        fam = family(exp, act)
        fam == "match" && continue
        counts[fam] = get(counts, fam, 0) + 1
        get!(examples, fam, "$key expected=($(exp.status),$(exp.result_type),$(exp.result_value),$(exp.exception_type)) actual=($(act.status),$(act.result_type),$(act.result_value),$(act.exception_type))")
        push!(diff_rows, join((
            exp.left, exp.right, exp.op, exp.left_label, exp.right_label, fam,
            exp.status, exp.result_type, exp.result_value, exp.exception_type,
            act.status, act.result_type, act.result_value, act.exception_type,
        ), '\t'))
    end

    open(DIFF, "w") do io
        println(io, "left_type\tright_type\toperator\tleft_label\tright_label\tfamily\texpected_status\texpected_type\texpected_value\texpected_exception\tactual_status\tactual_type\tactual_value\tactual_exception")
        for row in diff_rows
            println(io, row)
        end
    end

    failed = false
    for fam in sort(collect(keys(counts)))
        if !haskey(allowlist, fam)
            println(stderr, "ERROR: unallowlisted numeric matrix divergence family: $fam ($(counts[fam]) rows)")
            println(stderr, "  example: ", examples[fam])
            failed = true
            continue
        end
        classification, issue, expected_count, _reason = allowlist[fam]
        if classification == "" || issue == ""
            println(stderr, "ERROR: allowlist family $fam lacks classification or issue")
            failed = true
        end
        if counts[fam] != expected_count
            println(stderr, "RATCHET: family $fam count changed: expected $expected_count, observed $(counts[fam])")
            println(stderr, "  example: ", examples[fam])
            failed = true
        end
    end
    for fam in sort(collect(keys(allowlist)))
        if !haskey(counts, fam)
            println(stderr, "RATCHET: allowlist family $fam is stale; remove it from $ALLOWLIST")
            failed = true
        end
    end
    for (key, (_issue, expected_count, _reason)) in skip_rules
        observed = get(skipped_counts, key, 0)
        if observed != expected_count
            println(stderr, "RATCHET: skiplist key $(join(key, "|")) count changed: expected $expected_count, observed $observed")
            failed = true
        end
    end
    failed && exit(1)
    total = sum(values(counts); init=0)
    skipped_total = sum(values(skipped_counts); init=0)
    println("OK: numeric matrix reduced comparison observed $total allowlisted divergences across $(length(counts)) families.")
    skipped_total > 0 && println("  skipped\t$skipped_total\trows from $SKIPLIST")
    for fam in sort(collect(keys(counts)))
        classification, issue, expected_count, reason = allowlist[fam]
        println("  $fam\t$expected_count\t$classification\t$issue\t$reason")
    end
    println("diff: $DIFF")
end

main()
JL
