#!/usr/bin/env bash
# check_upstream_test_sweep_allowlist.sh — upstream julia/test sweep ratchet
# (Issue #8701, parent #8684).
#
# Verifies that:
#   1. Every currently non-passing sweep row is covered by the allowlist.
#   2. Every non-scope-out non-passing row has a linked issue.
#   3. No allowlist file now passes; fixed rows must shrink the allowlist.
#   4. sjulia testset counts do not drop below the committed baseline.
#
# Usage:
#   bash scripts/check_upstream_test_sweep_allowlist.sh
#   SWEEP_TSV=target/upstream-test-sweep/sweep.tsv \
#     bash scripts/check_upstream_test_sweep_allowlist.sh
#
# Depends on:
#   - target/upstream-test-sweep/sweep.tsv, generated by:
#       scripts/upstream_test_sweep.sh > target/upstream-test-sweep/sweep.tsv
#   - docs/vm/UPSTREAM_TEST_SWEEP_ALLOWLIST.tsv
#   - docs/vm/UPSTREAM_TEST_SWEEP_BASELINE.tsv

set -euo pipefail
cd "$(dirname "$0")/.."

SWEEP_TSV="${SWEEP_TSV:-target/upstream-test-sweep/sweep.tsv}"
ALLOWLIST="${ALLOWLIST:-docs/vm/UPSTREAM_TEST_SWEEP_ALLOWLIST.tsv}"
BASELINE="${BASELINE:-docs/vm/UPSTREAM_TEST_SWEEP_BASELINE.tsv}"

if [[ ! -f "$SWEEP_TSV" ]]; then
  echo "SKIP: $SWEEP_TSV not found. Run scripts/upstream_test_sweep.sh first."
  exit 0
fi
if [[ ! -f "$ALLOWLIST" ]]; then
  echo "ERROR: $ALLOWLIST not found." >&2
  exit 1
fi
if [[ ! -f "$BASELINE" ]]; then
  echo "ERROR: $BASELINE not found." >&2
  exit 1
fi

tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/upstream-test-sweep-ratchet.XXXXXX")"
trap 'rm -rf "$tmpdir"' EXIT

current_nonpass="$tmpdir/current_nonpass.tsv"
current_nonpass_files="$tmpdir/current_nonpass_files.txt"
allowlist_files="$tmpdir/allowlist_files.txt"

awk -F'\t' 'NR > 1 && $4 != "pass" { print $1 "\t" $4 "\t" $6 "\t" $7 "\t" $8 }' \
  "$SWEEP_TSV" > "$current_nonpass"
awk -F'\t' '{ print $1 }' "$current_nonpass" | sort -u > "$current_nonpass_files"
awk -F'\t' 'NR > 1 { print $1 }' "$ALLOWLIST" | sort -u > "$allowlist_files"

failed=0

uncovered="$(comm -23 "$current_nonpass_files" "$allowlist_files" || true)"
if [[ -n "$uncovered" ]]; then
  echo "ERROR: upstream test sweep failures not covered by $ALLOWLIST:" >&2
  while IFS= read -r file; do
    [[ -n "$file" ]] || continue
    echo "  $file" >&2
    awk -F'\t' -v file="$file" 'NR > 1 && $1 == file { print "    status=" $4 " first_error=" $9; exit }' "$SWEEP_TSV" >&2
  done <<< "$uncovered"
  failed=1
fi

unclassified="$(awk -F'\t' '$4 == "" || $4 == "unclassified" { print $1 }' "$current_nonpass" | sort -u)"
if [[ -n "$unclassified" ]]; then
  echo "ERROR: upstream test sweep has unclassified non-pass rows:" >&2
  echo "$unclassified" | sed 's/^/  /' >&2
  failed=1
fi

missing_issue="$(awk -F'\t' '$4 != "scope-out" && $5 == "" { print $1 }' "$current_nonpass" | sort -u)"
if [[ -n "$missing_issue" ]]; then
  echo "ERROR: non-scope-out sweep failures must link issue numbers:" >&2
  echo "$missing_issue" | sed 's/^/  /' >&2
  failed=1
fi

stale="$(comm -13 "$current_nonpass_files" "$allowlist_files" || true)"
if [[ -n "$stale" ]]; then
  echo "RATCHET: these upstream test files now pass; remove them from $ALLOWLIST:" >&2
  echo "$stale" | sed 's/^/  /' >&2
  failed=1
fi

testset_regressions="$(
  awk -F'\t' '
    NR == FNR {
      if (FNR > 1) {
        baseline_status[$1] = $4
        baseline_testsets[$1] = $6 + 0
      }
      next
    }
    FNR > 1 && ($1 in baseline_testsets) {
      current_status = $4
      current_testsets = $6 + 0
      if (baseline_status[$1] == "pass" && current_status != "pass") {
        print $1 "\tbaseline_status=pass\tcurrent_status=" current_status
      } else if (current_testsets < baseline_testsets[$1]) {
        print $1 "\tbaseline_sjulia_testsets=" baseline_testsets[$1] "\tcurrent_sjulia_testsets=" current_testsets
      }
    }
  ' "$BASELINE" "$SWEEP_TSV"
)"
if [[ -n "$testset_regressions" ]]; then
  echo "RATCHET: sjulia upstream-test coverage regressed below $BASELINE:" >&2
  echo "$testset_regressions" | sed 's/^/  /' >&2
  failed=1
fi

if [[ "$failed" -ne 0 ]]; then
  exit 1
fi

nonpass_count="$(wc -l < "$current_nonpass" | tr -d ' ')"
allowlist_count="$(wc -l < "$allowlist_files" | tr -d ' ')"
echo "OK: $nonpass_count non-pass upstream-test rows, all covered by $ALLOWLIST ($allowlist_count files)."
