#!/usr/bin/env bash
# check_parser_corpus_allowlist.sh — corpus allowlist ratchet (Issue #8637 / #8636).
#
# Verifies that:
#   1. Every file failing in the current corpus sweep is covered by an entry in
#      docs/vm/PARSER_CORPUS_ALLOWLIST.toml.
#   2. No entry in the allowlist covers a file that NOW passes (would indicate
#      the allowlist has not been shrunk — ratchet is enforced by requiring
#      entries to be removed when a gap is fixed).
#
# Exit code: 0 = allowlist is complete and ratcheted, 1 = new divergence OR
#            stale allowlist entry (file now passes).
#
# Usage:
#   bash scripts/check_parser_corpus_allowlist.sh [--sweep-only] [--ratchet-only]
#     --sweep-only    only check new divergences (skip stale-entry check)
#     --ratchet-only  only check stale entries (skip new-divergence check)
#
# Depends on:
#   - target/parser_corpus/sweep.tsv  (generated by parser_corpus_sweep.sh)
#   - docs/vm/PARSER_CORPUS_ALLOWLIST.toml
#   Run parser_corpus_sweep.sh first for the full shell ratchet. In lightweight
#   check_*.sh batches, a missing TSV is treated as an explicit skip because the
#   full sweep builds a parser binary and scans the Julia submodule.

set -euo pipefail
cd "$(dirname "$0")/.."

SWEEP_TSV="target/parser_corpus/sweep.tsv"
ALLOWLIST="docs/vm/PARSER_CORPUS_ALLOWLIST.toml"
SWEEP_ONLY=false
RATCHET_ONLY=false

while [ $# -gt 0 ]; do
  case "$1" in
    --sweep-only)    SWEEP_ONLY=true;    shift ;;
    --ratchet-only)  RATCHET_ONLY=true;  shift ;;
    -h|--help)
      sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "ERROR: unknown arg $1 (see --help)" >&2; exit 2 ;;
  esac
done

if [ ! -f "$SWEEP_TSV" ]; then
  echo "SKIP: $SWEEP_TSV not found. Run: bash scripts/parser_corpus_sweep.sh && bash scripts/check_parser_corpus_allowlist.sh for the full corpus ratchet."
  exit 0
fi
if [ ! -f "$ALLOWLIST" ]; then
  echo "ERROR: $ALLOWLIST not found." >&2
  exit 1
fi

# --- Extract files from TSV and allowlist ---

# Files that currently fail (have at least one record in sweep.tsv):
FAILING_FILES=$(grep -v '^#' "$SWEEP_TSV" | awk -F'\t' '{print $1}' | sort -u)

# Files listed in the allowlist:
ALLOWLIST_FILES=$(grep '^file = ' "$ALLOWLIST" | sed "s/^file = '\\(.*\\)'/\\1/;s/^file = \"\\(.*\\)\"/\\1/" | sort -u)

FAILED=0

# --- Check 1: new divergences not in allowlist ---
if [ "$RATCHET_ONLY" != "true" ]; then
  UNCOVERED=$(comm -23 <(echo "$FAILING_FILES") <(echo "$ALLOWLIST_FILES") || true)
  if [ -n "$UNCOVERED" ]; then
    echo "ERROR: New corpus divergences not covered by $ALLOWLIST:"
    echo "$UNCOVERED" | while read -r f; do
      echo "  $f"
      grep -m1 "^$f	" "$SWEEP_TSV" | awk -F'\t' '{print "    first error: " $3 " — " $5}' || true
    done
    FAILED=1
  fi
fi

# --- Check 2: stale allowlist entries (file now passes) ---
if [ "$SWEEP_ONLY" != "true" ]; then
  STALE=$(comm -13 <(echo "$FAILING_FILES") <(echo "$ALLOWLIST_FILES") || true)
  if [ -n "$STALE" ]; then
    echo "RATCHET: These files now parse cleanly — remove them from $ALLOWLIST:"
    echo "$STALE" | while read -r f; do
      echo "  $f"
    done
    FAILED=1
  fi
fi

if [ "$FAILED" -eq 0 ]; then
  FAIL_COUNT=$(echo "$FAILING_FILES" | grep -c . || true)
  ALLOW_COUNT=$(echo "$ALLOWLIST_FILES" | grep -c . || true)
  echo "OK: $FAIL_COUNT failing files, all covered by allowlist ($ALLOW_COUNT entries)."
else
  exit 1
fi
