#!/usr/bin/env python3
"""Inventory Rust unsafe sites and gate new unannotated unsafe code.

Existing unannotated unsafe sites are grandfathered through
docs/vm/UNSAFE_INVENTORY_BASELINE.tsv. New unsafe sites must carry a nearby
`Safety:` comment with an Issue reference.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path


UNSAFE_RE = re.compile(r"\bunsafe\b")
ISSUE_RE = re.compile(r"(?:Issue\s+)?#\d+")


@dataclass(frozen=True)
class UnsafeSite:
    fingerprint: str
    path: str
    line: int
    kind: str
    has_safety_issue_comment: bool
    text: str


def classify(line: str) -> str:
    stripped = line.strip()
    if re.search(r"\bunsafe\s+extern\b", stripped):
        return "unsafe_extern"
    if re.search(r"\bunsafe\s+fn\b", stripped):
        return "unsafe_fn"
    if re.search(r"\bunsafe\s+impl\b", stripped):
        return "unsafe_impl"
    if re.search(r"\bunsafe\s+trait\b", stripped):
        return "unsafe_trait"
    if re.search(r"\bunsafe\s*\{", stripped):
        return "unsafe_block"
    return "unsafe_token"


def has_safety_comment(lines: list[str], index: int) -> bool:
    start = max(0, index - 4)
    window = "\n".join(lines[start : index + 1])
    return "Safety:" in window and ISSUE_RE.search(window) is not None


def fingerprint(path: str, kind: str, text: str) -> str:
    payload = f"{path}\0{kind}\0{text.strip()}".encode()
    return hashlib.sha256(payload).hexdigest()[:16]


def rust_roots(root: Path) -> list[Path]:
    candidates = [
        *root.glob("subset_julia_vm*/src"),
        root / "subset_julia_vm_runtime" / "src",
    ]
    return sorted({p for p in candidates if p.is_dir()})


def rust_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for src_root in rust_roots(root):
        files.extend(sorted(src_root.rglob("*.rs")))
    for extra in [root / "build.rs", root / "subset_julia_vm" / "build.rs"]:
        if extra.is_file():
            files.append(extra)
    return files


def scan(root: Path) -> list[UnsafeSite]:
    sites: list[UnsafeSite] = []
    for path in rust_files(root):
        rel = path.relative_to(root).as_posix()
        lines = path.read_text(encoding="utf-8").splitlines()
        for idx, line in enumerate(lines):
            if not UNSAFE_RE.search(line):
                continue
            if line.lstrip().startswith("//"):
                continue
            kind = classify(line)
            text = line.strip()
            sites.append(
                UnsafeSite(
                    fingerprint=fingerprint(rel, kind, text),
                    path=rel,
                    line=idx + 1,
                    kind=kind,
                    has_safety_issue_comment=has_safety_comment(lines, idx),
                    text=text,
                )
            )
    return sites


def read_baseline(path: Path) -> set[str]:
    if not path.exists():
        raise FileNotFoundError(path)
    with path.open(newline="", encoding="utf-8") as fh:
        return {row["fingerprint"] for row in csv.DictReader(fh, delimiter="\t")}


def write_inventory(path: Path, sites: list[UnsafeSite]) -> None:
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=[
                "fingerprint",
                "path",
                "line",
                "kind",
                "has_safety_issue_comment",
                "text",
            ],
            delimiter="\t",
            lineterminator="\n",
        )
        writer.writeheader()
        for site in sites:
            writer.writerow(
                {
                    "fingerprint": site.fingerprint,
                    "path": site.path,
                    "line": site.line,
                    "kind": site.kind,
                    "has_safety_issue_comment": str(site.has_safety_issue_comment).lower(),
                    "text": site.text,
                }
            )


def write_report(path: Path, sites: list[UnsafeSite], new_unannotated: list[UnsafeSite]) -> None:
    by_kind = Counter(site.kind for site in sites)
    by_root = Counter(site.path.split("/", 1)[0] for site in sites)
    lines = [
        "# Unsafe Inventory",
        "",
        "Generated by `scripts/unsafe_inventory.py`.",
        "",
        f"- total unsafe sites: {len(sites)}",
        f"- safety-commented sites: {sum(1 for site in sites if site.has_safety_issue_comment)}",
        f"- new unannotated sites: {len(new_unannotated)}",
        "",
        "## By Kind",
        "",
        "| kind | count |",
        "|---|---:|",
    ]
    lines.extend(f"| {kind} | {count} |" for kind, count in sorted(by_kind.items()))
    lines.extend(["", "## By Root", "", "| root | count |", "|---|---:|"])
    lines.extend(f"| {root} | {count} |" for root, count in sorted(by_root.items()))
    if new_unannotated:
        lines.extend(["", "## New Unannotated Unsafe Sites", ""])
        for site in new_unannotated:
            lines.append(f"- `{site.path}:{site.line}` `{site.kind}` `{site.text}`")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="repository root")
    parser.add_argument("--out-dir", default="target/ub-safety", help="output directory")
    parser.add_argument(
        "--baseline",
        default="docs/vm/UNSAFE_INVENTORY_BASELINE.tsv",
        help="grandfathered unannotated unsafe baseline",
    )
    parser.add_argument("--check", action="store_true", help="fail on new unannotated unsafe")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    out_dir = Path(args.out_dir)
    if not out_dir.is_absolute():
        out_dir = root / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    sites = scan(root)
    baseline_path = Path(args.baseline)
    if not baseline_path.is_absolute():
        baseline_path = root / baseline_path
    if args.check:
        baseline = read_baseline(baseline_path)
        new_unannotated = [
            site
            for site in sites
            if not site.has_safety_issue_comment and site.fingerprint not in baseline
        ]
    else:
        new_unannotated = []

    write_inventory(out_dir / "unsafe_inventory.tsv", sites)
    write_report(out_dir / "report.md", sites, new_unannotated)

    print(f"unsafe_sites={len(sites)}")
    print(f"unsafe_safety_commented={sum(1 for site in sites if site.has_safety_issue_comment)}")
    print(f"unsafe_new_unannotated={len(new_unannotated)}")
    print(f"wrote {out_dir / 'unsafe_inventory.tsv'}")
    print(f"wrote {out_dir / 'report.md'}")

    if new_unannotated:
        for site in new_unannotated:
            print(
                f"ERROR: new unannotated unsafe site: {site.path}:{site.line}: {site.text}",
                file=sys.stderr,
            )
        print(
            "Add a nearby `Safety:` comment with an Issue reference, or update the baseline after review.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
