//! Shared typed scalar bytecode selection for compiler and VM specialization.

use crate::Instr;
use subset_julia_vm_types::ir::core::BinaryOp;

/// Single source of truth for the **typed scalar binary instruction** chosen for
/// a primitive `Int64`/`Float64` operand pair (Issue #8192).
///
/// Binary-op bytecode is generated by two independent paths: the main compiler
/// (`compile_builtin_binary_op`, through `typed_instr_for_intrinsic`) and the
/// runtime argument-type specializer
/// (`vm::specialize::expr::FunctionSpecializer::emit_binary_op`, introduced in
/// #8167). Before #8192 each kept its own `op + type -> Instr` table, so a fix
/// to one silently missed the other (this surfaced in #8183 / PR #8189). Both
/// paths resolve the VM instruction here.
///
/// `result_is_float` is whether the already-promoted operands are `Float64`
/// rather than `Int64`. Returns `None` for ops with no single typed instruction
/// on the I64/F64 fast path (`÷`, `^`, float `%`, `&&` / `||`, identity /
/// subtype), which each caller lowers with its own dynamic / short-circuit path.
///
/// INVARIANT: every `Instr` this returns must be accepted by the native
/// typed-loop recognizer's whitelist (`vm::executable`); otherwise a specialized
/// hot loop emitting it silently drops off the native fast path. The
/// `shared_binary_table_only_emits_typed_loop_recognized_instrs_issue_8192`
/// guard test (in `vm::executable`) enforces this. See
/// `docs/vm/BINARY_DISPATCH.md` ("Two binary-op codegen paths").
pub fn typed_scalar_binary_instr(op: BinaryOp, result_is_float: bool) -> Option<Instr> {
    Some(match op {
        BinaryOp::Add if result_is_float => Instr::AddF64,
        BinaryOp::Add => Instr::AddI64,
        BinaryOp::Sub if result_is_float => Instr::SubF64,
        BinaryOp::Sub => Instr::SubI64,
        BinaryOp::Mul if result_is_float => Instr::MulF64,
        BinaryOp::Mul => Instr::MulI64,
        // `/` always yields Float64 (operands are coerced to F64 first).
        BinaryOp::Div => Instr::DivF64,
        // Integer `%` has a typed op; float `%` falls back to DynamicMod.
        BinaryOp::Mod if !result_is_float => Instr::ModI64,
        BinaryOp::Eq if result_is_float => Instr::EqF64,
        BinaryOp::Eq => Instr::EqI64,
        BinaryOp::Ne if result_is_float => Instr::NeF64,
        BinaryOp::Ne => Instr::NeI64,
        BinaryOp::Lt if result_is_float => Instr::LtF64,
        BinaryOp::Lt => Instr::LtI64,
        BinaryOp::Gt if result_is_float => Instr::GtF64,
        BinaryOp::Gt => Instr::GtI64,
        BinaryOp::Le if result_is_float => Instr::LeF64,
        BinaryOp::Le => Instr::LeI64,
        BinaryOp::Ge if result_is_float => Instr::GeF64,
        BinaryOp::Ge => Instr::GeI64,
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_instr_variant(actual: Option<Instr>, expected: Instr) {
        let actual = actual.expect("expected typed scalar instruction");
        assert_eq!(
            std::mem::discriminant(&actual),
            std::mem::discriminant(&expected)
        );
    }

    #[test]
    fn typed_scalar_binary_instr_maps_i64_fast_path() {
        let cases = [
            (BinaryOp::Add, Instr::AddI64),
            (BinaryOp::Sub, Instr::SubI64),
            (BinaryOp::Mul, Instr::MulI64),
            (BinaryOp::Mod, Instr::ModI64),
            (BinaryOp::Eq, Instr::EqI64),
            (BinaryOp::Ne, Instr::NeI64),
            (BinaryOp::Lt, Instr::LtI64),
            (BinaryOp::Le, Instr::LeI64),
            (BinaryOp::Gt, Instr::GtI64),
            (BinaryOp::Ge, Instr::GeI64),
        ];
        for (op, instr) in cases {
            assert_instr_variant(typed_scalar_binary_instr(op, false), instr);
        }
    }

    #[test]
    fn typed_scalar_binary_instr_maps_f64_fast_path() {
        let cases = [
            (BinaryOp::Add, Instr::AddF64),
            (BinaryOp::Sub, Instr::SubF64),
            (BinaryOp::Mul, Instr::MulF64),
            (BinaryOp::Div, Instr::DivF64),
            (BinaryOp::Eq, Instr::EqF64),
            (BinaryOp::Ne, Instr::NeF64),
            (BinaryOp::Lt, Instr::LtF64),
            (BinaryOp::Le, Instr::LeF64),
            (BinaryOp::Gt, Instr::GtF64),
            (BinaryOp::Ge, Instr::GeF64),
        ];
        for (op, instr) in cases {
            assert_instr_variant(typed_scalar_binary_instr(op, true), instr);
        }
    }

    #[test]
    fn typed_scalar_binary_instr_rejects_unsupported_fast_paths() {
        assert_instr_variant(
            typed_scalar_binary_instr(BinaryOp::Div, false),
            Instr::DivF64,
        );
        assert!(typed_scalar_binary_instr(BinaryOp::Mod, true).is_none());
        for op in [BinaryOp::Pow, BinaryOp::And, BinaryOp::Or] {
            assert!(typed_scalar_binary_instr(op, false).is_none());
            assert!(typed_scalar_binary_instr(op, true).is_none());
        }
    }
}
