//! Shared convert() implementation for the VM (Issue #2259).
//!
//! This module provides a single `convert_value` function used by both
//! `builtins_exec.rs` and `builtins_types.rs`, eliminating duplicated
//! match arms that previously diverged when new types were added.
//!
//! The convert handler supports all numeric types (Int8-Int128, UInt8-UInt128,
//! Float16, Float32, Float64, BigInt, BigFloat), String, and Bool.
//! When adding a new Value variant, only this file needs to be updated.
//!
//! Integer converters are generated by `define_integer_converter!` macro to
//! ensure all source Value variants are handled uniformly (Issue #2288).
//!
//! Narrowing integer / float→integer conversions are range-checked and throw
//! `InexactError` when the value does not fit, matching the type constructor
//! path in `type_ops/conversion.rs` and upstream Julia (Issue #5192). Before
//! this, `convert(Int8, 300)` silently wrapped to `44`; now it throws
//! `InexactError`, the same as the `Int8(300)` constructor.

#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]
// This module performs explicit numeric type conversions (Julia `convert(T, x)`).
// All `as` casts here are intentional type coercions — sign loss/truncation is
// caught at runtime via InexactError checks (range-checked `try_from` for
// integer sources, truncation round-trip for float sources).
#![allow(clippy::cast_sign_loss)]

use super::error::VmError;
use super::value::{RustBigFloat, RustBigInt, Value, BIGFLOAT_PRECISION};

/// Convert a Value to the target type specified by name.
///
/// Returns `Ok(value)` on success, `Err(VmError)` if conversion is not supported.
pub(crate) fn convert_value(type_name: &str, value: &Value) -> Result<Value, VmError> {
    if type_name.starts_with("SubArray") {
        match value {
            Value::Struct(s) if s.struct_name.starts_with("SubArray") => {
                return Ok(value.clone());
            }
            Value::StructRef(_) => {
                return Ok(value.clone());
            }
            _ => {}
        }
    }

    // Abstract types: return the value unchanged (identity conversion).
    // This handles cases like convert(Number, x) or convert(Any, x) that arise
    // from promote/convert chains in generic Number-typed methods.
    if matches!(
        type_name,
        "Any" | "Number" | "Real" | "Integer" | "Signed" | "Unsigned" | "AbstractFloat"
    ) {
        return Ok(value.clone());
    }

    match type_name {
        "Float64" => convert_to_f64(value),
        "Float32" => convert_to_f32(value),
        "Float16" => convert_to_f16(value),
        "Int" if crate::types::native_int_type_name() == "Int32" => convert_to_i32(value),
        "Int64" | "Int" => convert_to_i64(value),
        "Int128" => convert_to_i128(value),
        "Int32" => convert_to_i32(value),
        "Int16" => convert_to_i16(value),
        "Int8" => convert_to_i8(value),
        "UInt" if crate::types::native_uint_type_name() == "UInt32" => convert_to_u32(value),
        "UInt64" | "UInt" => convert_to_u64(value),
        "UInt128" => convert_to_u128(value),
        "UInt32" => convert_to_u32(value),
        "UInt16" => convert_to_u16(value),
        "UInt8" => convert_to_u8(value),
        "BigInt" => convert_to_bigint(value),
        "BigFloat" => convert_to_bigfloat(value),
        "String" => convert_to_string(value),
        "Symbol" => convert_to_symbol(value),
        "Bool" => convert_to_bool(value),
        "Char" => convert_to_char(value),
        _ => Err(VmError::TypeError(format!(
            "unsupported target type for convert: {}",
            type_name
        ))),
    }
}

/// Convert an integer codepoint (or an existing `Char`) to `Char` (Issue #5407).
///
/// Mirrors upstream `Char(::Integer)` / `convert(::Type{Char}, ::Integer)`:
/// `convert(Char, 97) == 'a'`, and `convert(Char, 'a')` is the identity. `Char`
/// in this VM wraps a Rust `char`, so only valid Unicode scalar values are
/// representable; out-of-range, negative, or surrogate codepoints throw a
/// `TypeError` instead of constructing an invalid `Char`. Non-integer sources
/// (Float, String, ...) are rejected, matching the lack of a `Char(::Real)`
/// method upstream.
fn convert_to_char(value: &Value) -> Result<Value, VmError> {
    // Identity: convert(Char, ::Char) returns the value unchanged.
    if let Value::Char(_) = value {
        return Ok(value.clone());
    }
    let codepoint: Option<u32> = match value {
        Value::I8(n) => u32::try_from(*n).ok(),
        Value::I16(n) => u32::try_from(*n).ok(),
        Value::I32(n) => u32::try_from(*n).ok(),
        Value::I64(n) => u32::try_from(*n).ok(),
        Value::I128(n) => u32::try_from(*n).ok(),
        Value::U8(n) => Some(u32::from(*n)),
        Value::U16(n) => Some(u32::from(*n)),
        Value::U32(n) => Some(*n),
        Value::U64(n) => u32::try_from(*n).ok(),
        Value::U128(n) => u32::try_from(*n).ok(),
        // Bool is a subtype of Integer in Julia: Char(true) == '\x01'.
        Value::Bool(b) => Some(u32::from(*b)),
        _ => {
            return Err(VmError::TypeError(format!(
                "Cannot convert {:?} to Char",
                value
            )))
        }
    };
    codepoint
        .and_then(char::from_u32)
        .map(Value::Char)
        .ok_or_else(|| VmError::TypeError(format!("Char: invalid codepoint {:?}", value)))
}

fn convert_to_symbol(value: &Value) -> Result<Value, VmError> {
    match value {
        Value::Symbol(_) => Ok(value.clone()),
        _ => Err(VmError::TypeError(format!(
            "Cannot convert {:?} to Symbol",
            value.value_type()
        ))),
    }
}

/// Range-checked integer→integer conversion (Issue #5192).
///
/// Uses `try_from` so out-of-range values throw `InexactError` (matching the
/// type constructor in `type_ops/conversion.rs` and upstream Julia) instead of
/// silently bit-wrapping. The error message mirrors the constructor's
/// `"{Type}({value})"` shape, which the VM's `InexactError` renders as
/// `InexactError: {Type}({value})`.
fn checked_int_to_int<To, From>(value: From, julia_name: &str) -> Result<To, VmError>
where
    To: TryFrom<From>,
    From: core::fmt::Display + Copy,
{
    To::try_from(value).map_err(|_| VmError::InexactError(format!("{}({})", julia_name, value)))
}

/// Range-checked float→integer conversion (Issue #5192).
///
/// Mirrors the constructor path: truncate toward zero, then verify the value
/// round-trips exactly. Non-integral or out-of-range floats throw
/// `InexactError`.
macro_rules! checked_float_to_int {
    ($v:expr, $rust_ty:ty, $variant:ident, $float_ty:ty, $julia_name:expr) => {{
        let f: $float_ty = $v;
        let truncated = (f as $rust_ty) as $float_ty;
        if truncated == f {
            Ok(Value::$variant(f as $rust_ty))
        } else {
            Err(VmError::InexactError(format!("{}({})", $julia_name, f)))
        }
    }};
}

/// Macro to generate integer type converter functions.
///
/// Each generated function converts any numeric Value variant to the target
/// integer type. This ensures all source types are handled uniformly —
/// adding a new source Value variant only requires updating this macro.
///
/// Narrowing / out-of-range conversions throw `InexactError` exactly like the
/// type constructor (Issue #5192); they no longer silently bit-wrap.
///
/// # Parameters
/// - `$fn_name`: Name of the generated function (e.g., `convert_to_i128`)
/// - `$rust_ty`: Rust primitive type (e.g., `i128`)
/// - `$variant`: Value enum variant (e.g., `I128`)
/// - `$julia_name`: Julia type name for error messages (e.g., `"Int128"`)
/// - `$bool_one`: The literal `1` value for the target type (e.g., `1i128`)
macro_rules! define_integer_converter {
    ($fn_name:ident, $rust_ty:ty, $variant:ident, $julia_name:expr, $bool_one:expr) => {
        fn $fn_name(value: &Value) -> Result<Value, VmError> {
            match value {
                Value::I8(v) => {
                    checked_int_to_int::<$rust_ty, _>(*v, $julia_name).map(Value::$variant)
                }
                Value::I16(v) => {
                    checked_int_to_int::<$rust_ty, _>(*v, $julia_name).map(Value::$variant)
                }
                Value::I32(v) => {
                    checked_int_to_int::<$rust_ty, _>(*v, $julia_name).map(Value::$variant)
                }
                Value::I64(v) => {
                    checked_int_to_int::<$rust_ty, _>(*v, $julia_name).map(Value::$variant)
                }
                Value::I128(v) => {
                    checked_int_to_int::<$rust_ty, _>(*v, $julia_name).map(Value::$variant)
                }
                Value::U8(v) => {
                    checked_int_to_int::<$rust_ty, _>(*v, $julia_name).map(Value::$variant)
                }
                Value::U16(v) => {
                    checked_int_to_int::<$rust_ty, _>(*v, $julia_name).map(Value::$variant)
                }
                Value::U32(v) => {
                    checked_int_to_int::<$rust_ty, _>(*v, $julia_name).map(Value::$variant)
                }
                Value::U64(v) => {
                    checked_int_to_int::<$rust_ty, _>(*v, $julia_name).map(Value::$variant)
                }
                Value::U128(v) => {
                    checked_int_to_int::<$rust_ty, _>(*v, $julia_name).map(Value::$variant)
                }
                Value::F64(v) => checked_float_to_int!(*v, $rust_ty, $variant, f64, $julia_name),
                Value::F32(v) => checked_float_to_int!(*v, $rust_ty, $variant, f32, $julia_name),
                Value::F16(v) => {
                    checked_float_to_int!(v.to_f64(), $rust_ty, $variant, f64, $julia_name)
                }
                Value::Bool(v) => Ok(Value::$variant(if *v { $bool_one } else { 0 as $rust_ty })),
                _ => Err(VmError::TypeError(format!(
                    concat!("cannot convert {:?} to ", $julia_name),
                    value
                ))),
            }
        }
    };
}

// Generate all integer converter functions from a single source of truth.
// To add a new integer type: add one line here + a dispatch arm in convert_value().
define_integer_converter!(convert_to_i8, i8, I8, "Int8", 1i8);
define_integer_converter!(convert_to_i16, i16, I16, "Int16", 1i16);
define_integer_converter!(convert_to_i32, i32, I32, "Int32", 1i32);
define_integer_converter!(convert_to_i64, i64, I64, "Int64", 1i64);
define_integer_converter!(convert_to_i128, i128, I128, "Int128", 1i128);
define_integer_converter!(convert_to_u8, u8, U8, "UInt8", 1u8);
define_integer_converter!(convert_to_u16, u16, U16, "UInt16", 1u16);
define_integer_converter!(convert_to_u32, u32, U32, "UInt32", 1u32);
define_integer_converter!(convert_to_u64, u64, U64, "UInt64", 1u64);
define_integer_converter!(convert_to_u128, u128, U128, "UInt128", 1u128);

/// Convert any numeric Value to Float64.
fn convert_to_f64(value: &Value) -> Result<Value, VmError> {
    match value {
        Value::I64(v) => Ok(Value::F64(*v as f64)),
        Value::F64(v) => Ok(Value::F64(*v)),
        Value::F32(v) => Ok(Value::F64(*v as f64)),
        Value::F16(v) => Ok(Value::F64(v.to_f64())),
        Value::I8(v) => Ok(Value::F64(*v as f64)),
        Value::I16(v) => Ok(Value::F64(*v as f64)),
        Value::I32(v) => Ok(Value::F64(*v as f64)),
        Value::I128(v) => Ok(Value::F64(*v as f64)),
        Value::U8(v) => Ok(Value::F64(*v as f64)),
        Value::U16(v) => Ok(Value::F64(*v as f64)),
        Value::U32(v) => Ok(Value::F64(*v as f64)),
        Value::U64(v) => Ok(Value::F64(*v as f64)),
        Value::U128(v) => Ok(Value::F64(*v as f64)),
        Value::Bool(v) => Ok(Value::F64(if *v { 1.0 } else { 0.0 })),
        Value::Str(s) => s
            .parse::<f64>()
            .map(Value::F64)
            .map_err(|_| VmError::TypeError(format!("cannot convert \"{}\" to Float64", s))),
        _ => Err(VmError::TypeError(format!(
            "cannot convert {:?} to Float64",
            value
        ))),
    }
}

/// Convert any numeric Value to Float32.
fn convert_to_f32(value: &Value) -> Result<Value, VmError> {
    match value {
        Value::I64(v) => Ok(Value::F32(*v as f32)),
        Value::F64(v) => Ok(Value::F32(*v as f32)),
        Value::F32(v) => Ok(Value::F32(*v)),
        Value::F16(v) => Ok(Value::F32(v.to_f64() as f32)),
        Value::I8(v) => Ok(Value::F32(*v as f32)),
        Value::I16(v) => Ok(Value::F32(*v as f32)),
        Value::I32(v) => Ok(Value::F32(*v as f32)),
        Value::I128(v) => Ok(Value::F32(*v as f32)),
        Value::U8(v) => Ok(Value::F32(*v as f32)),
        Value::U16(v) => Ok(Value::F32(*v as f32)),
        Value::U32(v) => Ok(Value::F32(*v as f32)),
        Value::U64(v) => Ok(Value::F32(*v as f32)),
        Value::U128(v) => Ok(Value::F32(*v as f32)),
        Value::Bool(v) => Ok(Value::F32(if *v { 1.0 } else { 0.0 })),
        Value::Str(s) => s
            .parse::<f32>()
            .map(Value::F32)
            .map_err(|_| VmError::TypeError(format!("cannot convert \"{}\" to Float32", s))),
        _ => Err(VmError::TypeError(format!(
            "cannot convert {:?} to Float32",
            value
        ))),
    }
}

/// Convert any numeric Value to Float16.
fn convert_to_f16(value: &Value) -> Result<Value, VmError> {
    use half::f16;
    match value {
        Value::F16(v) => Ok(Value::F16(*v)),
        Value::F64(v) => Ok(Value::F16(f16::from_f64(*v))),
        Value::F32(v) => Ok(Value::F16(f16::from_f32(*v))),
        Value::I64(v) => Ok(Value::F16(f16::from_f64(*v as f64))),
        Value::I8(v) => Ok(Value::F16(f16::from_f64(*v as f64))),
        Value::I16(v) => Ok(Value::F16(f16::from_f64(*v as f64))),
        Value::I32(v) => Ok(Value::F16(f16::from_f64(*v as f64))),
        Value::I128(v) => Ok(Value::F16(f16::from_f64(*v as f64))),
        Value::U8(v) => Ok(Value::F16(f16::from_f64(*v as f64))),
        Value::U16(v) => Ok(Value::F16(f16::from_f64(*v as f64))),
        Value::U32(v) => Ok(Value::F16(f16::from_f64(*v as f64))),
        Value::U64(v) => Ok(Value::F16(f16::from_f64(*v as f64))),
        Value::U128(v) => Ok(Value::F16(f16::from_f64(*v as f64))),
        Value::Bool(v) => Ok(Value::F16(f16::from_f64(if *v { 1.0 } else { 0.0 }))),
        _ => Err(VmError::TypeError(format!(
            "cannot convert {:?} to Float16",
            value
        ))),
    }
}

/// Convert any numeric Value to BigInt.
fn convert_to_bigint(value: &Value) -> Result<Value, VmError> {
    match value {
        Value::BigInt(v) => Ok(Value::BigInt(v.clone())),
        Value::I64(v) => Ok(Value::BigInt(RustBigInt::from(*v))),
        Value::I128(v) => Ok(Value::BigInt(RustBigInt::from(*v))),
        Value::I8(v) => Ok(Value::BigInt(RustBigInt::from(*v as i64))),
        Value::I16(v) => Ok(Value::BigInt(RustBigInt::from(*v as i64))),
        Value::I32(v) => Ok(Value::BigInt(RustBigInt::from(*v as i64))),
        Value::U8(v) => Ok(Value::BigInt(RustBigInt::from(*v as u64))),
        Value::U16(v) => Ok(Value::BigInt(RustBigInt::from(*v as u64))),
        Value::U32(v) => Ok(Value::BigInt(RustBigInt::from(*v as u64))),
        Value::U64(v) => Ok(Value::BigInt(RustBigInt::from(*v))),
        Value::U128(v) => Ok(Value::BigInt(RustBigInt::from(*v))),
        Value::Bool(v) => Ok(Value::BigInt(RustBigInt::from(if *v {
            1i64
        } else {
            0i64
        }))),
        _ => Err(VmError::TypeError(format!(
            "cannot convert {:?} to BigInt",
            value
        ))),
    }
}

/// Convert any numeric Value to BigFloat.
fn convert_to_bigfloat(value: &Value) -> Result<Value, VmError> {
    match value {
        Value::BigFloat(v) => Ok(Value::BigFloat(v.clone())),
        Value::F64(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v,
            BIGFLOAT_PRECISION,
        ))),
        Value::F32(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::F16(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            v.to_f64(),
            BIGFLOAT_PRECISION,
        ))),
        Value::I64(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::I128(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::I8(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::I16(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::I32(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::U8(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::U16(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::U32(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::U64(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::U128(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            *v as f64,
            BIGFLOAT_PRECISION,
        ))),
        Value::Bool(v) => Ok(Value::BigFloat(RustBigFloat::from_f64(
            if *v { 1.0 } else { 0.0 },
            BIGFLOAT_PRECISION,
        ))),
        Value::BigInt(v) => {
            // Convert BigInt to BigFloat via f64 (lossy for very large values)
            use std::str::FromStr;
            let f = f64::from_str(&v.to_string()).unwrap_or(0.0);
            Ok(Value::BigFloat(RustBigFloat::from_f64(
                f,
                BIGFLOAT_PRECISION,
            )))
        }
        _ => Err(VmError::TypeError(format!(
            "cannot convert {:?} to BigFloat",
            value
        ))),
    }
}

/// Convert Value to String.
fn convert_to_string(value: &Value) -> Result<Value, VmError> {
    match value {
        Value::I64(v) => Ok(Value::Str(v.to_string())),
        Value::F64(v) => Ok(Value::Str(v.to_string())),
        Value::Str(s) => Ok(Value::Str(s.clone())),
        Value::Char(c) => Ok(Value::Str(c.to_string())),
        _ => Err(VmError::TypeError(format!(
            "cannot convert {:?} to String",
            value
        ))),
    }
}

/// Convert Value to Bool.
fn convert_to_bool(value: &Value) -> Result<Value, VmError> {
    // Mirror upstream `Bool(x::Real) = x==0 ? false : x==1 ? true :
    // throw(InexactError(:Bool, Bool, x))` and `convert(::Type{Bool}, x::Number)
    // = Bool(x)`: only 0 and 1 are valid. A lenient truthiness test (`x != 0`)
    // accepted any nonzero value as `true`, which silently mis-converted e.g.
    // `convert(Bool, 2)` to `true` instead of raising `InexactError` (Issue #7970).
    macro_rules! int_to_bool {
        ($v:expr) => {{
            let v = $v;
            if v == 0 {
                Ok(Value::Bool(false))
            } else if v == 1 {
                Ok(Value::Bool(true))
            } else {
                Err(VmError::InexactError(format!("Bool({})", v)))
            }
        }};
    }
    fn float_to_bool(f: f64) -> Result<Value, VmError> {
        if f == 0.0 {
            Ok(Value::Bool(false))
        } else if f == 1.0 {
            Ok(Value::Bool(true))
        } else {
            Err(VmError::InexactError(format!("Bool({})", f)))
        }
    }
    match value {
        Value::Bool(v) => Ok(Value::Bool(*v)),
        Value::I8(v) => int_to_bool!(*v),
        Value::I16(v) => int_to_bool!(*v),
        Value::I32(v) => int_to_bool!(*v),
        Value::I64(v) => int_to_bool!(*v),
        Value::I128(v) => int_to_bool!(*v),
        Value::U8(v) => int_to_bool!(*v),
        Value::U16(v) => int_to_bool!(*v),
        Value::U32(v) => int_to_bool!(*v),
        Value::U64(v) => int_to_bool!(*v),
        Value::U128(v) => int_to_bool!(*v),
        Value::F64(v) => float_to_bool(*v),
        Value::F32(v) => float_to_bool(f64::from(*v)),
        Value::F16(v) => float_to_bool(v.to_f64()),
        _ => Err(VmError::TypeError(format!(
            "cannot convert {:?} to Bool",
            value
        ))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Issue #5192: convert() to a narrower integer type must range-check and
    /// return InexactError on out-of-range values instead of silently wrapping.
    #[test]
    fn test_convert_narrow_int_out_of_range_is_inexact() {
        // Signed targets
        assert!(matches!(
            convert_value("Int8", &Value::I64(300)),
            Err(VmError::InexactError(_))
        ));
        assert!(matches!(
            convert_value("Int8", &Value::I64(128)),
            Err(VmError::InexactError(_))
        ));
        assert!(matches!(
            convert_value("Int8", &Value::I64(-129)),
            Err(VmError::InexactError(_))
        ));
        assert!(matches!(
            convert_value("Int16", &Value::I64(40000)),
            Err(VmError::InexactError(_))
        ));
        // Unsigned targets reject overflow and negatives
        assert!(matches!(
            convert_value("UInt8", &Value::I64(300)),
            Err(VmError::InexactError(_))
        ));
        assert!(matches!(
            convert_value("UInt8", &Value::I64(-1)),
            Err(VmError::InexactError(_))
        ));
        // Cross-width signed/unsigned mismatch (matches constructor)
        assert!(matches!(
            convert_value("Int8", &Value::U8(200)),
            Err(VmError::InexactError(_))
        ));
        assert!(matches!(
            convert_value("Int64", &Value::U64(u64::MAX)),
            Err(VmError::InexactError(_))
        ));
    }

    /// Issue #5192: the error message matches the constructor's `Type(value)`
    /// shape (rendered as `InexactError: Int8(300)`).
    #[test]
    fn test_convert_inexact_message_matches_constructor_shape() {
        match convert_value("Int8", &Value::I64(300)) {
            Err(VmError::InexactError(msg)) => assert_eq!(msg, "Int8(300)"),
            other => panic!("expected InexactError, got {:?}", other),
        }
        match convert_value("UInt8", &Value::I64(-1)) {
            Err(VmError::InexactError(msg)) => assert_eq!(msg, "UInt8(-1)"),
            other => panic!("expected InexactError, got {:?}", other),
        }
    }

    /// Issue #7970: `convert(Bool, x)` only accepts 0/1 and raises InexactError
    /// for any other value, instead of a lenient `x != 0` truthiness test.
    #[test]
    fn test_convert_to_bool_range_checked_7970() {
        // 0/1 from signed, unsigned, and float sources succeed.
        assert!(matches!(
            convert_value("Bool", &Value::I64(0)),
            Ok(Value::Bool(false))
        ));
        assert!(matches!(
            convert_value("Bool", &Value::I64(1)),
            Ok(Value::Bool(true))
        ));
        assert!(matches!(
            convert_value("Bool", &Value::U8(1)),
            Ok(Value::Bool(true))
        ));
        assert!(matches!(
            convert_value("Bool", &Value::F64(0.0)),
            Ok(Value::Bool(false))
        ));
        assert!(matches!(
            convert_value("Bool", &Value::Bool(true)),
            Ok(Value::Bool(true))
        ));
        // Out-of-range values raise InexactError with the `Bool(value)` shape.
        match convert_value("Bool", &Value::I64(2)) {
            Err(VmError::InexactError(msg)) => assert_eq!(msg, "Bool(2)"),
            other => panic!("expected InexactError, got {:?}", other),
        }
        assert!(matches!(
            convert_value("Bool", &Value::I64(-1)),
            Err(VmError::InexactError(_))
        ));
        assert!(matches!(
            convert_value("Bool", &Value::U8(2)),
            Err(VmError::InexactError(_))
        ));
        assert!(matches!(
            convert_value("Bool", &Value::F64(2.0)),
            Err(VmError::InexactError(_))
        ));
        assert!(matches!(
            convert_value("Bool", &Value::F64(0.5)),
            Err(VmError::InexactError(_))
        ));
    }

    /// Issue #5192: float->int conversions reject non-integral / out-of-range
    /// values while accepting in-range integral floats.
    #[test]
    fn test_convert_float_to_int_range_checked() {
        assert!(matches!(
            convert_value("Int8", &Value::F64(3.5)),
            Err(VmError::InexactError(_))
        ));
        assert!(matches!(
            convert_value("Int8", &Value::F64(300.0)),
            Err(VmError::InexactError(_))
        ));
        assert!(matches!(
            convert_value("UInt8", &Value::F64(-1.0)),
            Err(VmError::InexactError(_))
        ));
        // In-range integral floats still succeed
        assert!(matches!(
            convert_value("Int8", &Value::F64(3.0)),
            Ok(Value::I8(3))
        ));
        assert!(matches!(
            convert_value("Int8", &Value::F64(-1.0)),
            Ok(Value::I8(-1))
        ));
    }

    /// Issue #5192: boundary, widening, same-type, and Bool conversions must
    /// still succeed (no regression of valid conversions).
    #[test]
    fn test_convert_valid_int_conversions_unaffected() {
        assert!(matches!(
            convert_value("Int8", &Value::I64(127)),
            Ok(Value::I8(127))
        ));
        assert!(matches!(
            convert_value("Int8", &Value::I64(-128)),
            Ok(Value::I8(-128))
        ));
        assert!(matches!(
            convert_value("UInt8", &Value::I64(255)),
            Ok(Value::U8(255))
        ));
        assert!(matches!(
            convert_value("UInt8", &Value::I64(0)),
            Ok(Value::U8(0))
        ));
        // Widening
        assert!(matches!(
            convert_value("Int64", &Value::I8(-5)),
            Ok(Value::I64(-5))
        ));
        assert!(matches!(
            convert_value("Int128", &Value::I32(100)),
            Ok(Value::I128(100))
        ));
        // Same-type
        assert!(matches!(
            convert_value("Int8", &Value::I8(5)),
            Ok(Value::I8(5))
        ));
        // Bool
        assert!(matches!(
            convert_value("Int64", &Value::Bool(true)),
            Ok(Value::I64(1))
        ));
        assert!(matches!(
            convert_value("UInt8", &Value::Bool(true)),
            Ok(Value::U8(1))
        ));
    }

    /// Verify that convert_value handles all numeric Value variants for each target type.
    /// This prevents the recurring bug where new types are added but convert handlers
    /// are not updated (Issue #1786, #2249).
    #[test]
    fn test_convert_handler_completeness() {
        let test_values: Vec<Value> = vec![
            Value::I8(1),
            Value::I16(1),
            Value::I32(1),
            Value::I64(1),
            Value::I128(1),
            Value::U8(1),
            Value::U16(1),
            Value::U32(1),
            Value::U64(1),
            Value::U128(1),
            Value::F16(half::f16::from_f32(1.0)),
            Value::F32(1.0),
            Value::F64(1.0),
            Value::Bool(true),
        ];

        for target in [
            "Float64", "Float32", "Float16", "Int64", "Int128", "Int32", "Int16", "Int8", "UInt64",
            "UInt128", "UInt32", "UInt16", "UInt8",
        ] {
            for val in &test_values {
                let result = convert_value(target, val);
                assert!(
                    result.is_ok(),
                    "convert({}, {:?}) should succeed but got: {:?}",
                    target,
                    val,
                    result.err()
                );
            }
        }
    }

    /// Verify BigInt conversion from all numeric types (Issue #2492).
    #[test]
    fn test_convert_to_bigint() {
        let test_values: Vec<Value> = vec![
            Value::I8(42),
            Value::I16(42),
            Value::I32(42),
            Value::I64(42),
            Value::I128(42),
            Value::U8(42),
            Value::U16(42),
            Value::U32(42),
            Value::U64(42),
            Value::U128(42),
            Value::Bool(true),
        ];

        for val in &test_values {
            let result = convert_value("BigInt", val);
            assert!(
                result.is_ok(),
                "convert(BigInt, {:?}) should succeed but got: {:?}",
                val,
                result.err()
            );
            assert!(
                result.as_ref().is_ok_and(|v| v.is_bigint()),
                "convert(BigInt, {:?}) should return BigInt",
                val
            );
        }

        // BigInt identity conversion
        let big = Value::BigInt(RustBigInt::from(42i64));
        let result = convert_value("BigInt", &big);
        assert!(result.is_ok());
        assert!(result.as_ref().is_ok_and(|v| v.is_bigint()));
    }

    /// Verify BigFloat conversion from all numeric types (Issue #2492).
    #[test]
    fn test_convert_to_bigfloat() {
        let test_values: Vec<Value> = vec![
            Value::I64(42),
            Value::F64(std::f64::consts::PI),
            Value::F32(std::f32::consts::PI),
            Value::F16(half::f16::from_f32(std::f32::consts::PI)),
            Value::Bool(true),
        ];

        for val in &test_values {
            let result = convert_value("BigFloat", val);
            assert!(
                result.is_ok(),
                "convert(BigFloat, {:?}) should succeed but got: {:?}",
                val,
                result.err()
            );
            assert!(
                result.as_ref().is_ok_and(|v| v.is_bigfloat()),
                "convert(BigFloat, {:?}) should return BigFloat",
                val
            );
        }

        // BigFloat identity conversion
        let bf = Value::BigFloat(RustBigFloat::from_f64(
            std::f64::consts::PI,
            BIGFLOAT_PRECISION,
        ));
        let result = convert_value("BigFloat", &bf);
        assert!(result.is_ok());
        assert!(result.as_ref().is_ok_and(|v| v.is_bigfloat()));
    }

    /// Verify abstract type names return identity (Issue #2492).
    #[test]
    fn test_convert_abstract_types_identity() {
        let val = Value::I64(42);
        for abstract_type in &[
            "Any",
            "Number",
            "Real",
            "Integer",
            "Signed",
            "Unsigned",
            "AbstractFloat",
        ] {
            let result = convert_value(abstract_type, &val);
            assert!(
                result.is_ok(),
                "convert({}, I64(42)) should succeed (identity)",
                abstract_type
            );
        }
    }

    /// Verify convert(Char, ::Integer) / identity / invalid codepoint (Issue #5407).
    ///
    /// `Value` does not implement `PartialEq`, so results are checked with
    /// `matches!` rather than `assert_eq!`.
    #[test]
    fn test_convert_to_char() {
        // Integer codepoint -> Char, across integer source variants.
        for val in &[
            Value::I64(97),
            Value::I32(97),
            Value::I16(97),
            Value::I8(97),
            Value::U8(97),
            Value::U16(97),
            Value::U32(97),
            Value::U64(97),
            Value::I128(97),
            Value::U128(97),
        ] {
            assert!(
                matches!(convert_value("Char", val), Ok(Value::Char('a'))),
                "convert(Char, {:?}) should be 'a', got {:?}",
                val,
                convert_value("Char", val)
            );
        }

        // Identity: convert(Char, ::Char).
        assert!(matches!(
            convert_value("Char", &Value::Char('z')),
            Ok(Value::Char('z'))
        ));

        // Bool is a subtype of Integer: Char(true) == '\x01'.
        assert!(matches!(
            convert_value("Char", &Value::Bool(true)),
            Ok(Value::Char('\u{1}'))
        ));

        // Invalid codepoint (negative / surrogate / out of range) -> error,
        // never an invalid Char.
        assert!(convert_value("Char", &Value::I64(-1)).is_err());
        assert!(convert_value("Char", &Value::I64(0x11_0000)).is_err());
        assert!(convert_value("Char", &Value::I64(0xD800)).is_err());

        // String source -> error (no Char(::AbstractString) upstream).
        assert!(convert_value("Char", &Value::Str("a".to_string())).is_err());
    }
}
