# Generated by scripts/gen_subtype_matrix_fixture.jl for Issue #10049.
# Differential subtype (`<:`) property test: each @test asserts sjulia agrees
# with upstream julia's verdict for one type-pair expression.
#
# This measures the `<:` engine surface (CoreType::is_subtype_of /
# JuliaType::is_subtype_of) only. Dispatch-scoring divergences whose `<:`
# verdict already agrees with upstream (e.g. Issue #8806, where the engine
# was correct but the dispatch scorer was not) are out of this instrument's
# reach; see docs/vm/SUBTYPING.md.
#
# Pairs where sjulia disagrees with upstream are excluded here and tracked in
# docs/vm/SUBTYPE_MATRIX_SKIPLIST.tsv. Re-run this generator after a fix lands
# and remove the pair's row from the skiplist to re-include it.

using Test

abstract type Animal10049 end
struct Dog10049 <: Animal10049 end
struct Cat10049 <: Animal10049 end

struct Wrap10049{T} end

abstract type Shape10049{T} end
struct Circle10049{T} <: Shape10049{T}
    r::T
end

struct PairT10049{A,B}
    a::A
    b::B
end

@testset "subtype matrix - abstract_hierarchy (Issue #10049)" begin
    @test (Integer) <: (Real)  # S020
    @test (Real) <: (Number)  # S021
    @test (AbstractFloat) <: (Real)  # S022
    @test (Signed) <: (Integer)  # S023
    @test (Unsigned) <: (Integer)  # S024
    @test !((Number) <: (Real))  # S025
    @test !((Real) <: (Integer))  # S026
    @test (AbstractString) <: (Any)  # S027
    @test !((Any) <: (AbstractString))  # S028
    @test (Animal10049) <: (Any)  # S029
    @test (Dog10049) <: (Animal10049)  # S030
    @test (Cat10049) <: (Animal10049)  # S031
    @test !((Dog10049) <: (Cat10049))  # S032
end

@testset "subtype matrix - array_family (Issue #10049)" begin
    @test !((Vector{Int64}) <: (Vector{Number}))  # S050
    @test (Vector{Int64}) <: (AbstractVector{Int64})  # S051
    @test (Vector{Int64}) <: (AbstractVector)  # S052
    @test !((Vector{Int64}) <: (Matrix))  # S053
    @test !((Matrix{Int64}) <: (Vector))  # S054
    @test (Vector{Int64}) <: (Array)  # S055
    @test (Array{Int64,1}) <: (Vector{Int64})  # S056
    @test !((Tuple{Vector{Int64}}) <: (Tuple{Matrix}))  # S057
    @test !((Tuple{Matrix{Int64}}) <: (Tuple{Vector}))  # S058
    @test (Tuple{Int64,Int64}) <: (Tuple{Real,Real})  # S059
    @test !((Tuple{Int64}) <: (Tuple{Int64,Int64}))  # S060
    @test (Tuple{Int64,Float64}) <: (Tuple{Real,Real})  # S061
    @test (Tuple{}) <: (Tuple{})  # S062
    @test (Tuple{Int64,Vararg{Int64}}) <: (Tuple{Vararg{Integer}})  # S063
    @test (Tuple{Int64,String}) <: (Tuple{Vararg{Any}})  # S064
end

@testset "subtype matrix - concrete_numeric (Issue #10049)" begin
    @test (Int64) <: (Real)  # S001
    @test (Int64) <: (Integer)  # S002
    @test !((Int64) <: (Float64))  # S003
    @test (Float64) <: (AbstractFloat)  # S004
    @test (Bool) <: (Integer)  # S005
    @test !((Bool) <: (Int64))  # S006
    @test (Int64) <: (Int64)  # S007
    @test (Int8) <: (Signed)  # S008
    @test (UInt8) <: (Unsigned)  # S009
    @test !((UInt8) <: (Signed))  # S010
    @test (Complex{Float64}) <: (Complex)  # S011
    @test !((Complex) <: (Complex{Float64}))  # S012
    @test (Rational{Int64}) <: (Rational)  # S013
    @test (Rational{Int64}) <: (Real)  # S014
    @test (BigInt) <: (Integer)  # S015
    @test (BigFloat) <: (AbstractFloat)  # S016
end

@testset "subtype matrix - diagonal_rule (Issue #10049)" begin
    @test (Tuple{Int64,Int64}) <: ((Tuple{T,T} where T))  # S110
    @test !((Tuple{Int64,String}) <: ((Tuple{T,T} where T)))  # S111
end

@testset "subtype matrix - invariant_params (Issue #10049)" begin
    @test (Wrap10049{Int64}) <: (Wrap10049{Int64})  # S040
    @test !((Wrap10049{Int64}) <: (Wrap10049{Real}))  # S041
    @test (Wrap10049{Int64}) <: (Wrap10049)  # S042
    @test !((Wrap10049) <: (Wrap10049{Int64}))  # S043
    @test !((Wrap10049{Int64}) <: (Wrap10049{Number}))  # S044
end

@testset "subtype matrix - nested_where (Issue #10049)" begin
    @test ((PairT10049{A,B} where {A<:Integer,B<:Real})) <: ((PairT10049{A,B} where {A<:Real,B<:Real}))  # S130
    @test (PairT10049{Int64,Float64}) <: ((PairT10049{A,B} where {A<:Integer,B<:Real}))  # S131
    @test !((PairT10049{Float64,Float64}) <: ((PairT10049{A,B} where {A<:Integer,B<:Real})))  # S132
end

@testset "subtype matrix - type_of (Issue #10049)" begin
    @test (Type{Int64}) <: (Type{Int64})  # S100
    @test !((Type{Int64}) <: (Type{Real}))  # S101
    @test (Type{Int64}) <: (Type{<:Real})  # S102
    @test !((Type{String}) <: (Type{<:Real}))  # S103
    @test (DataType) <: (Type)  # S104
    @test (Type{Int64}) <: (DataType)  # S105
end

@testset "subtype matrix - union (Issue #10049)" begin
    @test (Union{Int64,Float64}) <: (Real)  # S070
    @test !((Real) <: (Union{Int64,Float64}))  # S071
    @test (Int64) <: (Union{Int64,String})  # S072
    @test !((String) <: (Union{Int64,Float64}))  # S073
    @test (Union{Int64,String}) <: (Any)  # S074
    @test (Union{}) <: (Int64)  # S075
    @test !((Int64) <: (Union{}))  # S076
end

@testset "subtype matrix - unionall_bounds (Issue #10049)" begin
    @test (Vector{Int64}) <: ((Vector{T} where T<:Integer))  # S080
    @test !((Vector{Float64}) <: ((Vector{T} where T<:Integer)))  # S081
    @test (Vector{Int64}) <: ((Vector{T} where T<:Real))  # S082
    @test (Vector{Int64}) <: ((Vector{T} where Int64<:T<:Real))  # S083
    @test !((Vector{Float32}) <: ((Vector{T} where Int64<:T<:Real)))  # S084
    @test (Circle10049{Real}) <: (Shape10049{>:Int64})  # S085
    @test (Circle10049{Number}) <: (Shape10049{>:Int64})  # S086
    @test (Circle10049{Any}) <: (Shape10049{>:Int64})  # S087
    @test (Circle10049{Int64}) <: (Shape10049{>:Int64})  # S088
    @test !((Circle10049{Int32}) <: (Shape10049{>:Int64}))  # S089
    @test (Vector{Real}) <: (Vector{>:Int64})  # S090
    @test (Vector{Any}) <: (Vector{>:Int64})  # S091
    @test !((Vector{Int32}) <: (Vector{>:Int64}))  # S092
end

@testset "subtype matrix - unionall_vs_unionall (Issue #10049)" begin
    @test ((Vector{T} where T<:Integer)) <: ((Vector{S} where S<:Real))  # S120
    @test !(((Vector{T} where T<:Real)) <: ((Vector{S} where S<:Integer)))  # S121
end

true
